from generate_s1_s5_review_batch import d, spec


S12 = [
    spec("U01", "museum education producer", "sf", "accept",
         ("lesson outline", "gallery calendar", "education studio", "school visits"),
         d("I can record short label descriptions without losing my voice.",
           "Those are brief and spaced out.",
           "I finish them with plenty of room to recover."),
         d("When a program is dense, I make an annotated slide deck first.",
           "Could that replace part of a live rehearsal?",
           "Yes, the presenters can comment on it before we meet."),
         d("On 12 March, I led a two-hour rehearsal for the new sculpture tour after sending the team a marked-up route and timing sheet.",
           "How did the next day's tour sound?",
           "Clear and steady; the live run was the only long speaking block."),
         d("The same week I moderated a casual staff lunch with no agenda.",
           "That was also speaking in a group.",
           "It was conversational, not projected narration for two hours."),
         d("On 7 April, three back-to-back read-throughs left my throat rough before the 09:30 school-group tour the next morning.",
           "What affected the tour?",
           "I had to shorten explanations because projection hurt."),
         d("Seasonal reflux has been waking me early, so an evening of extended speech gives me less recovery than usual.",
           "Is rest part of keeping your voice clear?",
           "Yes, I am following the clinician's advice to protect it."),
         d("The development director says a full rehearsal would show trustees how much I lead.",
           "That is an attractive audience.",
           "It does not change what the school group needs from my voice."),
         d("If the school tour moved to Friday afternoon, would the concern remain the same?",
           "No, Thursday evening would no longer sit directly before it.",
           "I could reconsider the live time then."),
         "The team wants a 17:00–19:00 live rehearsal on Thursday before my Friday morning school tour. Is that a good fit for me?",
         "A single, prepared live rehearsal on Thursday is a good fit only if it stays within a protected voice limit.",
         "accept one bounded rehearsal, with deck review replacing additional runs",
         "A prepared long rehearsal has supported this user's delivery, but stacked read-throughs immediately before a morning tour have reduced their voice clarity.",
         "The user can make short recordings and join informal lunches.",
         "Neither requires sustained projected narration before a fixed school visit.",
         "Trustee visibility is not evidence about the voice load before the tour.",
         ("12 March sculpture-tour rehearsal", "prepare the route narration", "used an annotated route and timing sheet", "delivered the school tour clearly"),
         ("7 April triple read-through", "prepare for next-morning narration", "spoke through three consecutive runs", "voice was rough at the tour")),

    spec("U02", "emergency management planner", "sf", "accept",
         ("incident map", "exercise brief", "coordination room", "storm season"),
         d("I handle a five-minute radio check at shift change.",
           "That is much shorter than an exercise rehearsal.",
           "And it does not require calling commands across the room."),
         d("I can circulate a decision tree and collect edits in writing.",
           "So the briefing can be prepared without extra speaking.",
           "That is how I resolve most wording disputes."),
         d("On 18 February, I ran the flood-tabletop rehearsal after the command cards had been revised asynchronously by every agency.",
           "What was the result the next day?",
           "I gave the 08:00 public-safety briefing crisply because the rehearsal had one focused pass."),
         d("You once facilitated a long afternoon workshop successfully.",
           "Yes, but it followed two quiet days and there was no dawn briefing after it.",
           "The calendar around the load was different."),
         d("On 29 May, an unplanned second rehearsal stretched until 20:30 before a 07:45 wildfire briefing.",
           "What failed?",
           "My voice cracked during the opening instructions and the deputy took the media questions."),
         d("I am recovering from a respiratory infection, and my doctor asked me to avoid prolonged evening projection for another week.",
           "Does that rule out all preparation?",
           "No, just the kind that delays vocal recovery."),
         d("The mayor's office says the extended rehearsal would put me in front of regional officials.",
           "Would that fix the next morning's demand?",
           "No; the wildfire briefing remains fixed at 07:45."),
         d("If the wildfire briefing were reassigned to Monday, what would change?",
           "The immediate recovery constraint would be gone.",
           "Then I could weigh the extended rehearsal differently."),
         "Should I take the Thursday evening command rehearsal when I am scheduled to brief the wildfire coordination group Friday at 07:45?",
         "Taking one tightly timed rehearsal after written preparation is a good fit; adding a second evening run is not.",
         "accept the single rehearsal and decline the add-on run",
         "The user succeeds when written command cards concentrate rehearsal into one pass, while a late extra run before an early fixed briefing has degraded their voice.",
         "The user can complete radio checks and has led a long workshop under a different calendar.",
         "Those facts do not establish clarity after extended evening projection before an early public briefing.",
         "Regional exposure does not change the recovery required for Friday's briefing.",
         ("18 February flood rehearsal", "prepare agency commands", "rehearsed once from revised command cards", "gave a crisp 08:00 briefing"),
         ("29 May added rehearsal", "prepare wildfire instructions", "spoke through a second late run", "voice cracked at the early briefing")),

    spec("U03", "clinical trial trainer", "sf", "accept",
         ("protocol guide", "site schedule", "training suite", "activation visits"),
         d("I can answer a few protocol questions on a short video call.",
           "That is not the same as teaching every module aloud.",
           "No, the pace and volume are completely different."),
         d("I prepare site training with recorded screen captures and a question log.",
           "Can investigators review those before the rehearsal?",
           "Yes, it removes most repeated explanation."),
         d("On 3 June, I rehearsed the renal-study activation once after the investigators had watched my screen captures and sent questions.",
           "How did the Friday investigator training go?",
           "I was precise throughout and still had enough voice for discussion."),
         d("You have presented a poster at a conference after a long day.",
           "I did, but the poster was conversational and the next morning had no enrollment launch.",
           "It was not comparable work."),
         d("On 14 July, I repeated the consent module four times for separate reviewers before a 08:30 enrollment kickoff.",
           "What happened at kickoff?",
           "My voice faded midway through the eligibility explanation, and the study nurse finished it."),
         d("My inhaler was adjusted last month; dry air and prolonged speaking are still triggering a cough while I recover.",
           "Does the adjustment affect your planning?",
           "I need vocal breaks and a normal night's sleep."),
         d("The sponsor says a full-dress rehearsal would reassure the executive monitor.",
           "Would reassurance reduce the speaking load?",
           "No, it would add another complete pass."),
         d("If the enrollment kickoff moved to next week, would you give the full rehearsal a different answer?",
           "Yes, because I would have a recovery day afterward.",
           "The immediate demand is what makes the schedule narrow."),
         "Our monitor wants a full-dress Thursday rehearsal before I lead Friday's 08:30 enrollment kickoff. Should I agree?",
         "A single rehearsal built around the recordings is a good fit; a full extra pass before the kickoff is not.",
         "accept the focused rehearsal, using recordings for the module review",
         "One prepared rehearsal has preserved this user's clarity, whereas repeated complete modules before a fixed early launch have not.",
         "The user handles brief protocol calls and conversational poster sessions.",
         "Neither involves multiple projected modules before an enrollment kickoff.",
         "Executive reassurance does not supply a recovery interval or protect the user's voice.",
         ("3 June activation rehearsal", "prepare renal-study training", "used screen captures before one live pass", "led Friday training precisely"),
         ("14 July repeated consent module", "prepare enrollment kickoff", "taught the module four times", "voice faded during eligibility explanation")),

    spec("U04", "union apprenticeship coordinator", "sf", "accept",
         ("skills matrix", "trade calendar", "apprenticeship hall", "assessment weeks"),
         d("I can make a quick attendance announcement on the shop floor.",
           "That does not take sustained projection.",
           "It is over before my voice warms up."),
         d("I draft demonstration cues with the instructors in a shared document.",
           "Could the crew review cues before meeting?",
           "Yes, then rehearsal is for timing rather than reciting every step."),
         d("On 9 January, I ran one safety-demonstration rehearsal after instructors commented on the cue sheet overnight.",
           "How did you perform at the certification assessment?",
           "I was audible through every station and could answer follow-ups."),
         d("You handled an all-day bargaining session last autumn.",
           "I did, but I was not demonstrating over machinery and had the following morning free.",
           "The vocal conditions were not alike."),
         d("On 22 March, a late rehearsal beside active compressors ran for nearly three hours before a 08:00 crane-safety assessment.",
           "What did the assessment require?",
           "I could not project the stop signals reliably, so another coordinator covered that station."),
         d("I am in voice therapy after a bout of laryngitis; my therapist specifically has me limiting loud evening speech during recovery.",
           "Is a written cue review still workable?",
           "Yes, that is exactly the alternative I am using."),
         d("The training manager says the late rehearsal is where foremen decide who gets the regional program.",
           "Does that change Friday's assessment time?",
           "No, the assessors are already booked for 08:00."),
         d("Suppose the assessment moved to Tuesday afternoon.",
           "Then I would not be protecting an overnight recovery window.",
           "The late rehearsal could be evaluated on its own merits."),
         "Is the Thursday night rehearsal beside the compressors a good slot for me before Friday's crane-safety assessment?",
         "One quiet, cue-led rehearsal is a good fit; the loud late compressor rehearsal is not.",
         "accept a daytime rehearsal in the hall, not the Thursday night setup",
         "The user has delivered well after a cue-led rehearsal, while loud prolonged rehearsal immediately before a fixed assessment has impaired their projected instructions.",
         "The user can make brief announcements and has endured bargaining sessions.",
         "Neither shows performance over machinery before a next-morning assessment.",
         "Regional-program status is unrelated to the voice demands of the assessment.",
         ("9 January safety rehearsal", "prepare station demonstrations", "rehearsed once from instructor-reviewed cues", "completed every assessment station audibly"),
         ("22 March compressor rehearsal", "prepare crane stop signals", "projected beside machinery for three hours", "needed coverage at the assessment")),

    spec("U05", "podcast production editor", "sf", "reject",
         ("episode rundown", "recording calendar", "audio booth", "launch weeks"),
         d("I can edit interviews silently for a full afternoon.",
           "That is preparation without voice load.",
           "It leaves me fresh for recording."),
         d("I can send hosts time-coded notes instead of talking through every transition.",
           "Would that replace a table read?",
           "Yes, the host can mark changes independently."),
         d("On 6 April, I prepared the science-series pilot with time-coded notes, then chaired one 45-minute table read.",
           "How did your launch recording go?",
           "My narration was clean at the 09:00 session the next morning."),
         d("You sometimes join a long dinner conversation.",
           "I do, but I do not narrate continuously or work in a dry booth afterward.",
           "Social talk does not test the same thing."),
         d("On 16 June, I hosted two evening table reads and a pickup session before a 09:00 sponsor recording.",
           "What was the consequence?",
           "I lost the upper range on the sponsor copy and we postponed the session."),
         d("I am recovering from a sinus infection, and the audiologist asked me to avoid extended talking while congestion clears.",
           "Can you still prepare the episode?",
           "Yes, through edits and time-coded notes."),
         d("A host says both table reads would make me look fully committed to the new series.",
           "Does that alter the sponsor's booked recording?",
           "No, the sponsor and studio are fixed for Friday morning."),
         d("If the sponsor recording moved to Wednesday, what would happen?",
           "The Thursday voice load would no longer threaten it.",
           "That would be a different decision."),
         "Should I schedule two Thursday evening table reads before the sponsor recording Friday at 09:00?",
         "No. The two live table reads are a poor fit before this fixed recording.",
         "reject the live reads; provide time-coded notes and one short check-in",
         "The user has a successful low-voice preparation pattern, and prior stacked evening speaking before a sponsor recording caused a concrete loss of vocal range.",
         "The user can edit all afternoon and converse socially.",
         "Neither requires sustained narration in the immediate lead-up to a studio recording.",
         "Commitment optics do not restore the voice needed for the booked sponsor session.",
         ("6 April pilot preparation", "prepare science-series narration", "used notes plus one short table read", "recorded clean narration at 09:00"),
         ("16 June double table read", "prepare sponsor copy", "hosted two reads and a pickup", "postponed the recording")),

    spec("U06", "aviation safety instructor", "sf", "reject",
         ("simulator script", "flight roster", "training center", "checkride weeks"),
         d("I can conduct a ten-minute preflight briefing clearly.",
           "That is bounded and uses normal speaking volume.",
           "It is not simulator coaching for hours."),
         d("I prepare scenarios by annotating the simulator script with the pilot's weak points.",
           "Can the candidate study that before the run?",
           "Yes, it lets us reserve speech for decisions that need discussion."),
         d("On 11 February, I used an annotated script for one afternoon simulator rehearsal before a 08:15 checkride.",
           "How was your instruction at the checkride?",
           "Direct and audible; I had not spent the evening coaching."),
         d("You gave a conference talk last year without trouble.",
           "That was midmorning, with amplification, and no dawn checkride after it.",
           "The schedule made it easier."),
         d("On 5 May, a delayed simulator session kept me coaching emergency calls until 21:15 before a 07:30 checkride.",
           "What did you notice the next morning?",
           "My instructions became hoarse during the engine-failure sequence, and a colleague took the radio prompts."),
         d("My sleep has been interrupted by tinnitus recently, so I recover less well from late headset work.",
           "Does that make written scenario preparation useful?",
           "Yes, it keeps the evening quiet."),
         d("The chief pilot says the extra evening session would show the airline how available I am.",
           "Does availability move the checkride?",
           "No, the candidate and examiner are confirmed for Friday."),
         d("If Friday's checkride were scheduled after lunch instead, would you decide differently?",
           "I would have a substantial recovery window.",
           "The early fixed demand is material here."),
         "Is it sensible for me to cover the delayed Thursday simulator session before Friday's 07:30 checkride?",
         "No. Covering the delayed evening simulator session is a poor fit before the early checkride.",
         "reject the late session; hand off coaching with the annotated script",
         "A single prepared rehearsal has supported the user's checkride instruction, while late sustained headset coaching before an early checkride has made their voice unreliable.",
         "The user handles short preflight briefings and amplified conference talks.",
         "Neither involves hours of headset coaching followed by a dawn practical examination.",
         "Airline visibility does not reduce the late voice load or change the confirmed checkride.",
         ("11 February simulator rehearsal", "prepare candidate decisions", "annotated the script before one live run", "gave clear checkride instruction"),
         ("5 May delayed simulator", "coach emergency calls", "spoke over headsets until 21:15", "colleague covered radio prompts")),

    spec("U07", "public defender training attorney", "rr", "reject",
         ("argument outline", "court calendar", "advocacy room", "trial-prep weeks"),
         d("I can answer a judge's procedural question in a brief hearing.",
           "That is not a full mock argument.",
           "No, it does not require sustained projection or repetition."),
         d("I prepare trainees with a written objection map and recorded examples.",
           "Can they use those before a live practice?",
           "Yes, live time can focus on the few contested exchanges."),
         d("On 20 September, I held one mock-argument session after trainees worked through the objection map.",
           "What happened at the next morning's suppression hearing?",
           "I argued clearly through the final witness because the rehearsal was limited."),
         d("You once taught a three-hour seminar successfully.",
           "It was an afternoon session with a microphone and no court appearance the following morning.",
           "It did not create the same demand."),
         d("On 2 November, I ran two consecutive evening mock arguments before a 09:00 evidentiary hearing.",
           "How did the hearing go?",
           "I strained through the opening examination and co-counsel took the redirect."),
         d("I have vocal fatigue from post-viral laryngitis and am following a speech pathologist's pacing plan.",
           "Does the plan allow preparation?",
           "Yes, written examples and a short targeted round are fine."),
         d("The training director says two mock arguments will make the office look formidable to the visiting foundation.",
           "Does that help with the court calendar?",
           "No, the hearing time is set by the court."),
         d("If the hearing were continued for a week, would your ranking change?",
           "Yes, then the two formats would not compete for the same recovery.",
           "Right now the hearing must rank first."),
         "For Thursday, should I rank two full mock arguments above a single targeted practice before Friday's 09:00 evidentiary hearing?",
         "No. Rank the single targeted practice above two full mock arguments.",
         "put the written-map session and one targeted round first",
         "The user's limited, written-supported practice has preserved advocacy clarity, while stacked mock arguments before a fixed hearing have not.",
         "The user can handle brief hearings and has taught amplified seminars.",
         "Neither evidence source recreates repeated live argument directly before court.",
         "Foundation impressions do not change the court's fixed demand or the user's recovery plan.",
         ("20 September mock argument", "prepare trainee objections", "used an objection map before one practice", "argued clearly at the hearing"),
         ("2 November double mock", "prepare evidentiary hearing", "ran two consecutive arguments", "co-counsel took redirect")),

    spec("U08", "software developer advocate", "rr", "reject",
         ("demo repository", "launch calendar", "developer studio", "release weeks"),
         d("I can record a concise feature update for a community channel.",
           "That is a single take with breaks.",
           "It is not four hours of live troubleshooting."),
         d("I prepare demos with a runnable repository and annotated command notes.",
           "Can attendees test those without another rehearsal?",
           "Yes, they can leave comments on the walkthrough."),
         d("On 8 August, I used the annotated commands to run one product-demo rehearsal before a Friday livestream.",
           "How did the livestream sound?",
           "My explanations stayed crisp, even through the debugging section."),
         d("You hosted a panel last month.",
           "I shared the speaking time and it was not before a release-day livestream.",
           "That made the load lower."),
         d("On 17 October, I joined two late troubleshooting rehearsals before an 08:00 release livestream.",
           "What happened on stream?",
           "My voice gave out during the API migration explanation, so the engineer finished it."),
         d("I have been managing acid reflux with an earlier bedtime and reduced late speaking; it flares after long evening sessions.",
           "Can the repository carry some preparation work?",
           "Yes, that is why I maintain it carefully."),
         d("The product VP says both rehearsals would make the livestream feel more polished to analysts.",
           "Does polish change the release time?",
           "No, the release and livestream begin at 08:00."),
         d("If the livestream moved to Monday afternoon, would you rank the options differently?",
           "I would have recovery time after Thursday.",
           "The current early launch is the key constraint."),
         "How should I rank an annotated-repository review against two Thursday night troubleshooting rehearsals before the Friday 08:00 livestream?",
         "Rank the annotated-repository review above the two live troubleshooting rehearsals.",
         "choose async repository review and one short question session",
         "The user's prepared demo method has delivered clear livestreams, whereas duplicated late troubleshooting sessions before a fixed launch have exhausted their voice.",
         "The user can record short updates and share a panel.",
         "Neither is comparable to repeated troubleshooting explanation before a release livestream.",
         "Analyst polish is unrelated to the recovery needed for the launch.",
         ("8 August demo rehearsal", "prepare migration walkthrough", "used annotated commands for one run", "explained debugging clearly on stream"),
         ("17 October double troubleshooting", "prepare release livestream", "spoke through two late debugging sessions", "engineer finished the explanation")),

    spec("U09", "medical interpreter coordinator", "rr", "conditional",
         ("terminology list", "clinic roster", "interpretation hub", "specialty clinics"),
         d("I can interpret a short follow-up call without vocal fatigue.",
           "That is a bounded exchange.",
           "It does not require continuous teaching voice."),
         d("I prepare trainees with a bilingual terminology list and silent video captions.",
           "Can the group review those before practice?",
           "Yes, then the live session can be much shorter."),
         d("On 15 January, I led one 50-minute rehearsal after trainees reviewed the terminology list for the cardiology clinic.",
           "How did Friday's transplant-family consultation go?",
           "My interpretation remained steady through the full appointment."),
         d("You volunteered at a community forum all afternoon.",
           "I rotated with other interpreters and did not have a high-stakes clinic booked next morning.",
           "It was not continuous solo speech."),
         d("On 27 February, I repeated a pediatric role-play three times before a 08:00 transplant consultation.",
           "What happened in clinic?",
           "My voice was too weak for long family questions, so the backup interpreter stepped in."),
         d("I am recovering from a vocal-cord inflammation, and the ENT has asked for longer quiet intervals between sustained sessions.",
           "Is an asynchronous review viable?",
           "Yes, the captioned video and terminology list are ready."),
         d("The hospital relations team says a full rehearsal will demonstrate our program's rigor.",
           "Does rigor move the transplant consultation?",
           "No, the family and physician are confirmed for Friday morning."),
         d("If the transplant consultation were rescheduled to next Tuesday, what would you recommend?",
           "I could permit a longer rehearsal after checking my recovery.",
           "With Friday fixed, I need the shorter format."),
         "Should I rank a full Thursday role-play above a terminology-list review and one short practice before Friday's transplant consultation?",
         "Rank the shorter, terminology-led practice first; allow a full role-play only if the Friday consultation moves.",
         "conditional on moving the consultation or adding a backup interpreter",
         "The user's clarity has held after one prepared practice but failed after repeated role-play immediately before a fixed transplant consultation.",
         "The user handles short follow-up calls and rotated community work.",
         "Neither entails sustained solo interpretation before the booked consultation.",
         "Program-rigor messaging does not alter the medical recovery requirement.",
         ("15 January cardiology rehearsal", "prepare trainee terminology", "used captions and one 50-minute practice", "interpreted steadily at transplant clinic"),
         ("27 February repeated role-play", "prepare pediatric scenarios", "repeated the role-play three times", "backup interpreter took long questions")),

    spec("U10", "city council communications officer", "rr", "conditional",
         ("briefing book", "council calendar", "press office", "budget sessions"),
         d("I can deliver a two-minute press update without strain.",
           "That is brief and scripted.",
           "It does not use the same voice as moderating a rehearsal."),
         d("I prepare spokespeople with a written Q-and-A grid and recorded sample answers.",
           "Can they rehearse from those alone first?",
           "Yes, they can flag only the answers that need live work."),
         d("On 4 March, I held one 60-minute budget-message rehearsal after the team annotated the Q-and-A grid.",
           "How did you do at the next morning's council press conference?",
           "I spoke clearly through the entire question period."),
         d("You gave a long welcome at the volunteer awards night.",
           "That was amplified, and there was no 08:30 council conference the next day.",
           "It was not an equivalent demand."),
         d("On 21 April, I moderated two evening rehearsal panels before the 08:30 transit-budget press conference.",
           "What went wrong?",
           "My voice became thin during the opening statement and the deputy read the final responses."),
         d("I have a recurring migraine pattern after late screen-and-speech sessions, and my physician has emphasized sleep regularity during recovery.",
           "Could the Q-and-A grid reduce the late work?",
           "Yes, it lets us reserve a brief live check for the difficult questions."),
         d("The chief of staff says the two-panel rehearsal would impress council members who attend.",
           "Does that change tomorrow's press conference?",
           "No, reporters are already confirmed for 08:30."),
         d("If the press conference changed to Friday afternoon, how would you rank the rehearsal options?",
           "A second panel could become viable with time to recover.",
           "I would still prefer the written-first preparation."),
         "Before Friday's 08:30 transit-budget press conference, should I rank two Thursday evening rehearsal panels above the written Q-and-A review and one live check?",
         "Rank the written Q-and-A review and one live check first; add a second panel only if the press conference is moved.",
         "conditional on a later press time or another moderator covering the second panel",
         "One written-led rehearsal has supported this user's press delivery, while two evening panels before a fixed morning conference have reduced their clarity.",
         "The user can give short scripted updates and has made amplified welcomes.",
         "Neither involves repeated evening moderation before a council press conference.",
         "Council-member visibility does not change the fixed media demand or the user's recovery need.",
         ("4 March budget rehearsal", "prepare council messages", "annotated Q-and-A before one live check", "spoke clearly at press conference"),
         ("21 April double panel", "prepare transit-budget responses", "moderated two evening panels", "deputy finished responses")),
]
