from generate_s1_s5_review_batch import d, spec


S14 = [
    spec("U01", "grant compliance director", "pr", "accept",
         ("grant closeout narrative", "visitor-dense hot-desk zone", "Thursday sponsor portal", "reserved archive room"),
         d("I completed the wildfire grant closeout narrative in the archive room last spring after turning off chat notifications.",
           "What helped most?",
           "No one interrupted the evidence trail while I reconciled it."),
         d("I can answer quick sponsor questions from the shared desk without losing my place.",
           "So the shared desk is useful sometimes?",
           "Yes, for short exchanges rather than long synthesis."),
         d("For the coastal resilience closeout, I booked the archive room before drafting and finished the narrative cleanly before submission.",
           "Did the booking change the work?",
           "It gave me a protected stretch to connect every expenditure to the outcome."),
         d("The room is free from 09:00 to 13:00 on Thursday, before the sponsor portal closes at 16:00.",
           "Is that enough time to draft there?",
           "Yes, if I use the hot desk only for the afternoon questions."),
         d("On the flood-mitigation closeout, visitor questions at the shared desk broke my reconciliation twice and I submitted the narrative after the internal cutoff.",
           "What was different from the archive-room draft?",
           "I had to leave the expenditure trail each time someone needed an answer."),
         d("My program officer has already approved a four-hour morning drafting block before the portal check-in.",
           "Does that make the schedule workable?",
           "Yes, the questions can wait until the narrative is complete."),
         d("The facilities coordinator says the new hot-desk zone is closer to the coffee bar.",
           "Does that affect the narrative?",
           "No, it says nothing about tracing the grant evidence."),
         d("The archive room's ventilation work was postponed, so its Thursday reservation remains available.",
           "Does that preserve your plan?",
           "Yes, the quiet drafting block is still real."),
         "Facilities asks whether I can join the visitor-dense hot-desk rotation Thursday while my grant closeout narrative is due. How will I react?",
         "The user will accept the rotation if the morning archive-room drafting reservation is retained.",
         "accept with a protected morning quiet block",
         "The user has succeeded on a comparable narrative when a quiet room and muted messages protected the evidence work, and the room is available before the deadline.",
         "The user can handle short sponsor questions from the shared desk.",
         "Short questions do not test sustained reconciliation of a closeout narrative.",
         "Coffee-bar proximity does not establish a suitable drafting condition.",
         ("coastal resilience closeout", "connect expenditures to outcomes", "booked archive room", "finished a coherent narrative"),
         ("Thursday hot-desk rotation", "draft closeout narrative", "visitor interruptions", "evidence trail repeatedly broken")),

    spec("U02", "museum collections registrar", "pr", "accept",
         ("provenance correction report", "lobby-facing hot desks", "Monday repatriation review", "reading-room carrel"),
         d("I prepared the provenance correction for the Bemba mask in a reading-room carrel and sent it without a citation error.",
           "Why did that setting work?",
           "I could compare the accession ledgers without being pulled into visitor requests."),
         d("I greet researchers at the lobby desk comfortably during their scheduled appointments.",
           "Does public-facing work suit you?",
           "It does when I am not reconstructing a chain of ownership."),
         d("Last month I used a carrel to rebuild a donor file from three ledgers and the review panel accepted the report on first read.",
           "Was the report ready on time?",
           "Yes, because the source comparisons stayed uninterrupted."),
         d("A carrel is open from 08:30 until the 11:30 repatriation review, and the lobby shift begins at noon.",
           "Can both commitments fit?",
           "Yes, the drafting can be complete before I take the desk."),
         d("At the lobby desk during the Maroon collection review, two visitor requests pulled me away from a ledger comparison and I carried an unchecked accession number into the draft.",
           "Was the error caught?",
           "Yes, but only during the final review."),
         d("The panel chair has confirmed that no new collection material will arrive before the 11:30 review.",
           "Does that limit last-minute research?",
           "Yes, the carrel session can be used to finish the existing record."),
         d("The visitor services lead says the lobby desk offers more chances to meet curators.",
           "Is that relevant to source verification?",
           "No, visibility is not a substitute for checking ledgers."),
         d("The reading room will remain open Monday despite the exhibit installation.",
           "Does that change your answer?",
           "It confirms the quiet option is available."),
         "The visitor-services lead asks whether I can take the lobby-facing hot desk Monday while the provenance correction report goes to review. How will I react?",
         "The user will accept if the reading-room carrel is reserved for the pre-review drafting period.",
         "accept after securing the carrel",
         "Comparable source reconstruction succeeded in a quiet carrel, and the available morning slot ends before the public-facing shift begins.",
         "The user handles researcher appointments at the lobby desk.",
         "Appointments are bounded interactions, unlike tracing provenance across records.",
         "Meeting curators does not show that lobby interruptions support accurate provenance work.",
         ("donor-file reconstruction", "compare ledger entries", "reading-room carrel", "report accepted on first read"),
         ("lobby hot-desk shift", "reconstruct ownership chain", "visitor questions", "citation mismatch in the report")),

    spec("U03", "labor relations adviser", "be", "reject",
         ("bargaining brief", "union-floor hot desks", "Tuesday mediation", "union conference room"),
         d("I drafted a wage proposal in the union conference room after reviewing the bargaining history alone.",
           "What made the proposal usable?",
           "I could hold the trade-offs in view through the final paragraph."),
         d("I answer routine contract-status messages from the union floor without difficulty.",
           "So the floor is not always a problem?",
           "No, it works for messages that do not require a negotiating position."),
         d("During last year's grievance preparation, I tried to write the bargaining brief at a hot desk while stewards kept asking for updates.",
           "What happened to the brief?",
           "I contradicted the seniority concession and had to rebuild the argument that night."),
         d("The union conference room is occupied all Tuesday, while mediation starts at 15:00.",
           "Do you have another quiet room?",
           "Not in the building before the session."),
         d("During a contract-renewal week, I drafted at the union-floor desk between steward questions and reversed two linked wage positions in the same brief.",
           "How did you discover it?",
           "The lead negotiator spotted the conflict just before the meeting."),
         d("The mediation chair has asked for the final brief by 13:30 so both sides can read it before the 15:00 session.",
           "Can the drafting be repaired later?",
           "No, the review window closes before mediation begins."),
         d("A colleague says sitting on the floor would signal solidarity before mediation.",
           "Does that solve the drafting issue?",
           "No, solidarity does not prevent a concession from being misstated."),
         d("The conference room booking was released for Tuesday morning after all.",
           "Would that alter the concern?",
           "Yes, a protected morning would remove the specific obstacle."),
         "Why should I decline the union-floor hot desk on Tuesday when the bargaining brief must be ready for mediation?",
         "The user should decline the hot desk unless a quiet drafting room is secured.",
         "reject without a protected alternative",
         "A prior person-owned hot-desk episode produced a specific bargaining contradiction under updates, while the needed quiet option is unavailable before mediation.",
         "The user can manage routine contract-status messages on the union floor.",
         "Routine messages do not require preserving a multi-part negotiating argument.",
         "Solidarity signaling does not bear on whether the brief remains internally consistent.",
         ("wage proposal", "weigh bargaining trade-offs", "union conference room", "usable final position"),
         ("grievance brief", "state seniority concession", "steward interruptions", "contradiction and overnight rewrite")),

    spec("U04", "clinical trials writer", "be", "reject",
         ("protocol deviation narrative", "clinical operations hot desks", "Friday safety review", "library workstation"),
         d("I assembled a deviation narrative at the medical library workstation with the source reports open side by side.",
           "What did that allow?",
           "I could distinguish the investigator account from the monitoring record."),
         d("I can update the enrollment tracker from the clinical operations desks.",
           "Are those desks workable for all trial tasks?",
           "They are fine for entering completed facts."),
         d("When I drafted the cardiac-study deviation narrative at a hot desk, Teams calls and monitor questions caused me to merge two dates.",
           "What was the result?",
           "The safety physician returned it because the chronology was unreliable."),
         d("The library workstation is closed for inventory through Friday, and the safety review begins at 10:00.",
           "Could you draft there beforehand?",
           "No, it is unavailable during the only preparation window."),
         d("For the oncology protocol, monitor calls at the clinical desk split my attention while I compared visit dates, and I transposed the investigator and monitoring timelines.",
           "What did that require?",
           "A full chronology check after the safety meeting was delayed."),
         d("The safety physician has set Thursday evening as the last time to circulate the narrative for clinical review.",
           "Can you wait until Friday to correct it?",
           "No, the reviewers need the draft beforehand."),
         d("The operations manager says the hot desks make it easier to hear recruitment news.",
           "Does that help the narrative?",
           "No, recruitment news is unrelated to a defensible chronology."),
         d("Inventory was rescheduled and the library workstation will reopen Thursday afternoon.",
           "Would that matter?",
           "Yes, it would provide the comparison space before review."),
         "Why is the clinical operations hot-desk assignment a poor choice before Friday's safety review?",
         "The user should reject it while the library workstation is unavailable.",
         "reject the assignment as currently arranged",
         "The user's own hot-desk draft produced a chronology error under live interruptions, and the normal quiet comparison workspace is unavailable before the review.",
         "The user completes enrollment-tracker entries from the clinical operations desks.",
         "Entering completed facts does not require reconciling competing clinical accounts.",
         "Recruitment visibility does not improve the accuracy of a protocol-deviation narrative.",
         ("deviation narrative", "compare source reports", "library workstation", "accounts kept distinct"),
         ("cardiac-study narrative", "establish chronology", "Teams calls and monitor questions", "merged dates and returned draft")),

    spec("U05", "urban planning analyst", "be", "reject",
         ("zoning impact assessment", "permit-counter hot desks", "Wednesday council packet", "municipal records alcove"),
         d("I wrote the riverfront zoning assessment in the records alcove after mapping every parcel comment to the ordinance.",
           "How did the setting affect it?",
           "The uninterrupted map check kept the recommendation consistent."),
         d("I can explain permit steps to residents from the public counter.",
           "Does that counter work for your day-to-day service?",
           "Yes, for a single question at a time."),
         d("I once revised a density assessment at the permit counter while applicants queued beside me.",
           "What went wrong?",
           "I omitted the school-capacity condition and the packet had to be withdrawn."),
         d("The records alcove is reserved for scanning all Wednesday, and the council packet locks at 14:00.",
           "Can the assessment move elsewhere quietly?",
           "No other room has the parcel map archive."),
         d("At the permit counter during the transit-overlay revision, I answered walk-up questions between map checks and left a flood-zone parcel out of the impact table.",
           "What followed?",
           "The planning manager sent the table back for a complete rebuild."),
         d("The city clerk requires the packet in the publishing queue by 13:00, an hour before the council lock.",
           "Is there time for a later rewrite?",
           "No, a missing condition would carry into the public packet."),
         d("The department head says the public counter would demonstrate responsiveness.",
           "Does responsiveness answer the packet risk?",
           "No, the council needs a complete analysis."),
         d("The scanner booking was moved to Tuesday, restoring the records alcove on Wednesday morning.",
           "Would that affect your decision?",
           "Yes, the assessment could then be completed with the maps."),
         "Why should I turn down the permit-counter hot desk before the zoning impact assessment goes into Wednesday's council packet?",
         "The user should reject it because the required records alcove is unavailable before the packet locks.",
         "reject until the records alcove is available",
         "A prior counter-based draft omitted a material condition, and the assessment needs the unavailable quiet alcove and map archive before a fixed packet deadline.",
         "The user handles individual resident permit questions at the counter.",
         "Individual service questions are not equivalent to integrating parcel evidence into a council assessment.",
         "Public responsiveness does not show that interruptions preserve a complete zoning analysis.",
         ("riverfront assessment", "map parcel comments to ordinance", "records alcove", "consistent recommendation"),
         ("density assessment", "include all conditions", "queued applicants", "omitted condition and withdrawn packet")),

    spec("U06", "information security counsel", "be", "reject",
         ("regulator notification draft", "security pod hot desks", "48-hour notice deadline", "soundproof legal room"),
         d("I prepared the ransomware notification in the soundproof legal room after separating confirmed access from working hypotheses.",
           "Why was that separation reliable?",
           "No one pressed me to answer incident questions while I checked each qualifier."),
         d("I can take a quick incident-status call from the security pod.",
           "Is the pod unusable?",
           "No, it is good for live coordination."),
         d("At the security pod during a vendor breach, Slack escalations and walk-ups led me to state an unverified access route in a draft.",
           "How was that caught?",
           "Outside counsel removed it before it went to the regulator."),
         d("The soundproof legal room is being rewired through the 48-hour notification deadline.",
           "Can you reserve a comparable room?",
           "Every other legal room is assigned to depositions."),
         d("While writing the cloud-access notification at the security pod, I paused repeatedly for escalation questions and described a suspected credential path as confirmed.",
           "What prevented filing it?",
           "Outside counsel caught the unsupported wording in the final pass."),
         d("The incident response lead must approve the regulator notice two hours before the statutory filing window.",
           "Can the language wait for a quiet room afterward?",
           "No, approval has to happen while the rewiring is still underway."),
         d("The chief security officer says working in the pod would keep me close to the response team.",
           "Does proximity change the drafting standard?",
           "No, the notice still must separate fact from hypothesis."),
         d("The rewiring contractor offered an early completion slot tomorrow morning.",
           "Would that change the situation?",
           "Yes, a reopened legal room before filing would be enough."),
         "Why should I refuse the security-pod hot desk while writing the regulator notification?",
         "The user should reject it until a quiet legal drafting space is available.",
         "reject pending a suitable quiet room",
         "The user's prior pod-based draft included an unverified claim under incident interruptions, and no comparable quiet room is presently available before filing.",
         "The user can coordinate live incident calls from the security pod.",
         "Live coordination does not test careful qualification in a regulatory notice.",
         "Response-team proximity does not validate an unverified statement.",
         ("ransomware notification", "separate facts from hypotheses", "soundproof legal room", "careful qualified filing"),
         ("vendor-breach draft", "describe access route", "Slack escalations and walk-ups", "unverified claim removed")),

    spec("U07", "public defender supervisor", "be", "conditional",
         ("sentencing memorandum", "courthouse hot desks", "Thursday morning hearing", "library consultation room"),
         d("I completed a sentencing memorandum in the library consultation room after reading the mitigation records in sequence.",
           "What did that protect?",
           "It kept the family history connected to the requested sentence."),
         d("I can return client calls from the courthouse hot desks between appearances.",
           "Do those calls go well?",
           "Yes, when each call has one immediate purpose."),
         d("I tried to draft a mitigation memorandum at a courthouse hot desk while lawyers and clients asked for help.",
           "What happened?",
           "I lost the treatment chronology and filed an incomplete first version."),
         d("The library consultation room is available from 07:00 to 09:30, but the hot-desk rotation begins at 09:00.",
           "Could both be managed?",
           "Only if the last half hour of the rotation is covered by another supervisor."),
         d("At a courthouse hot desk before an earlier sentencing hearing, urgent questions from two attorneys made me skip a treatment letter and the memorandum lacked its key timeline.",
           "Did the judge receive the complete context?",
           "No, I had to supplement the record afterward."),
         d("The client meeting ends at 09:30, leaving no later gap before the hearing calendar opens.",
           "Can you finish the memorandum after the rotation starts?",
           "No, the final review must be done before I meet the client."),
         d("The chief judge says being visible at the hot desks would reassure the calendar staff.",
           "Does that settle the memorandum issue?",
           "No, the hearing needs the complete mitigation record."),
         d("A supervisor has offered to cover the 09:00 to 09:30 desk interval.",
           "Would that change your answer?",
           "Yes, then I can finish the memorandum before joining the desk."),
         "Why would I agree to the courthouse hot-desk rotation only with coverage during my sentencing-memorandum block?",
         "The user should agree only if the early library block and its final half hour are protected.",
         "conditional on coverage for the drafting overlap",
         "The user's own interrupted hot-desk draft lost a material chronology, while a quiet alternative exists only if the overlapping desk obligation is covered.",
         "The user can make focused client calls from the courthouse hot desks.",
         "Focused calls do not require building a complete mitigation narrative from multiple records.",
         "Calendar-staff reassurance does not establish that the memorandum will be complete.",
         ("sentencing memorandum", "connect mitigation records", "library consultation room", "complete argument for hearing"),
         ("mitigation memorandum", "preserve treatment chronology", "courthouse interruptions", "incomplete first filing")),

    spec("U08", "product accessibility lead", "be", "conditional",
         ("screen-reader remediation brief", "engineering hot desks", "Tuesday release review", "accessibility lab"),
         d("I prepared the keyboard-navigation remediation brief in the accessibility lab while replaying the screen-reader recordings.",
           "What did the lab provide?",
           "I could trace each failure from the recording to a specific component."),
         d("I can answer design questions from the engineering hot desks during stand-up.",
           "Are those questions manageable?",
           "Yes, when I am addressing one interface decision."),
         d("At an engineering hot desk, notification banners and pair-programming requests interrupted a remediation brief.",
           "What was the consequence?",
           "I matched two defects to the wrong components and delayed the fix."),
         d("The accessibility lab has a test device available after 13:00, but the release review is at 15:00 and the hot-desk shift starts at 14:00.",
           "Is there a workable arrangement?",
           "Yes, if the shift begins after I finish the device review."),
         d("During the last mobile release, a stream of hot-desk requests interrupted my replay of the screen-reader sessions and I linked two focus failures to the wrong controls.",
           "How was that resolved?",
           "The engineering team lost a day retesting the components."),
         d("The release manager needs the tested brief in the review folder by 14:45, before the 15:00 meeting.",
           "Can the test session be shortened?",
           "No, each recording has to be replayed on the reserved device."),
         d("The engineering manager says the hot-desk shift would make me easier to consult.",
           "Does that prove the brief can be drafted there?",
           "No, consultability and defect tracing are different work."),
         d("The device reservation was extended through 14:30.",
           "Does that affect the condition?",
           "Yes, I need the shift delayed until the lab work is done."),
         "Why should my engineering hot-desk shift depend on finishing the accessibility-lab review first?",
         "The user should accept the shift only after the lab-based remediation work is complete.",
         "conditional on delaying the hot-desk start",
         "A prior interrupted hot-desk brief misassigned defects, while the needed test-device session is available only if the overlapping shift is delayed.",
         "The user can resolve single design questions from the engineering hot desks.",
         "Single questions do not require tracing multiple recorded failures to their components.",
         "Being easy to consult does not ensure accurate screen-reader remediation analysis.",
         ("keyboard remediation brief", "trace failures to components", "accessibility lab recordings", "specific reliable fixes"),
         ("hot-desk remediation brief", "assign defects to components", "banners and pair-programming requests", "misassigned defects and delay")),

    spec("U09", "forensic accountant", "be", "non_decision",
         ("asset-tracing report", "open investigations hot desks", "Friday injunction filing", "secure document room"),
         d("I finished an asset-tracing report in the secure document room after following the transfers without interruption.",
           "Was that room necessary?",
           "It helped, but the bank records were already indexed and unusually clear."),
         d("I regularly review straightforward invoice batches at the investigations hot desks.",
           "Do interruptions affect those reviews?",
           "Not much when the documents are already categorized."),
         d("While drafting a prior asset-tracing report at the open hot desks, I missed a transfer between two related accounts.",
           "Why did you miss it?",
           "The queue changed twice, although the bank export also arrived with duplicate lines."),
         d("The secure document room is unavailable until Friday afternoon, after the injunction filing time.",
           "Is there a comparable quiet option?",
           "A finance archive room may open, but access approval is still pending."),
         d("In the earlier related-account review, the hot-desk queue changed twice while I traced transfers, but the bank export also contained duplicated transaction rows.",
           "Can you identify which factor caused the miss?",
           "No, either distraction or the flawed export could explain it."),
         d("The litigation partner has allowed a corrected tracing schedule if the finance archive room is approved by Thursday noon.",
           "Does that create a definite quiet plan?",
           "Not until facilities grants the access approval."),
         d("The investigations partner says the hot desks would help the team see how busy the matter is.",
           "Does that identify the cause of the earlier miss?",
           "No, visibility does not separate interruption from the duplicate export."),
         d("The bank has confirmed the duplicate lines in the earlier export and will send a corrected file this morning.",
           "Does that resolve the prior episode's explanation?",
           "It makes the old miss less clear as evidence about the desks alone."),
         "Why can't I yet say whether the open investigations hot desk is suitable for Friday's asset-tracing report?",
         "There is not enough evidence to decide until the alternate-room approval and current records are confirmed.",
         "withhold a decision pending the remaining facts",
         "The earlier error had both interruptions and duplicate bank lines, so it does not isolate the hot-desk effect; the possible quiet alternative is also unresolved.",
         "The user reviews categorized invoice batches successfully at the hot desks.",
         "Categorized invoices do not establish performance on an asset-tracing report.",
         "Team visibility does not explain the missed transfer.",
         ("indexed asset-tracing report", "follow transfers", "secure document room", "complete trace"),
         ("prior asset-tracing report", "identify related-account transfer", "interruptions and duplicate export", "miss with ambiguous cause")),

    spec("U10", "policy research editor", "be", "non_decision",
         ("education funding brief", "newsroom hot desks", "Monday cabinet meeting", "university reading room"),
         d("I edited the school-funding brief in the university reading room after comparing the model assumptions with the tables.",
           "Did the quiet room explain the result?",
           "Possibly, though the author had also delivered a much cleaner draft than usual."),
         d("I edit short press responses at the newsroom hot desks without trouble.",
           "Why are those manageable?",
           "They are brief and the sources have already been checked."),
         d("When I revised an earlier funding brief at the newsroom hot desks, I left out a regional adjustment.",
           "Was the interruption the reason?",
           "It may have contributed, but the spreadsheet's adjustment tab was hidden in the handoff."),
         d("The university reading room is closed Sunday, and a private desk at the legislative library may be available if security approves weekend access.",
           "Do you know whether it will be approved?",
           "Not yet, and Monday's cabinet meeting is early."),
         d("For the earlier funding brief, I worked through breaking-news interruptions at the newsroom desk, but the workbook handed to me also hid the regional-adjustment tab.",
           "Can you tell why the adjustment was omitted?",
           "No, the interruption and the hidden source both remain plausible explanations."),
         d("The cabinet secretary will accept a revised briefing time if the legislative-library access request clears before Saturday evening.",
           "Does that confirm a quiet drafting option?",
           "No, security has not yet answered the request."),
         d("The editor-in-chief says the newsroom desk would keep the brief close to breaking coverage.",
           "Does that determine whether the analysis will be sound?",
           "No, it does not explain the hidden adjustment tab."),
         d("The data team has restored the missing adjustment tab and labeled it in the new workbook.",
           "Does that change how you read the earlier mistake?",
           "Yes, it weakens the claim that the hot desks alone caused it."),
         "Why should I withhold a recommendation on the newsroom hot-desk assignment for the education funding brief?",
         "The user should defer the decision until weekend library access and the current workbook review are confirmed.",
         "defer pending access and document verification",
         "The prior omission cannot be attributed to interruptions alone because the key tab was hidden, and the availability of a quiet alternative remains unknown.",
         "The user edits short, source-checked press responses successfully at the newsroom hot desks.",
         "Short responses do not test reconciliation of a funding model and its tables.",
         "Proximity to breaking coverage does not establish the cause of the prior analytical omission.",
         ("school-funding brief", "compare assumptions and tables", "university reading room", "sound edited analysis"),
         ("earlier funding brief", "include regional adjustment", "hot-desk interruptions and hidden tab", "omission with ambiguous cause")),
]
