"""Hand-authored S11 profiles for the vNext offsite batch."""

from generate_s1_s5_review_batch import d, spec


S11 = [
    spec("U01", "release operations lead", "pg", "accept",
         ("handover board", "on-call calendar", "release room", "pager rotations"),
         d("I can spend an ordinary afternoon reviewing release notes without feeling depleted.", "So routine desk work is sustainable?", "Yes, when it follows a normal night's sleep."),
         d("I enjoyed a short team lunch after last month's daytime deployment.", "Did the social part tire you?", "No, because I could leave after an hour."),
         d("After Tuesday's overnight pager rotation, I closed the handover board at 10:45 and slept until noon.", "How did the afternoon feel?", "I could handle essentials, but I had no reserve for a long group event."),
         d("The new pager tone has kept waking me for three weeks, even on quieter nights.", "Has that changed your recovery?", "I stay foggier after call than I used to."),
         d("My shoulder physiotherapy is booked for Thursday at 17:30, and the clinic has no other appointment this week.", "Can you reschedule it?", "No, missing it would interrupt the treatment plan."),
         d("I avoid coffee after two because it brings back the palpitations I had during the spring release.", "Can caffeine extend your afternoon?", "No, I protect sleep instead."),
         d("The director says the Thursday offsite is where release leads become visible to senior staff.", "Does that make you want to attend?", "It does, but visibility does not create capacity."),
         d("The physiotherapist can offer a Friday morning video check-in without delaying treatment.", "Would that change Thursday?", "Yes, the calendar conflict would no longer be fixed."),
         "The team wants my answer today for a Thursday 14:00–16:30 offsite after my pager rotation. What should I say?",
         "Ask for a shorter, remote, or rescheduled offsite option before confirming.",
         "request an accommodated attendance option",
         "Post-rotation recovery, unsettled sleep, a fixed treatment appointment, and the caffeine boundary make the proposed afternoon unsuitable without an accommodation.",
         "The user manages ordinary desk work and a brief optional lunch after normal daytime work.",
         "Neither event follows an overnight pager rotation or competes with scarce treatment.",
         "Leadership visibility concerns reputation, not the user's recovery or calendar constraints.",
         ("overnight pager rotation", "complete the release handover", "closed the handover board at 10:45", "needed the afternoon to recover"),
         ("shoulder physiotherapy", "continue treatment", "kept the only Thursday appointment", "avoided interrupting the care plan")),

    spec("U02", "clinical scheduling coordinator", "pg", "accept",
         ("waitlist ledger", "clinic diary", "scheduling pod", "triage weeks"),
         d("I can join a staff breakfast after a regular shift and still work a full day.", "Are normal team events difficult?", "No, not when I have slept normally."),
         d("I attended a ninety-minute planning meeting last Friday with no trouble.", "What was different about that day?", "I had not been awake managing urgent calls overnight."),
         d("I covered the midnight cancellation list and finished reconciling the waitlist at 11:20 on Thursday.", "What capacity remained?", "By midafternoon my concentration was thin and I needed quiet time."),
         d("Night triage calls have aggravated my migraines this month, especially when I look at screens for long periods.", "Does that affect group sessions?", "Noise and screens make the fog last longer."),
         d("My vestibular assessment is fixed for Thursday at 17:15 because the specialist only visits our clinic once a month.", "Could it move?", "Not without losing this month's assessment."),
         d("After migraine nights I use water and a quiet break rather than coffee.", "Why not use caffeine?", "It makes the rebound headache worse."),
         d("A colleague says attending the offsite will show I am ready for regional coordination.", "Is that appealing?", "Yes, but it does not change the appointment or the migraine."),
         d("The specialist has moved the vestibular assessment to Friday morning.", "Does Thursday still contain the same conflict?", "No, although I would still need a manageable format after call."),
         "Facilities has invited me to a Thursday afternoon offsite after I cover the cancellation list overnight. How should I respond?",
         "Request a different attendance window rather than accepting the full Thursday afternoon.",
         "request a lower-demand offsite window",
         "The overnight recovery demand, migraine sensitivity, fixed specialist assessment, and no-caffeine recovery plan support an accommodation.",
         "The user handles staff breakfasts and ordinary planning meetings after regular shifts.",
         "Those experiences do not combine overnight triage, screen-sensitive migraine symptoms, and the specialist booking.",
         "The promotion opportunity is attractive but does not resolve the operational and health constraints.",
         ("midnight cancellation coverage", "reconcile urgent openings", "worked through the night and finished at 11:20", "lost reliable afternoon focus"),
         ("vestibular assessment", "complete specialist evaluation", "held the monthly Thursday appointment", "preserved access to the specialist")),

    spec("U03", "museum programs manager", "pg", "accept",
         ("event grid", "gallery calendar", "programs office", "opening weeks"),
         d("I can host a daytime gallery tour without straining my hand.", "Does public-facing work itself cause trouble?", "No, a normal tour is fine."),
         d("A short committee conversation after lunch is manageable.", "What keeps it manageable?", "It is brief and not after a night of alarm calls."),
         d("After covering alarms for a loaned sculpture overnight, I finalized the event grid at 10:30.", "Could you attend a long event later?", "I needed the afternoon to recover from the interrupted night."),
         d("The recent alarm sequence has made my sleep shallow, and my packing-injury hand aches more when I am tired.", "Does fatigue affect the injury?", "Yes, I tense my grip and the ache becomes distracting."),
         d("Hand therapy is scheduled Thursday at 16:45, the only slot before the sculpture travels next week.", "Can the therapy be moved?", "No, the therapist needs to check the hand before the packing work."),
         d("I do not drink espresso after a racing-heart episode during the last opening.", "Can you push through with coffee?", "No, I use a quiet walk and an earlier finish."),
         d("The donor liaison says the offsite would let me meet trustees who fund future programs.", "Does that matter to you?", "It matters, but I should not trade treatment for networking."),
         d("The therapist can inspect my hand remotely on Friday before the packing shift.", "What changes if that is confirmed?", "The Thursday appointment would no longer prevent a shorter offsite visit."),
         "Should I confirm the Thursday afternoon team retreat while I am on the artifact alarm rotation?",
         "Confirm only if the retreat is shortened, moved, or otherwise accommodated.",
         "confirm only with a workable schedule",
         "Overnight alarm recovery, sleep-related hand discomfort, the pre-travel therapy appointment, and the stimulant boundary support a conditional response.",
         "The user handles daytime tours and short committee discussions.",
         "Neither activity follows overnight alarm coverage or displaces necessary hand therapy.",
         "Trustee access offers a benefit but does not establish that this timing is safe or workable.",
         ("artifact alarm rotation", "protect the loaned sculpture", "stayed available through the night and updated the event grid", "required a recovery afternoon"),
         ("hand therapy visit", "assess the packing injury", "kept the pre-travel appointment", "protected readiness for the packing shift")),

    spec("U04", "manufacturing planner", "pg", "accept",
         ("changeover map", "plant roster", "planning bay", "shutdown cycles"),
         d("A normal late-afternoon toolbox talk is easy for me.", "Are group discussions generally a problem?", "No, not on an ordinary day."),
         d("I can make a short check-in after lunch during a regular production week.", "Does that leave you tired?", "No, it is a light commitment."),
         d("After an unplanned furnace-monitoring rotation, I completed the changeover map at 11:05.", "How did you feel by afternoon?", "I needed a quiet reset before I could make careful decisions again."),
         d("Repeated alarm drills have left my sleep light, and the lack of sleep worsens the knee stiffness from my old injury.", "Does that affect long meetings?", "Sitting still for hours after a night shift makes the stiffness much worse."),
         d("My knee rehabilitation session is locked for Thursday at 17:00 as part of my return-to-work plan.", "Can you skip one session?", "No, the therapist uses this week to adjust my work restrictions."),
         d("Cardiology asked me not to use stimulant drinks after the heart-racing episode in May.", "Can you compensate with an energy drink?", "No, I use water and a proper break."),
         d("The plant manager says the offsite identifies future shift leaders.", "Does that pull you toward it?", "Of course, but it does not change how my knee and sleep are doing."),
         d("Rehabilitation can see me Friday after a cancellation.", "Would that alter the answer?", "Yes, provided the offsite does not require a full post-night afternoon."),
         "The plant asks me to attend a Thursday afternoon offsite after furnace monitoring. What response fits my situation?",
         "Ask for a morning, remote, or rescheduled participation option before agreeing.",
         "seek an adjusted participation format",
         "The furnace-monitoring recovery need, light sleep, knee rehabilitation, and inability to use stimulants make the full afternoon a poor fit.",
         "The user attends normal toolbox talks and brief daytime check-ins.",
         "Those events do not require sustained attendance after an overnight control-room rotation.",
         "Leadership prospects are not evidence that the proposed time meets the user's health and calendar needs.",
         ("furnace monitoring rotation", "maintain safe plant oversight", "worked through the night and completed the changeover map", "needed time to reset judgment"),
         ("knee rehabilitation", "update return-to-work treatment", "kept the Thursday session", "maintained the recovery plan")),

    spec("U05", "research administration officer", "pg", "reject",
         ("grant tracker", "faculty diary", "research office", "deadline weeks"),
         d("I manage ordinary faculty meetings in the afternoon without a problem.", "Does collaborative work drain you?", "No, when it follows a settled night."),
         d("I can have coffee with colleagues for an hour after a regular workday.", "Is social contact difficult?", "No, recovery after urgent coverage is the issue."),
         d("During emergency ethics-system coverage, I updated the grant tracker at 10:50 after handling alerts all night.", "What did you need next?", "I needed the afternoon free from sustained conversation."),
         d("Urgent messages have tightened my jaw and broken my sleep for several nights.", "How does that affect you?", "Long discussions leave me irritable and unable to focus."),
         d("My counselling appointment is protected at Thursday 16:30, and the counsellor is away next week.", "Can it be moved?", "Not without delaying the support I arranged after the alert cycle."),
         d("I keep caffeine out of my afternoons after anxious nights because it keeps me awake again.", "Could coffee help you attend?", "It would make the next night's recovery worse."),
         d("The dean says the offsite would broaden my committee network.", "Is that a reason to go?", "It is a reason to find another session, not to ignore the appointment."),
         d("The counsellor can offer a Friday telephone appointment instead.", "Would that affect Thursday's decision?", "Yes, but I would still need the offsite to respect post-coverage recovery."),
         "A Thursday afternoon offsite follows my ethics-system night coverage and overlaps my counselling appointment. Should I accept?",
         "Reject the proposed afternoon and request another way to contribute.",
         "decline the scheduled afternoon",
         "Night coverage, ongoing anxiety-related sleep disruption, the protected counselling session, and the sleep-preserving caffeine boundary make acceptance unsuitable.",
         "The user handles ordinary meetings and optional social coffee after regular work.",
         "Those examples lack both the all-night alert work and the protected care appointment.",
         "Committee networking is a benefit, but it does not remove the health or calendar constraints.",
         ("ethics-system night coverage", "keep urgent approvals moving", "handled alerts until the grant tracker was updated at 10:50", "needed a low-demand afternoon"),
         ("counselling appointment", "maintain support after alert stress", "protected the Thursday session", "avoided delaying care")),

    spec("U06", "transit control supervisor", "pg", "reject",
         ("signal board", "dispatch calendar", "control room", "service disruptions"),
         d("Normal afternoon dispatch briefings are manageable for me.", "Are briefings the problem?", "No, the issue is recovery after overnight incidents."),
         d("I can take a short walk-and-talk after a routine shift.", "Does that help you reset?", "Yes, when I have not spent the night listening for radio alerts."),
         d("After the signal-priority incident rotation, I closed the signal board at 11:15.", "What did that leave for later?", "I had sleep debt and needed a quiet afternoon before the next shift."),
         d("Radio alerts have repeatedly broken my sleep, and the resulting fatigue makes my blood-pressure medication leave me dizzy.", "Does that affect group events?", "A long, noisy room makes the dizziness and fatigue harder to manage."),
         d("My medication review is fixed for Thursday at 16:45 because the prescribing nurse needs my incident-week readings.", "Could it be rescheduled?", "Not until the following month."),
         d("After palpitations, I replaced late coffee with mint tea on my clinician's advice.", "Can you use caffeine to stay alert?", "No, that is not a safe option for me."),
         d("The mayoral office calls the offsite an important visibility event for control supervisors.", "Does that change your plan?", "It explains the pressure, not how I can safely attend."),
         d("The prescribing nurse has opened a Saturday medication-review slot.", "Would that resolve the calendar issue?", "It would, although the offsite would still need to account for overnight recovery."),
         "The city team wants me at a Thursday afternoon offsite after my signal incident rotation. Should I confirm?",
         "Reject the full Thursday-afternoon commitment and ask for an alternative attendance arrangement.",
         "decline unless attendance is adapted",
         "The late incident rotation, broken sleep, medication-related dizziness, fixed review, and no-caffeine boundary do not support the scheduled commitment.",
         "The user manages ordinary briefings and short walks after routine shifts.",
         "Neither recreates the sleep debt and clinical follow-up that accompany an incident rotation.",
         "Civic visibility is not evidence that the user can meet this demand safely.",
         ("signal incident rotation", "restore priority sequencing", "closed the signal board at 11:15 after overnight radio alerts", "carried sleep debt into the afternoon"),
         ("medication review", "check blood-pressure treatment", "kept the incident-week appointment", "enabled a timely dose decision")),

    spec("U07", "library systems manager", "pg", "reject",
         ("migration ledger", "systems calendar", "library lab", "cutover weeks"),
         d("An ordinary afternoon book club is no problem for me.", "Do groups generally exhaust you?", "No, when I have not been on overnight testing."),
         d("I can attend a short librarian huddle after lunch.", "Does that affect your eyes?", "Not usually, because it is brief and not screen-heavy."),
         d("After catalog migration testing overnight, I signed the migration ledger at 10:40.", "How much capacity remained?", "I needed the afternoon away from bright screens and extended discussion."),
         d("Overnight screens have aggravated my dry-eye condition and have begun disrupting my sleep.", "What happens in long sessions?", "My vision blurs and the fatigue becomes much stronger."),
         d("Optometry booked a Thursday 17:10 assessment to check the flare before next week's public cutover.", "Can the assessment move?", "No, the optometrist has no earlier opening before cutover."),
         d("I avoid late coffee because it makes the dry-eye medication and my sleep worse.", "Could you use caffeine to attend?", "No, it would compound the problem."),
         d("A trustee says the offsite is the best place to champion the migration.", "Does that persuade you?", "It makes me want to send a written update, not sacrifice the assessment."),
         d("The optometrist can review photos remotely on Friday morning.", "Does that change the Thursday constraint?", "Yes, although I would still need to limit post-testing screen time."),
         "A team offsite is set for Thursday afternoon after migration testing and before my eye assessment. What should I do?",
         "Reject the scheduled session and offer a written update or a different attendance time.",
         "decline the screen-heavy afternoon",
         "Overnight testing, dry-eye and sleep symptoms, the cutover-critical optometry assessment, and the caffeine restriction make the proposed session unsuitable.",
         "The user enjoys book clubs and short huddles on normal days.",
         "Those activities do not follow overnight screen exposure or collide with clinical care before cutover.",
         "Trustee enthusiasm supports communicating about the migration, not accepting an incompatible time.",
         ("catalog migration test", "validate the public cutover", "tested through the night and signed the ledger at 10:40", "needed screen-free recovery time"),
         ("optometry assessment", "evaluate the dry-eye flare", "kept the pre-cutover appointment", "protected safe work during the public launch")),

    spec("U08", "compliance training lead", "pg", "reject",
         ("certification roster", "training calendar", "learning office", "renewal cycles"),
         d("I attend regular afternoon workshops effectively.", "Are workshops inherently difficult?", "No, they work when I have had a normal night."),
         d("A brief planning call after lunch is manageable.", "Why is it manageable?", "It ends before fatigue builds and I can step away afterward."),
         d("After restoring the certification platform overnight, I finished reconciling the roster at 11:10.", "What did you need that afternoon?", "I needed to reduce demands and sleep before the next workday."),
         d("Emergency messages have increased my anxiety and interrupted sleep, and long social rooms trigger my tinnitus.", "How does that affect an offsite?", "Sustained noise makes the fatigue and ringing harder to control."),
         d("My audiology rehabilitation session is Thursday at 16:50, with an adjustment needed before the next training cycle.", "Can you postpone it?", "No, the audiologist will be at a conference afterward."),
         d("I use rooibos instead of espresso after anxious nights because caffeine intensifies the ringing.", "Can you take coffee for the offsite?", "No, that would make the evening worse."),
         d("An executive note says offsite attendance signals leadership readiness.", "Does that create pressure?", "Yes, but it is not a reason to abandon recovery or treatment."),
         d("The audiologist can conduct the adjustment by video on Friday.", "Would the answer change?", "The fixed clash would lift, but I would still need a quiet, shorter format."),
         "The executive team asks me to confirm a Thursday afternoon offsite after platform recovery. Should I accept?",
         "Reject the scheduled session and request a quieter, shorter, or later alternative.",
         "decline and request an adapted format",
         "Overnight platform recovery, anxiety-related sleep loss, tinnitus sensitivity, the fixed audiology session, and the caffeine limit rule out the proposed format.",
         "The user performs well in normal workshops and short planning calls.",
         "Those events do not include overnight restoration work, prolonged noise exposure, or treatment timing.",
         "Leadership signaling describes an incentive but not a workable recovery or care plan.",
         ("certification-platform recovery", "restore learner access", "worked overnight and reconciled the roster at 11:10", "needed reduced demands afterward"),
         ("audiology rehabilitation", "adjust tinnitus treatment", "kept the Thursday session", "protected the next training cycle")),

    spec("U09", "environmental field coordinator", "sf", "conditional",
         ("sampling log", "field rota", "field office", "survey weeks"),
         d("I enjoy normal afternoon site walks after daytime sampling.", "Does fieldwork tire you in general?", "No, a regular day outside feels restorative."),
         d("A brief debrief with the survey crew is easy after lunch.", "What makes it easy?", "It is short and does not follow an all-night watch."),
         d("After overnight flood-sensor monitoring, I completed the sampling log at 10:55.", "Could you take on a long meeting later?", "Only if I had time to recover first; my attention was unreliable."),
         d("Storm alerts have fractured my sleep, and the poor sleep is aggravating my Achilles tendon flare.", "How does that affect attendance?", "Standing through a long retreat after a watch makes the tendon tighten quickly."),
         d("Tendon therapy is fixed for Thursday at 16:30 because the therapist needs to clear me for next week's river survey.", "Can the appointment move?", "No, the survey plan depends on that assessment."),
         d("I avoid coffee after a racing-heart episode and use hydration and an early finish instead.", "Can caffeine solve the fatigue?", "No, it would undermine the next night's sleep."),
         d("The regional director says the offsite could help me win larger survey sites.", "Does that affect your choice?", "It makes an alternative worth requesting, not the full afternoon worth forcing."),
         d("The therapist can clear me by video on Friday if the river level stays safe.", "What would that change?", "I could consider a remote offsite after recovery, but not a standing retreat immediately after monitoring."),
         "The survey unit wants a Thursday afternoon offsite commitment after flood monitoring. Is there a workable way to participate?",
         "Participate only if the offsite is remote or rescheduled after recovery and the therapy requirement is met.",
         "participate only with remote or later attendance",
         "The overnight monitoring demand, disrupted sleep, tendon flare, fixed clearance appointment, and caffeine boundary require both recovery time and a lower-load format.",
         "The user handles ordinary site walks and short crew debriefs.",
         "Neither requires sustained standing after a flood watch or competes with clearance for the river survey.",
         "The prospect of larger sites is valuable, but it does not make the immediate in-person retreat fit.",
         ("flood-sensor monitoring", "protect the river survey data", "monitored through the night and completed the sampling log at 10:55", "had unreliable afternoon attention"),
         ("tendon therapy", "clear the Achilles flare for fieldwork", "kept the Thursday assessment", "preserved readiness for the river survey")),

    spec("U10", "customer service quality lead", "sf", "conditional",
         ("quality queue", "service diary", "quality hub", "escalation rotations"),
         d("A normal afternoon coaching session goes well for me.", "Can you sustain a standard team session?", "Yes, after a routine day with normal sleep."),
         d("I can make a short check-in after lunch without losing focus.", "What makes that manageable?", "It is bounded and does not follow a night of escalations."),
         d("After an overnight fraud-escalation rotation, I cleared the quality queue at 11:00.", "How did you feel afterward?", "I could complete urgent work, but I needed a quiet afternoon before speaking with a group."),
         d("Pager bursts have disrupted my sleep for days, and fatigue makes my shoulder tendinitis ache at the desk.", "Would a long offsite affect that?", "Long sitting and constant conversation after a rotation make both the ache and my judgment worse."),
         d("My physiotherapy session is Thursday at 17:20, and the therapist needs to reassess my workstation plan before the audit week.", "Can it be moved?", "No, the next available session is after the audit."),
         d("I do not use late caffeine after palpitations because it keeps the sleep cycle broken.", "Can you push through with coffee?", "No, I need recovery rather than a second wind."),
         d("My vice president says the offsite is ideal for showcasing quality leadership.", "Does that tempt you to accept?", "It does, but I would rather contribute well in a format that fits."),
         d("The physiotherapist can review the workstation plan by video Friday morning.", "Would that make participation possible?", "Yes, if the offsite is remote or moved to a day after the escalation rotation."),
         "My manager wants me at a Thursday afternoon offsite after fraud-escalation night duty. What participation plan fits?",
         "Offer remote participation or a rescheduled session after the rotation, contingent on protecting the physiotherapy plan.",
         "offer remote or later participation",
         "The post-escalation recovery demand, persistent sleep disruption, shoulder treatment, and no-caffeine boundary support participation only in an adjusted format.",
         "The user succeeds in regular coaching sessions and short daytime check-ins.",
         "Those activities do not recreate an overnight escalation, sustained sitting discomfort, or a treatment collision.",
         "Quality-leadership visibility is a reason to find a workable option, not proof that the scheduled offsite fits.",
         ("fraud-escalation rotation", "resolve urgent quality cases", "worked overnight and cleared the queue at 11:00", "needed a quiet afternoon before group work"),
         ("physiotherapy session", "update the shoulder workstation plan", "kept the Thursday appointment", "prepared safely for audit week")),
]
