from generate_s1_s5_review_batch import d, spec

S15 = [
    spec("U01", "cloud incident commander", "be", "accept",
         ("service graph", "incident roster", "war room", "overnight rotations"),
         d("I can give a prepared daytime outage briefing without losing the thread.",
           "What supports that?",
           "I have the dependency graph open before anyone asks for a decision."),
         d("A short afternoon postmortem after a normal shift is manageable for me.",
           "So discussion itself is not the issue?",
           "No; improvising restore order while tired is the issue."),
         d("During the billing-region Sev-1, I drew the graph from database replication through the API gateway before naming the recovery order.",
           "Did that affect the call?",
           "Yes. We restored the ledger path first and avoided reopening traffic too early."),
         d("After two consecutive pager nights, I need an uninterrupted morning before I make priority calls.",
           "Is that simply a preference?",
           "No. I have found that recovery debt makes competing dependencies blur together."),
         d("At last month's map-free cache outage, I put worker recovery ahead of the identity store and delayed customer access.",
           "What went wrong?",
           "I tried to hold the chain in my head while the room was talking."),
         d("Late caffeine brings on palpitations for me, so a quiet recovery block is my only reliable way to reset.",
           "Can you compensate by pushing through?",
           "No. I need sleep or a daytime slot."),
         d("The VP says leading the 23:00 room would put me on the executive incident list.",
           "Does that solve the operating problem?",
           "It does not provide a graph or erase two nights of sleep debt."),
         d("If the incident lead posts the current service graph and moves my leadership turn to 10:00 after rest, I can take the call.",
           "Why would that change it?",
           "The order would be visible and I would be recovered enough to use it."),
         "Why do I keep asking for a graph and a daytime turn before I lead an overnight Sev-1 war room?",
         "Because this user's reliable live leadership depends on an external dependency graph and recovered judgment.",
         "request the graph and a recovered leadership window",
         "The successful billing incident used a drawn dependency chain, while the map-free cache call reversed the order under sleep debt.",
         "The user manages prepared daytime briefings and normal-shift postmortems.",
         "Neither requires choosing a restoration order live after repeated pager nights.",
         "Executive visibility is not evidence that the conditions for reliable sequencing are present.",
         ("billing-region Sev-1", "choose a restoration order", "drew the service graph before speaking", "ledger path restored first"),
         ("map-free cache outage", "set restore priorities live", "held dependencies in memory while exhausted", "identity recovery delayed")),

    spec("U02", "emergency department flow lead", "cr", "accept",
         ("patient-flow board", "night rota", "command room", "surge coverage"),
         d("I lead scheduled daytime bed huddles well when the flow board is current.",
           "What makes those huddles workable?",
           "The board shows which discharge, imaging, and staffing steps release each bed."),
         d("I can cover a brief evening handover after a regular day.",
           "Does that mean every late command call works?",
           "No. A handover is not a live surge decision after a night shift."),
         d("During the winter influenza surge, I traced the bottleneck from discharge pharmacy to transport before opening overflow bays.",
           "What followed?",
           "We released beds without sending patients into a blocked transport queue."),
         d("This week I have covered three overnight ambulance-diversion calls, and I protect the next morning for sleep.",
           "Why protect it?",
           "My judgment in competing admission paths is slower until I recover."),
         d("On the March surge call, I opened observation beds before confirming radiology capacity, and patients waited in the wrong stream.",
           "Was there a board available?",
           "No. I was working from shouted updates after a night on duty."),
         d("Migraine medication leaves me foggy if I use it after midnight; a rested morning command slot is the safer alternative.",
           "Can a stimulant solve that?",
           "No. Bright screens and caffeine make the rebound worse."),
         d("The chief nurse says the 01:00 command chair is how people show they can run the department.",
           "How does that bear on the choice?",
           "It does not make the flow board current or restore my sleep."),
         d("If the bed-management analyst maintains the board and another lead takes the first hour, I can chair the recovered morning review.",
           "Would that be enough?",
           "Yes. The map and recovery period address the two known failure points."),
         "The chief nurse wants me to chair tonight's 01:00 surge war room. What should I propose?",
         "Accept leadership only with a live patient-flow board and a recovered handoff into the decision role.",
         "ask another lead to cover the first hour and chair the mapped morning review",
         "The user has led a mapped surge successfully, but a night, board-free call sent patients into the wrong stream.",
         "The user handles scheduled bed huddles and short regular-day handovers.",
         "Those do not test real-time bed allocation after overnight diversion work.",
         "Leadership signaling does not replace current flow information or sleep.",
         ("winter influenza surge", "release beds safely", "traced pharmacy, transport, and staffing dependencies", "overflow opened in the right order"),
         ("March surge call", "place patients during a spike", "opened beds before checking radiology capacity", "patients waited in the wrong stream")),

    spec("U03", "network operations manager", "cr", "reject",
         ("topology map", "on-call ledger", "network bridge", "maintenance nights"),
         d("I run a planned daylight maintenance bridge accurately from the topology map.",
           "What does the map give you?",
           "The upstream routing and authentication dependencies are visible at once."),
         d("I can answer a routine alert-summary question late in the day.",
           "Is that comparable to directing an outage?",
           "No. A summary does not require committing a rollback sequence."),
         d("For the metro routing outage, I marked the route reflectors and DNS edge on the topology before authorizing the rollback.",
           "Did that prevent a mistake?",
           "It kept us from restoring customer routes before name resolution was stable."),
         d("I am carrying recovery debt from a midnight fiber cut and a 04:00 maintenance page, so I am not taking another night command slot.",
           "Could you sleep between them?",
           "Not enough to be reliable by 22:30."),
         d("At the last uncharted BGP incident, I restarted the edge pair before the route reflector and extended the outage.",
           "Why did that happen?",
           "I had no current topology and was exhausted from the preceding maintenance window."),
         d("My cardiologist asked me to avoid overnight energy drinks after an arrhythmia episode; a next-day deputy role is the safe alternative.",
           "Can you lead briefly anyway?",
           "Not when the decision window may run for hours."),
         d("The CTO says the night bridge is the best chance to demonstrate command presence.",
           "Does that alter your readiness?",
           "No. Presence is not a topology or recovery plan."),
         d("A fully updated topology and a rested 14:00 rollback review would let me contribute as incident lead.",
           "What changes in that arrangement?",
           "The known sequencing gap and the sleep debt are both removed."),
         "Should I take the 22:30 Sev-1 bridge after the fiber-cut night?",
         "Reject the overnight bridge as proposed.",
         "decline and offer to lead the mapped daytime rollback review",
         "A mapped daylight rollback succeeded; an uncharted, exhausted bridge produced the same ordering error the proposed shift invites.",
         "The user can run planned maintenance and answer routine late-day summaries.",
         "Neither involves deciding a live rollback after multiple night interruptions.",
         "Command presence does not change the arrhythmia precaution or missing topology.",
         ("metro routing outage", "authorize rollback", "marked route-reflector and DNS dependencies", "customer routes restored cleanly"),
         ("uncharted BGP incident", "recover external routing", "restarted edge pair before route reflector", "outage extended")),

    spec("U04", "rail service recovery chief", "cr", "reject",
         ("traction sequence board", "disruption rota", "control room", "night incidents"),
         d("I lead planned daytime service changes well with the traction sequence board in front of me.",
           "Why does that help?",
           "It makes power isolation, train positioning, and crew release visible in one order."),
         d("I can take a short late-afternoon depot update after ordinary work.",
           "Does that prove a night emergency is suitable?",
           "No. A depot update does not commit passenger recovery under pressure."),
         d("When a substation fault stopped the east line, I mapped power clearance before moving replacement buses and reopened safely.",
           "What did the map prevent?",
           "It stopped us sending buses before the stranded trains could be released."),
         d("I finished an all-night weather disruption at dawn and have a mandated recovery day after it.",
           "Can you waive the day?",
           "No. It exists because fatigue has affected command decisions before."),
         d("During a snow-night incident without the sequence board, I dispatched buses before confirming platform clearance and created a second bottleneck.",
           "What was missing?",
           "The dependency order and the rest to reason through it."),
         d("My sleep specialist has asked me to keep the recovery day after night duty; a rested deputy can cover tonight's room.",
           "Is there another workable route?",
           "Yes, I can prepare the board for the deputy and return tomorrow."),
         d("The regional director says accepting the 00:30 chair would be seen as true crisis leadership.",
           "Does that change the safety requirements?",
           "It does not change clearance dependencies or the recovery rule."),
         d("If the deputy chairs tonight using my completed sequence board, I can lead the 11:00 recovery review tomorrow.",
           "What does that preserve?",
           "Both continuous command coverage and the mandated rest."),
         "The director asks me to chair a 00:30 rail-recovery war room after last night's weather disruption. How should I respond?",
         "Reject the request to chair tonight's war room.",
         "prepare the sequence board for the deputy and lead tomorrow's recovery review",
         "The user succeeded with a mapped substation response, while a board-free snow night created a second bottleneck; recovery day is mandatory.",
         "The user can lead planned changes and short depot updates.",
         "Neither is a night emergency immediately following all-night disruption duty.",
         "Crisis-leadership language does not supersede fatigue safeguards.",
         ("east-line substation fault", "restore passenger service", "mapped power clearance before bus deployment", "safe reopening order"),
         ("snow-night incident", "replace stranded service", "dispatched buses before platform clearance", "second bottleneck created")),

    spec("U05", "fraud response director", "cr", "reject",
         ("attack-path canvas", "fraud roster", "response room", "after-hours escalations"),
         d("I make good daytime fraud-containment calls when the attack path is sketched.",
           "What does the sketch show?",
           "Which merchant, identity, and payout controls have to close first."),
         d("I can review a normal afternoon loss report without strain.",
           "Is that the same as an active fraud ring?",
           "No. Reports do not force a live freeze decision."),
         d("In the vendor-token breach, I charted the path from credential reset to payout holds before freezing accounts.",
           "What was the result?",
           "We preserved legitimate merchants while stopping the fraudulent exit path."),
         d("I have been awake through two 02:00 account-takeover escalations and have a recovery appointment tomorrow morning.",
           "Why not take tonight too?",
           "A third night would leave no recovery before the appointment."),
         d("On a prior uncharted takeover call, I froze payouts before closing the credential-reset route, and the attackers shifted channels.",
           "What caused the miss?",
           "I was making the chain up live after an overnight escalation."),
         d("My therapist and I set a no-night-call boundary during panic-symptom treatment; a written containment plan is the alternative.",
           "Can you remain available asynchronously?",
           "Yes. I can review the canvas before the room convenes."),
         d("The COO says taking the 23:00 chair would show the board I can handle enterprise risk.",
           "Does that remove the treatment boundary?",
           "No. It only adds pressure to ignore it."),
         d("If the team uses my attack-path canvas and the deputy chairs tonight, I can take the daylight decision review after treatment.",
           "Would that keep control of the response?",
           "Yes. The containment logic is available without another overnight chair."),
         "Do I accept the 23:00 account-takeover war-room chair after two escalation nights?",
         "Reject the overnight chair.",
         "send the attack-path canvas and ask the deputy to lead tonight",
         "The user's mapped vendor-token response succeeded, while an exhausted map-free takeover allowed attackers to shift channels; treatment requires a night-call boundary.",
         "The user handles daytime containment calls and ordinary loss-report review.",
         "Neither reproduces live fraud sequencing after repeated overnight escalations.",
         "Board exposure is not a reason to discard a clinical recovery boundary.",
         ("vendor-token breach", "contain fraudulent payouts", "charted credential and payout dependencies", "fraud path stopped without broad freezes"),
         ("uncharted takeover call", "stop account misuse", "froze payouts before closing credential route", "attackers shifted channels")),

    spec("U06", "plant reliability engineer", "cr", "reject",
         ("failure-mode tree", "maintenance roster", "reliability room", "shutdown nights"),
         d("I can direct a scheduled daytime inspection when the failure-mode tree is prepared.",
           "How does it affect your work?",
           "It distinguishes the lubrication, cooling, and control dependencies before we touch equipment."),
         d("I can join a brief shift-end safety talk after a normal day.",
           "Why is that not enough here?",
           "It is not a live decision about whether to restart a compressor."),
         d("During the turbine oil-pressure event, I used the tree to verify cooling flow before authorizing the restart.",
           "What happened?",
           "We avoided loading the turbine against an unresolved temperature fault."),
         d("I am on the second night of a shutdown window and must take the contracted twelve-hour rest before another control-room decision.",
           "Could you make an exception?",
           "Not safely, and not under the fatigue agreement."),
         d("In an earlier overnight compressor trip, I cleared the pressure alarm before checking the cooling interlock and triggered a second shutdown.",
           "What led to that?",
           "The tree was not available and I was at the end of a night shift."),
         d("A medication adjustment causes early-morning dizziness; the control-room supervisor is the safer lead until I have rested.",
           "Is there an alternative contribution?",
           "I can annotate the failure-mode tree before I sleep."),
         d("The plant manager says tonight's chair will be remembered during promotion planning.",
           "Does that reduce the restart risk?",
           "No. It does not change the rest requirement or the interlock order."),
         d("With a completed tree and a rested supervisor at the chair, the 09:00 restart review can proceed without me overnight.",
           "What role can you take then?",
           "I can attend the daytime review after my rest window."),
         "What should I tell the plant manager about chairing tonight's compressor Sev-1 room?",
         "Reject chairing the room during the current shutdown night.",
         "complete the failure-mode tree, then join the rested 09:00 review",
         "The mapped turbine restart was safe; an overnight tree-free compressor response caused a second shutdown, and the fatigue agreement bars another night decision.",
         "The user handles planned inspections and brief safety talks.",
         "Neither requires live restart authorization at the end of a shutdown night.",
         "Promotion attention does not alter the fatigue agreement or medication effect.",
         ("turbine oil-pressure event", "authorize a restart", "verified cooling flow through the failure-mode tree", "temperature fault avoided"),
         ("overnight compressor trip", "restore compressor operation", "cleared pressure before checking cooling interlock", "second shutdown triggered")),

    spec("U07", "public safety dispatcher", "cr", "conditional",
         ("agency dependency board", "dispatch schedule", "coordination room", "overnight alerts"),
         d("I coordinate planned daytime exercises accurately from the agency dependency board.",
           "What does the board clarify?",
           "Which evacuation, medical, and traffic actions must happen before a public alert."),
         d("I can take a short evening radio check after a regular shift.",
           "Does that make a midnight multi-agency call routine?",
           "No. The call requires choosing the order for several agencies at once."),
         d("During the river evacuation, I placed road closure, shelter transport, and hospital diversion on the board before issuing the public message.",
           "Did the sequence hold?",
           "Yes. Every agency received the same workable order."),
         d("After four nights of storm alerts, I need a protected sleep block before I take command decisions.",
           "Is that necessary even on a quiet night?",
           "Yes. The accumulated recovery debt is the risk, not only the next alert."),
         d("In a map-free wildfire call, I announced the evacuation route before confirming ambulance access, forcing a last-minute reroute.",
           "Why did that happen?",
           "I was tired and relied on radio fragments instead of a shared board."),
         d("My asthma worsens with overnight smoke exposure, so remote daytime coordination is the health-safe alternative.",
           "Could you still support the team?",
           "Yes, by preparing the board and joining after sleep from a clean-air location."),
         d("The commissioner says taking the 00:00 chair will make me the face of the response.",
           "Does that address the operational conditions?",
           "No. It ignores the smoke exposure and the missing board."),
         d("If the overnight chair uses a current agency board and I take the 13:00 remote coordination review after rest, I can lead effectively.",
           "What makes that conditional?",
           "Both the shared order and the recovery arrangement must be in place."),
         "The commissioner wants me to chair a midnight wildfire coordination room. What terms should I set?",
         "Accept only if another dispatcher covers overnight command and a current dependency board supports a rested remote review.",
         "offer the 13:00 remote lead after preparing the agency board",
         "The user led a mapped evacuation effectively, whereas a tired map-free wildfire call required a dangerous reroute; recovery and smoke avoidance are necessary.",
         "The user handles planned exercises and brief evening radio checks.",
         "Neither tests live multi-agency ordering after several storm-alert nights.",
         "Being the public face of a response does not make smoke exposure or recovery debt safe.",
         ("river evacuation", "coordinate agency actions", "sequenced road, shelter, and hospital dependencies", "shared evacuation order held"),
         ("map-free wildfire call", "announce an evacuation route", "announced before ambulance access was confirmed", "last-minute reroute required")),

    spec("U08", "data center manager", "cr", "conditional",
         ("power-chain diagram", "facility rota", "incident suite", "cooling alarms"),
         d("I lead scheduled daytime resilience tests well when the power-chain diagram is current.",
           "What does that diagram provide?",
           "It shows the generator, UPS, cooling, and load-transfer order."),
         d("I can read a normal evening facilities report without trouble.",
           "Is that equivalent to an overnight thermal event?",
           "No. Reading a report is not choosing a live transfer sequence."),
         d("During a chiller fault, I traced cooling dependency through the UPS room before moving load to the backup plant.",
           "What did that avoid?",
           "We kept the battery room from overheating during the transfer."),
         d("The last two cooling alarms woke me at 01:00 and 03:30; I am scheduled for protected recovery until noon.",
           "Can you simply start later?",
           "Not if the room begins at 02:00 and needs a decision immediately."),
         d("On a previous night without the diagram, I shifted load before confirming the backup chiller and tripped a rack row.",
           "What was the key error?",
           "I acted on temperature alarms without seeing the full power-and-cooling chain."),
         d("My clinician has limited overnight screen work during vestibular treatment; an annotated diagram for the on-call manager is the alternative.",
           "Can you contribute without chairing?",
           "Yes. I can leave the transfer sequence and join the recovered afternoon review."),
         d("The COO says the 02:00 room is where infrastructure leaders prove they are unflappable.",
           "Does that change your clinical limit?",
           "No. It is rhetoric, not a safer transfer path."),
         d("If the on-call manager has the annotated diagram and the decision review moves to 13:00, I can lead the follow-up after recovery.",
           "What has to be true?",
           "The diagram must be current and the overnight screen restriction must be respected."),
         "How should I answer the request to lead a 02:00 cooling-failure war room?",
         "Accept only with an on-call manager using a current power-chain diagram overnight and a recovered daytime leadership review.",
         "provide the transfer sequence now and lead the 13:00 review",
         "The successful chiller response followed a diagram; a diagram-free night transfer tripped a rack row, while recovery and vestibular treatment limit overnight command.",
         "The user can lead daytime tests and read ordinary evening reports.",
         "Neither is a real-time thermal transfer after interrupted sleep.",
         "Claims about being unflappable do not revise the medical screen-work limit.",
         ("chiller fault", "transfer load safely", "traced cooling through the UPS room", "battery room protected"),
         ("diagram-free night transfer", "respond to rising temperature", "shifted load before backup chiller confirmation", "rack row tripped")),

    spec("U09", "market operations supervisor", "cr", "non_decision",
         ("settlement dependency sheet", "trading rota", "market command room", "overnight volatility"),
         d("I can explain a prepared daytime settlement plan clearly from the dependency sheet.",
           "What does that show?",
           "Which collateral, venue, and confirmation steps have to settle in sequence."),
         d("I can handle a routine end-of-day market recap.",
           "Does that decide a live halt?",
           "No. A recap is not a judgment about linked settlement risk."),
         d("During the settlement-feed disruption, I mapped collateral release before reopening the affected venue.",
           "What was the outcome?",
           "We avoided releasing trades into an unconfirmed confirmation queue."),
         d("I am carrying sleep debt from a volatility watch and have a recovery morning booked before the next trading session.",
           "Why is that booked?",
           "Because I make poorer cross-market comparisons after a night alert."),
         d("On a prior map-less order-book break, I reopened one venue before confirming collateral status and created unmatched trades.",
           "What was different then?",
           "I was leading live after an overnight watch with no dependency sheet."),
         d("My blood-pressure medication requires a fixed sleep schedule; a written overnight recommendation is the health-safe alternative.",
           "Can you still advise the room?",
           "Yes. I can send the dependency sheet and thresholds before I disconnect."),
         d("The head of markets says the 01:00 chair would put me in front of the global desk.",
           "Does that determine whether you should chair?",
           "No. It says nothing about recovered judgment or settlement order."),
         d("If the deputy chairs with my sheet and the decision review occurs after my recovery morning, I can reassess whether to lead the follow-up.",
           "Is that a commitment to chair?",
           "No. It preserves the information and recovery conditions first."),
         "The global desk asks whether I will chair its 01:00 settlement-break war room. What should I tell them?",
         "Do not decide to chair until a deputy, dependency sheet, and post-recovery review are arranged.",
         "send the settlement thresholds and defer the chair decision until after recovery",
         "A mapped daytime settlement response succeeded, while an exhausted map-free reopening created unmatched trades; the overnight health routine also matters.",
         "The user can explain prepared plans and give routine market recaps.",
         "Neither establishes readiness to chair a live settlement halt at 01:00.",
         "Global-desk exposure is unrelated to the conditions needed for a sound decision.",
         ("settlement-feed disruption", "reopen a venue safely", "mapped collateral before confirmation dependencies", "unmatched trades avoided"),
         ("map-less order-book break", "reopen market activity", "reopened before collateral confirmation", "unmatched trades created")),

    spec("U10", "water treatment controller", "cr", "non_decision",
         ("treatment cascade board", "plant rota", "control room", "night alarms"),
         d("I can lead a prepared daytime treatment review with the cascade board open.",
           "What does it make clear?",
           "The intake, dosing, filtration, and distribution dependencies are in a visible sequence."),
         d("I can take a brief evening quality reading after a normal shift.",
           "Does that show you should chair a night alarm?",
           "No. A reading is not a live choice about treatment isolation."),
         d("During a turbidity spike, I used the cascade board to isolate intake before changing coagulant dosing.",
           "What did that prevent?",
           "We avoided pushing untreated water into the filter train."),
         d("A 03:00 chlorine alarm last night left me with a protected recovery morning and no reserve for another midnight room.",
           "Could you just take the call from home?",
           "The recovery problem follows me home; it is not a commute issue."),
         d("In a previous unboarded chlorine event, I increased dosing before confirming the intake valve position and caused a filter shutdown.",
           "Why was the order wrong?",
           "I was tired and tried to reconstruct the cascade during the call."),
         d("My sleep physician has restricted consecutive overnight alarms while we adjust treatment; the alternate is for me to prepare the board before rest.",
           "Can the team use that without you?",
           "Yes. The overnight controller can follow it and call me after recovery if needed."),
         d("The utilities director says chairing at midnight would prove I am ready for regional command.",
           "Does that change the treatment plan?",
           "No. It does not create recovery or make the cascade visible."),
         d("With the cascade board completed, the overnight controller can run the first room and I can decide about a daytime follow-up after rest.",
           "Is that a yes to the midnight chair?",
           "No. It is a plan that keeps the plant supported without precommitting beyond my health limit."),
         "The utilities director asks if I will chair another midnight chlorine-alarm war room tonight. What is the appropriate response?",
         "Do not commit to chairing tonight; provide the cascade board and revisit the leadership role after recovery.",
         "prepare the cascade board for the overnight controller and reassess at daytime handoff",
         "The user used the cascade board successfully during a turbidity spike, but an exhausted board-free chlorine response caused a shutdown; consecutive overnight alarms are medically restricted.",
         "The user can conduct prepared daytime reviews and brief evening readings.",
         "Neither indicates that a second midnight command decision is appropriate.",
         "Regional-command recognition does not negate the recovery requirement or known sequencing failure.",
         ("turbidity spike", "protect treatment quality", "isolated intake before changing dosing", "filter train protected"),
         ("unboarded chlorine event", "stabilize chemical treatment", "changed dosing before intake-valve confirmation", "filter shutdown caused")),
]
