import generate_s1_s5_review_batch as base
from generate_s1_s5_review_batch import d, spec


S13 = [
    base.spec("U01", "port operations controller", "rr", "accept",
        ("port operations controller", "berth ledger", "APAC bridge", "vessel handoff"),
        d("I can give a normal berth update from the departure board.", "Is a routine update difficult?", "No, when the berth status is already settled."),
        d("I can answer a carrier's scheduling question after checking the ledger.", "Does a ledger check help?", "It keeps the answer tied to the recorded position."),
        d("For a delayed feeder vessel, I prepare a written split of confirmed berth times, carrier reports, and unresolved movements before speaking on the APAC bridge.", "Why split the entries?", "So the next controller can see which parts are not yet verified."),
        d("The 06:40 Singapore handoff is the last overlap before the harbourmaster assigns the morning berths.", "Can the assignment wait?", "No, the allocation is made immediately after the bridge."),
        d("Last monsoon season I verbally called a vessel clear before the pilot confirmation arrived, and the berth was reassigned unnecessarily.", "What went wrong?", "I treated a carrier update as if it were a confirmed movement."),
        d("The bridge room is beside the quay and the foghorn is audible through the windows.", "Does that affect the record?", "No, it is only a noisy setting."),
        d("A colleague says owning the bridge will make me visible to the regional director.", "Does visibility settle the evidence?", "No, it does not establish the vessel's position."),
        d("The pilot confirmation and the berth ledger are both available before the handoff.", "What changes then?", "The earlier uncertainty about the vessel movement is gone."),
        "The Singapore controller asks whether I should own the delayed-feeder handoff at 06:40. How should I rank taking it?", "Take ownership with the written evidence split attached.", "state confirmed berth times, reported movements, and unresolved items",
        "The written split, fixed allocation window, and prior error support a bounded handoff rather than an unsupported verbal assurance.", "The user can report settled berth status.", "Routine status does not require resolving a missing movement confirmation.", "Director visibility is unrelated to whether the movement is confirmed.",
        ("delayed feeder", "prepare written evidence split", "confirmed and unresolved movements", "bounded ownership"),
        ("previous verbal clearance", "assign berth", "pilot confirmation missing", "unnecessary reassignment")),
    base.spec("U02", "merchant-acquiring risk lead", "rr", "accept",
        ("merchant-acquiring risk lead", "settlement dashboard", "APAC bridge", "chargeback handoff"),
        d("I can summarize yesterday's settled chargebacks from the dashboard.", "Is that the same as deciding a new hold?", "No, the settled figures need no inference."),
        d("I can route a merchant question to the investigations queue.", "Does routing establish cause?", "No, it only starts the review."),
        d("For a sudden chargeback cluster, I write an evidence ledger separating issuer-confirmed codes, merchant claims, and transactions still awaiting network response.", "Why make a ledger?", "It prevents a tentative pattern from becoming a stated cause."),
        d("The 07:10 Hong Kong bridge ends fifteen minutes before the network's temporary-hold window closes.", "Is there time for a later discussion?", "No, the hold request must be sent within that window."),
        d("In a prior cluster, I said fraud was established from merchant emails and requested a broad hold; network data later showed a duplicate-submission defect.", "What was the consequence?", "Several legitimate merchants were paused."),
        d("The office coffee machine is being replaced this week.", "Does that bear on the hold?", "No, it is simply an office disruption."),
        d("The sales team says a decisive call will reassure a prospective enterprise merchant.", "Does reassurance verify the pattern?", "No, it cannot substitute for network evidence."),
        d("The network response has identified the duplicate-submission defect before the bridge.", "What does that allow?", "A direct explanation without treating the cause as uncertain."),
        "Rank accepting the Hong Kong chargeback handoff for the next bridge.", "Accept it if the evidence ledger travels with the handoff.", "name verified codes, merchant assertions, and pending network responses",
        "The ledger preserves the live constraint while preventing a repeat of the unsupported broad hold.", "The user can summarize settled chargebacks.", "That task does not require attributing an active cluster.", "Sales reassurance is not evidence of fraud.",
        ("chargeback cluster", "write evidence ledger", "verified codes and pending responses", "qualified handoff"),
        ("prior broad hold", "attribute cluster", "network data absent", "legitimate merchants paused")),
    base.spec("U03", "radiology workflow coordinator", "rr", "accept",
        ("radiology workflow coordinator", "imaging queue", "APAC bridge", "urgent-study handoff"),
        d("I can read the completed imaging queue to the next shift.", "Does that involve uncertainty?", "No, completed studies are already signed off."),
        d("I can book a scanner slot after a radiologist approves it.", "Can booking alone determine priority?", "No, the clinical rationale comes first."),
        d("For an urgent neuroimaging request, I send a written triage note that labels confirmed symptoms, the referring clinician's concern, and missing contraindication details.", "Why label the sources?", "So the incoming coordinator does not mistake a concern for a cleared indication."),
        d("The 06:55 Tokyo bridge is followed by a scanner-maintenance lock at 07:20.", "Why does that matter?", "The urgent slot must be protected before the lock begins."),
        d("I once verbally described a patient as cleared for contrast when the renal result was still pending, and the slot had to be cancelled at the door.", "What caused the cancellation?", "I collapsed a pending result into a definite clearance."),
        d("The night team decorates the control room with paper cranes during festival week.", "Does that change triage?", "No, it is only part of the room's atmosphere."),
        d("A senior physician says taking the handoff will show that I can keep the queue moving.", "Does speed establish clearance?", "No, the missing result still needs to be visible."),
        d("The renal result is posted and the radiologist has approved contrast before the bridge.", "What is different?", "The contraindication question is resolved."),
        "How should I rank taking the Tokyo urgent-study handoff?", "Accept it with the source-labeled triage note.", "carry the symptom, concern, and pending-result labels into the bridge",
        "The note allows timely slot protection while guarding against the prior clearance mistake.", "The user can report completed studies.", "Completed work does not require interpreting a pending renal result.", "Queue speed does not make contrast clearance certain.",
        ("urgent neuroimaging", "send source-labeled triage note", "confirmed symptoms and pending result", "safe bridge ownership"),
        ("earlier verbal clearance", "reserve contrast slot", "renal result pending", "door-side cancellation")),
    base.spec("U04", "air-cargo customs supervisor", "rr", "reject",
        ("air-cargo customs supervisor", "manifest console", "APAC bridge", "release handoff"),
        d("I can relay a manifest number when the declaration is complete.", "Is that a release decision?", "No, it is just an identifier."),
        d("I can tell an airline that a file is under review.", "Does that accuse the shipment?", "No, it avoids drawing a conclusion."),
        d("For a temperature-sensitive cargo release, I draft a discrepancy register listing matched documents, mismatched weights, and declarations not yet received.", "What does the register prevent?", "It keeps an incomplete file from being presented as cleared."),
        d("The 06:15 Kuala Lumpur bridge is the only handoff before the bonded truck's 06:35 departure.", "Can the truck wait for a second bridge?", "No, it leaves after the first decision."),
        d("I previously said a shipment was ready for release based on a scanned invoice; the original declaration later showed a restricted consignee.", "What followed?", "The truck was recalled from the gate."),
        d("A thunderstorm is forecast for the afternoon cargo ramp.", "Does the forecast resolve the declaration?", "No, it is unrelated to the consignee record."),
        d("The airline says immediate ownership will protect its on-time-delivery score.", "Does the score complete the declaration?", "No, it does not answer the compliance gap."),
        d("The original declaration and consignee screening result arrive before the bridge.", "Would that change the release basis?", "Yes, the material gap would be closed."),
        "The Kuala Lumpur team wants me to verbally own the release at 06:15. How should I rank that option?", "Reject verbal ownership until the discrepancy register and missing declaration are reviewed.", "hold the release as pending rather than describe it as cleared",
        "The live truck deadline does not justify repeating the prior recall caused by an incomplete declaration.", "The user can relay a complete manifest number.", "Relaying an identifier is not approving a restricted shipment.", "An on-time score is not release evidence.",
        ("cargo release", "draft discrepancy register", "missing declaration", "pending status"),
        ("previous release call", "clear shipment", "original declaration absent", "truck recall")),
    base.spec("U05", "industrial cybersecurity incident lead", "pr", "reject",
        ("industrial cybersecurity incident lead", "plant telemetry", "APAC bridge", "containment handoff"),
        d("I can report that an alert has fired in the plant dashboard.", "Does an alert identify the intrusion path?", "No, it only records an alarm."),
        d("I can ask a site engineer to preserve a controller image.", "Does preservation prove compromise?", "No, it protects material for analysis."),
        d("For a suspected control-network intrusion, I prepare a written confidence matrix that separates observed commands, analyst hypotheses, and telemetry gaps.", "Why use confidence levels?", "So the handoff does not turn a hypothesis into an instruction."),
        d("The 05:50 Seoul bridge is immediately before the maintenance crew reconnects the affected line at 06:20.", "Why is that constraint important?", "Containment guidance will be acted on before another analyst joins."),
        d("During a prior alert, I verbally named a workstation as compromised from a single beacon and ordered its isolation; it was a maintenance simulator, and production diagnostics were lost.", "What failed?", "I acted on an untested attribution."),
        d("The plant cafeteria opens early for the maintenance shift.", "Does that affect the incident assessment?", "No, it is not evidence about the controller."),
        d("A vendor says a strong verbal owner will calm the site manager.", "Does calm establish the command source?", "No, the telemetry gap remains."),
        d("Forensic review confirms the command source and the missing telemetry segment is recovered.", "What then?", "The containment instruction can be stated without the former qualification."),
        "How will I likely respond if asked to take verbal containment ownership on the Seoul bridge?", "I will decline a purely verbal ownership request and send the confidence matrix first.", "make the observed commands, hypotheses, and gaps visible",
        "The reconnect deadline raises the stakes, while the prior simulator mistake shows why an unsupported attribution is unsafe.", "The user can report an alert.", "Reporting an alarm does not identify a safe isolation target.", "Calming the manager does not fill the telemetry gap.",
        ("control-network alert", "prepare confidence matrix", "observed commands and gaps", "qualified containment"),
        ("prior workstation isolation", "identify compromised asset", "single beacon", "lost diagnostics")),
    base.spec("U06", "semiconductor yield engineer", "pr", "reject",
        ("semiconductor yield engineer", "fab yield log", "APAC bridge", "wafer-disposition handoff"),
        d("I can read a completed wafer count from the yield log.", "Does that explain a yield drop?", "No, counts do not determine cause."),
        d("I can request a metrology rerun.", "Does a rerun itself identify the defect?", "No, it only obtains another measurement."),
        d("For an abrupt yield decline, I write a provenance sheet separating tool readings, operator observations, and uncalibrated metrology results.", "Why preserve provenance?", "So the receiving engineer can judge what supports a disposition."),
        d("The 06:30 Taipei bridge occurs before the lot reaches the next lithography stage at 07:05.", "Can disposition be reconsidered later?", "Not before the lot advances."),
        d("I once verbally blamed a coating tool from an operator remark and held three lots; calibration later showed the metrology baseline had drifted.", "What was the impact?", "Good lots missed their processing window."),
        d("The fab lobby is displaying a new safety poster.", "Does the poster bear on the yield cause?", "No, it is only workplace context."),
        d("The production manager says a firm answer will reduce line congestion.", "Does congestion identify the faulty tool?", "No, it cannot validate the attribution."),
        d("The metrology baseline is recalibrated and repeat readings match the tool data.", "What changes?", "The source of the decline can be evaluated on aligned measurements."),
        "How will I respond to a request for verbal wafer-disposition ownership on the Taipei bridge?", "I will reject it until the provenance sheet accompanies the handoff.", "avoid assigning a cause from uncalibrated measurements",
        "The advancing-lot constraint makes the decision consequential, and the earlier unnecessary hold shows why provenance is required.", "The user can read a completed count.", "A count is not a causal diagnosis.", "Line congestion does not make a tool attribution reliable.",
        ("yield decline", "write provenance sheet", "tool readings and uncalibrated results", "deferred disposition"),
        ("previous lot hold", "blame coating tool", "drifted metrology baseline", "missed processing window")),
    base.spec("U07", "subsea cable restoration manager", "pr", "reject",
        ("subsea cable restoration manager", "fault map", "APAC bridge", "repair-vessel handoff"),
        d("I can tell the team which alarms are already closed.", "Does that locate a new cable fault?", "No, closed alarms do not establish a break position."),
        d("I can reserve a repair-vessel slot.", "Does reservation select a splice point?", "No, the fault location must support that choice."),
        d("For a cable outage, I issue a written location brief that distinguishes measured attenuation, modeled fault ranges, and unreturned survey data.", "Why distinguish the ranges?", "So a modeled estimate is not treated as a surveyed location."),
        d("The 05:35 Manila bridge is the last contact before the repair vessel must commit its route at 06:00.", "Why is the route constraint material?", "A wrong route costs the only daylight survey window."),
        d("I previously gave verbal ownership of a break location from a model alone, and the vessel searched the wrong sector until the next tide.", "What did that cost?", "The repair window was lost."),
        d("The vessel captain keeps a small herb garden on deck.", "Does that affect the fault map?", "No, it is unrelated surrounding detail."),
        d("A finance partner says immediate ownership may protect the quarterly restoration metric.", "Does the metric survey the cable?", "No, it says nothing about the fault range."),
        d("The survey return is received and narrows the break to the same range as the attenuation reading.", "What follows?", "The route can be selected on corroborated location evidence."),
        "How will I react if Manila asks for a verbal repair-vessel ownership call?", "I will reject a verbal-only call and circulate the location brief.", "keep measured, modeled, and missing survey evidence separate",
        "The vessel's route deadline and the prior wrong-sector search make an unqualified location claim unacceptable.", "The user can close known alarms.", "Closing alarms does not locate a fresh break.", "A quarterly metric does not corroborate the model.",
        ("cable outage", "issue location brief", "measured and modeled ranges", "bounded routing"),
        ("prior location call", "route repair vessel", "survey data absent", "lost daylight window")),
    base.spec("U08", "humanitarian supply coordinator", "pr", "conditional",
        ("humanitarian supply coordinator", "relief inventory", "APAC bridge", "convoy handoff"),
        d("I can report the cartons counted at a warehouse.", "Does a count confirm delivery needs?", "No, it does not show which clinics have received stock."),
        d("I can schedule a convoy once its route is approved.", "Does scheduling prove the route is safe?", "No, route verification is separate."),
        d("For a cholera-supply transfer, I prepare a written needs map marking clinic-confirmed shortages, partner reports, and districts with no current contact.", "Why keep those groups apart?", "So unconfirmed need does not become a stated destination priority."),
        d("The 06:20 Jakarta bridge precedes the convoy's river crossing, which is permitted only before 07:00.", "What limits the choice?", "The convoy cannot wait for a midday reassessment."),
        d("I once verbally directed supplies to a district from a partner rumor, while a clinic with confirmed zero stock was bypassed.", "What happened?", "The confirmed clinic waited an extra day."),
        d("The warehouse team is sharing breakfast before loading starts.", "Does breakfast determine clinic need?", "No, it is only part of the morning routine."),
        d("A donor liaison says a confident ownership call will look responsive in the briefing.", "Does responsiveness verify a shortage?", "No, it does not replace clinic confirmation."),
        d("All clinics on the proposed route have submitted same-morning stock counts.", "What changes?", "The unconfirmed districts no longer determine the route."),
        "How will I respond to taking the Jakarta convoy handoff?", "I will take it only if the needs map accompanies a route limited to confirmed shortages.", "defer any destination supported only by partner reports",
        "The crossing deadline can be met without repeating the prior diversion away from a confirmed zero-stock clinic.", "The user can report warehouse counts.", "Warehouse counts do not establish clinic-level need.", "Donor optics do not verify shortages.",
        ("cholera supplies", "prepare needs map", "confirmed and unconfirmed clinics", "conditional ownership"),
        ("previous verbal direction", "choose destination", "partner rumor", "zero-stock clinic bypassed")),
    base.spec("U09", "food-safety recall coordinator", "pr", "conditional",
        ("food-safety recall coordinator", "traceability register", "APAC bridge", "recall-scope handoff"),
        d("I can read a completed lot number to the distribution team.", "Does that define recall scope?", "No, scope depends on the traceability links."),
        d("I can open a retailer notification ticket.", "Does opening a ticket confirm contamination?", "No, it starts communication without deciding the evidence."),
        d("For a suspected allergen cross-contact event, I create a written traceability chain that tags tested lots, shared-line lots, and lots with missing sanitation records.", "Why tag the chain?", "So the bridge can distinguish evidence of exposure from a missing record."),
        d("The 07:00 Osaka bridge ends before retailers begin their first receiving cycle at 07:30.", "Why does that matter?", "Any recall notice must be correctly scoped before stock is shelved."),
        d("I previously said every shared-line lot was contaminated without checking sanitation records; retailers withdrew unaffected stock and missed the actual untested lot.", "What was the failure?", "I let a broad assumption replace the traceability chain."),
        d("A local radio station has requested an interview about the company kitchen.", "Does the interview bear on lot exposure?", "No, it is unrelated public attention."),
        d("The communications director says a sweeping ownership statement will simplify the press line.", "Does a simple press line determine scope?", "No, the chain still contains missing records."),
        d("Sanitation records and test results are available for every shared-line lot.", "What then?", "The recall scope can be set without relying on the former gap."),
        "How will I react to owning the Osaka recall-scope handoff?", "I will accept conditionally: use the traceability chain and exclude lots with unresolved sanitation records from a final scope claim.", "notify retailers of the bounded status while records are checked",
        "The receiving deadline calls for a prompt but qualified notice, not a repeat of the prior overbroad withdrawal.", "The user can relay a completed lot number.", "That does not establish cross-contact exposure.", "A simplified press line is not traceability evidence.",
        ("allergen cross-contact", "create traceability chain", "tested and missing-record lots", "conditional scope"),
        ("prior broad recall", "set recall scope", "sanitation records unchecked", "unaffected stock withdrawn")),
    base.spec("U10", "earthquake engineering assessment lead", "pr", "non_decision",
        ("earthquake engineering assessment lead", "damage survey", "APAC bridge", "inspection handoff"),
        d("I can list buildings whose inspections are complete.", "Does that classify an uninspected building?", "No, completed inspections say nothing about the others."),
        d("I can ask a municipal team to photograph a crack.", "Does a photograph establish structural cause?", "No, it is an input for an engineer."),
        d("For a suspected structural failure, I write a field log separating measured displacement, resident reports, and areas the team could not enter.", "Why maintain that separation?", "So the next lead can see the limits of the assessment."),
        d("The 06:10 APAC bridge occurs before aftershock restrictions close access to the district at 06:45.", "Does that require a classification?", "It requires a handoff, but not an unsupported safety conclusion."),
        d("After a previous quake, I verbally called a school safe from exterior photographs; an interior column crack was found during the later inspection.", "What did that teach?", "A visible exterior is not a complete structural assessment."),
        d("The municipal command tent has a generator that hums through the bridge.", "Does the generator change the building evidence?", "No, it is simply the setting."),
        d("A mayoral aide says a definite ownership statement would ease public concern.", "Does public concern settle the inspection result?", "No, reassurance is not a structural finding."),
        d("A licensed structural engineer has inspected the interior and signed the safety classification.", "What is different?", "The conclusion now rests on a complete professional inspection."),
        "How will I react if asked to take verbal ownership of the district safety classification at 06:10?", "I will not make a safety classification; I will hand off the field log and request an engineer's decision.", "state what was measured, reported, and inaccessible",
        "The access deadline supports transferring evidence, while the earlier photo-based error means no decision should be made from the incomplete survey.", "The user can list completed inspections.", "That does not classify an inaccessible building.", "Public reassurance does not replace an engineering inspection.",
        ("structural assessment", "write field log", "measured and inaccessible areas", "non-decision handoff"),
        ("prior school classification", "declare building safe", "interior uninspected", "column crack found")),
]
