"""Hand-authored S20 profiles for synchronous versus asynchronous handoffs."""

from generate_s1_s5_review_batch import d, spec


S20 = [
    spec("U01", "pharmacy operations coordinator", "cr", "reject",
         ("dispensing ledger", "coverage grid", "clinical huddle", "formulary changes"),
         d("I reviewed a routine refill queue in the afternoon without needing a call.", "Was a substitution decision pending?", "No, the orders were already reconciled."),
         d("I joined a short daytime huddle when the order sheet was complete.", "Did that settle an overnight change?", "No, the facts were fixed before the huddle began."),
         d("When an antibiotic substitution changed overnight, I compared the dispensing ledger with the prescriber notes and prepared a numbered discrepancy list that stayed in draft until the clinical pharmacist reviewed it; no ward instruction was issued from my draft.", "What stayed unpublished?", "Any ward-facing instruction until the ledger-prescriber comparison was checked."),
         d("The early huddle begins at 07:00, and the courier report upload is scheduled for 09:30.", "Are those times fixed?", "Yes, both are on the coverage grid."),
         d("Last month, a verbal handoff before the courier count arrived led the next team to hold the wrong concentration for two wards.", "What had the handoff required?", "A live ward decision before the returned-stock record was visible."),
         d("The clinical chat channel opens at 09:45, and a side room is booked from 10:00 to 10:15.", "Are those resources on the roster?", "Yes, both appear on the coverage grid."),
         d("The department head said a fast live huddle would show that I can make decisions under pressure.", "Did that add courier counts?", "No, it was about appearing decisive."),
         d("During a July substitution huddle, I posted a verbal summary from an overnight ledger read but misread which ward group the concentration change affected; the clinical lead corrected it after the courier report arrived.", "Did you wait for the courier count?", "No, I spoke from the ledger alone and named the wrong ward group."),
         "The team has asked whether I should lead the early handoff about the substitution change. What format should I use?",
         "Send a reconciled written handoff after the courier count instead of leading the early live decision.",
         "post a reconciled asynchronous handoff",
         "The antibiotic episode shows this user can prepare a ledger-linked draft without issuing ward instructions, while the premature verbal handoff shows the cost of live ward decisions before courier counts; only both justify a post-courier written handoff instead of early live leadership.",
         "The user can review routine refill queues and join huddles with complete order sheets.",
         "Those tasks establish neither a reconciled asynchronous handoff nor the reason to reject leading the early live decision.",
         "Leadership visibility does not determine whether the courier count is available for a safe handoff.",
         ("antibiotic substitution", "prepare a checked discrepancy list without issuing ward instructions", "compared ledger with prescriber notes and kept the list in draft", "no ward instruction issued from the draft"),
         ("premature verbal handoff", "choose ward concentrations", "spoke before courier counts arrived", "held the wrong concentration for two wards")),

    spec("U02", "port logistics planner", "pg", "reject",
         ("berth board", "arrival log", "dispatch channel", "weather holds"),
         d("I coordinated a normal berth update in a quick radio check.", "Was a fog sequence still pending?", "No, vessel positions were stable."),
         d("I copied the weekly arrival log onto the berth board yesterday.", "Did that assign tugs for a hold?", "No, it was an administrative update."),
         d("During the fog diversion, I marked each tug assignment on the berth board and sent a timestamped channel update once harbor control confirmed the new sequence; the pilots and yard team worked from the same ordered plan.", "What made that reliable?", "The handoff waited for an authoritative bulletin before anyone acted."),
         d("The dawn coordination request is scheduled for 05:45, and the harbor-control bulletin posts at 06:00.", "Can either time move?", "No, both are fixed on the weather-hold calendar."),
         d("A live call during a previous fog hold assigned a tug to an arrival that harbor control later delayed, leaving a container crane idle.", "What were you trying to decide?", "A berth allocation from a forecast that was still provisional."),
         d("The berth-sequence bulletin can be published on the dispatch channel once the weather board posts, and the roster permits a brief conflict call only after that publication.", "Are those arrangements confirmed?", "Yes, the channel slot and conflict-call field are available."),
         d("The terminal manager said the bridge call is where planners demonstrate command of the port.", "Did that change the bulletin timing?", "No, it was about command presence."),
         d("During a May fog hold, I logged meter changes on the arrival log, relayed harbor updates, and tracked which berth fields were still blank; the duty dispatcher assigned tugs after the bulletin posted, and no allocation was made during my segment.", "Did you assign a tug from the forecast?", "No, I maintained the hold record while the dispatcher handled allocation."),
         "How should I handle the dawn coordination request while the fog bulletin is still pending?",
         "Publish the confirmed sequence asynchronously, then use a brief live call only for remaining conflicts.",
         "use written confirmation before a targeted call",
         "The fog diversion establishes this user's value in converting a confirmed bulletin into a shared written sequence, while the early live allocation establishes why this user should not treat the pending forecast as a final instruction.",
         "The user can manage stable radio checks and routine board updates.",
         "Those tasks establish neither bulletin-linked asynchronous sequencing nor the cost of acting on a provisional forecast.",
         "Managerial visibility is not evidence that the pending bulletin can support a commitment.",
         ("fog diversion", "align pilots and yard staff on one sequence", "waited for harbor control then posted timestamped channel updates", "every team worked from the same ordered plan"),
         ("early live allocation", "assign a tug during fog", "used a provisional forecast as instruction", "left a container crane idle")),

    spec("U03", "documentary post-production editor", "sf", "accept",
         ("edit decision list", "rights tracker", "review room", "delivery weeks"),
         d("I took notes in a routine edit review without losing context.", "Was a rights replacement still open?", "No, the cut and notes were already aligned."),
         d("I joined a short live check when one sound cue needed clarification.", "Did that approve replacement footage?", "No, it settled a contained cue question."),
         d("For the archival-interview cut, I linked each removed line in the edit decision list to its rights status before sharing the change packet with the producer; the packet showed which replacements were cleared.", "What did the producer receive?", "A rights-linked handoff that connected every edit to its clearance record."),
         d("The morning producer review is at 10:00, and clearance counsel posts tracker updates in batches by 11:30.", "Are those times fixed?", "Yes, both are on the delivery-week schedule."),
         d("In an earlier live review, the group restored a compelling clip that later proved restricted, requiring a weekend recut.", "What was missing from the room?", "The rights tracker had not yet recorded clearance for that replacement."),
         d("The rights-cleared packet can be sent on the review channel after counsel updates the tracker, and the roster reserves a ten-minute live slot only for competing cut versions.", "Are both channels available?", "Yes, the packet release and narrow live slot are on the approved form."),
         d("The executive producer prefers everyone in the review room because it feels decisive.", "Did that update the rights tracker?", "No, it was about room presence."),
         d("During a July archive review, I read the decision-list timestamps, tracked which tracker entries were still blank, and recorded producer questions; the clearance lead approved replacements after the tracker updated, and no clip was selected during my segment.", "Did you restore restricted footage live?", "No, I maintained the review record while the lead handled approval."),
         "What is the best way to move the archive sequence forward while counsel is finishing its review?",
         "Send the rights-linked change packet first, then hold a narrow live choice after clearance.",
         "share a cleared packet before live selection",
         "The archival-interview cut establishes this user's value in linking edits to clearance before sharing, while the uncleared room review establishes why this user should send the packet before any live selection.",
         "The user can take routine edit notes and resolve brief cue clarifications live.",
         "Those activities establish neither rights-linked asynchronous handoffs nor the reason to defer live selection.",
         "A preference for a decisive room does not make unreviewed footage usable.",
         ("archival-interview cut", "share cleared replacement options", "linked each removed line to rights status before the packet", "the producer saw which replacements were cleared"),
         ("uncleared room review", "restore a compelling clip", "selected material before the tracker updated", "required a weekend recut")),

    spec("U04", "building automation engineer", "rr", "reject",
         ("trend dashboard", "fault register", "control desk", "seasonal switchover"),
         d("I talked through a routine temperature alarm on a service call.", "Was the drift sequence still unresolved?", "No, one subsystem was clearly at fault."),
         d("I entered a standard repair note in the fault register after a closed fix.", "Did that isolate a switchover drift?", "No, it documented a completed repair."),
         d("When the chilled-water loop drifted during switchover, I overlaid the trend dashboard with the valve-maintenance record and posted the sequence for the night technician; the annotated handoff showed the drift began after a specific valve was serviced.", "What did the technician need?", "A time-linked record before anyone named the initiating component."),
         d("The control-desk bridge is scheduled for 14:00, and the dashboard aggregates readings every fifteen minutes.", "Can either interval move?", "No, both are fixed on the switchover calendar."),
         d("A prior live bridge blamed the thermostat because its alert appeared first, but the later trends showed a delayed valve response.", "What were you trying to decide?", "Fault ownership from alert order before the time series was complete."),
         d("An annotated trend can be circulated on the fault register after one additional dashboard interval, and the roster permits a contractor call only once that circulation is logged.", "Are those arrangements authorized?", "Yes, the circulation slot and call field are available."),
         d("The facilities director said the control desk should settle every fault aloud so tenants hear quick action.", "Did that add trend intervals?", "No, it was about tenant-facing speed."),
         d("During a June drift bridge, I announced dashboard timestamps, tracked which trend intervals were still pending, and recorded operator readbacks; the duty engineer named the component after the sequence posted, and no cause was assigned during my segment.", "Did you blame the first alerting device?", "No, I maintained the bridge record while the engineer handled attribution."),
         "The control desk wants an immediate bridge on the new drift alarm. How should I proceed?",
         "Wait for the next trend interval, post the annotated sequence, and convene a live call only if contractor action is indicated.",
         "document the time sequence before escalation",
         "The chilled-water drift establishes this user's value in connecting telemetry timing to maintenance records before escalation, while the first-alert bridge establishes why this user should not assign fault from alert order alone.",
         "The user can handle routine service calls and enter standard repair notes.",
         "Those tasks establish neither trend-linked asynchronous diagnosis nor the failure mode of naming a cause from the first alert.",
         "Tenant-facing speed does not justify a causal claim without the trend sequence.",
         ("chilled-water drift", "identify the initiating component", "overlaid trends with valve-maintenance record and posted the sequence", "the drift was traced to a specific valve service"),
         ("first-alert bridge", "assign fault ownership", "followed alert order before the time series completed", "blamed the thermostat instead of the valve response")),

    spec("U05", "university accessibility adviser", "pr", "conditional",
         ("adjustment register", "course timetable", "advising channel", "exam periods"),
         d("I answered a straightforward accommodation question in a live appointment.", "Was a placement adjustment still pending?", "No, the approved note was already in the register."),
         d("I sent written guidance for a common exam arrangement last week.", "Did that settle a laboratory placement?", "No, it covered a standard provision."),
         d("For a laboratory placement adjustment, I compared the student's approved note with the course timetable and sent the instructor an implementation checklist; the checklist tied each provision to its dated slot so rest breaks were not confused with examination dates.", "What did that prevent?", "A precise registered adjustment from being applied to the wrong assessment window."),
         d("Today's case conference begins at 14:00, and specialist letters must be logged by 13:30 on the adjustment form.", "Are those times negotiable?", "No, both are fixed on the exam-period calendar."),
         d("At a past conference, a verbal assurance omitted the student's rest-break provision, and the lab scheduled an uninterrupted assessment.", "What had the conference required?", "A live arrangement before the registered note was tied to the timetable."),
         d("Approved adjustment details can be sent on the advising channel after the letter is logged, and the roster permits a brief meeting only for implementation questions.", "Are both channels available?", "Yes, the written release and meeting slot are on the approved form."),
         d("The dean said addressing the case aloud at conference reassures departments that support is responsive.", "Did that add the specialist letter?", "No, it was about departmental reassurance."),
         d("During a July case conference, I read the register timestamps, tracked which letter fields were still blank, and recorded instructor questions; the advising lead confirmed the arrangement after the letter was logged, and no provision was promised during my segment.", "Did you assure rest breaks verbally?", "No, I maintained the conference record while the lead handled confirmation."),
         "A course team has asked me to settle the pending placement arrangement in today's conference. What should I do?",
         "Send the logged adjustment details first and use a brief meeting only for implementation questions.",
         "issue the approved details before discussion",
         "The laboratory placement adjustment establishes this user's value in tying registered provisions to the timetable before discussion, while the incomplete verbal assurance establishes why this user should post logged details before any live conference settlement.",
         "The user can answer ordinary appointments and send common written guidance.",
         "Those tasks establish neither timetable-linked written handoffs nor the failure mode of promising provisions before the letter is logged.",
         "Departmental reassurance does not substitute for the student's approved record.",
         ("laboratory placement adjustment", "apply registered provisions to the correct dates", "compared approved note with timetable and sent a checklist", "rest breaks were not confused with examination dates"),
         ("incomplete verbal assurance", "arrange assessment conditions", "promised an arrangement before the registered note was complete", "scheduled an uninterrupted assessment")),

    spec("U06", "rail maintenance scheduler", "be", "accept",
         ("possession plan", "crew ledger", "planning bridge", "track renewals"),
         d("I made a routine crew confirmation on a live planning bridge.", "Was an adjacent possession boundary unsettled?", "No, the limits were already signed off."),
         d("I posted a written crew list for day work yesterday.", "Did that authorize night access across a shared boundary?", "No, it covered isolated day jobs."),
         d("For a completed depot turnout renewal, I matched each crew ledger entry to the already-signed possession plan and filed a marked-up archive copy for the audit folder; no live access was issued during that filing.", "What was the purpose?", "To leave an auditable match between crews and the signed boundary after the work was already authorized."),
         d("The afternoon planning bridge is at 15:30, and the signal authority publishes revised possession edges at 16:00.", "Can either time move?", "No, both are fixed on the renewal calendar."),
         d("A previous live bridge allocated welders from an old possession diagram, and they arrived while an inspection crew still held the adjacent section.", "What were you trying to authorize?", "Night crew access from a diagram that had already been superseded."),
         d("The crew channel opens at 16:15, and a side room is booked from 16:20 to 16:25.", "Are those resources on the roster?", "Yes, both appear on the renewal calendar."),
         d("The project sponsor said a large bridge demonstrates that the renewal is being tightly managed.", "Did that revise the possession edge?", "No, it was about bridge visibility."),
         d("During a June planning bridge, I read crew headcounts from the ledger, relayed tool requests, and recorded which isolation fields were still blank; the duty planner reconciled the counts with the revised diagram, and no access decision was made during my segment.", "Did you authorize track entry?", "No, I tracked logistics while the planner handled authorization."),
         "The night shift wants access assignments before the revised possession authority arrives. What handoff should I give?",
         "Hold authorization until the signed plan is posted, then use a narrow bridge for crews sharing a boundary.",
         "post signed access details before targeted coordination",
         "The depot archive episode shows this user can match crews to a signed plan without issuing live access, while the superseded-diagram bridge shows the cost of authorizing from an old edge; only both justify holding night authorization until the revised plan posts, then using a narrow boundary bridge.",
         "The user can confirm routine bridge assignments and post simple day crew lists.",
         "Those tasks establish neither signed-plan asynchronous handoffs nor the cost of allocating from a superseded diagram.",
         "Sponsor interest in a visible bridge does not establish safe authority to enter track.",
         ("depot turnout renewal archive", "file an auditable crew-to-plan match after authorization", "matched ledger entries to the signed plan without issuing live access", "archive copy filed; no live access issued during filing"),
         ("superseded-diagram bridge", "allocate welders for night access", "used an old possession edge before revision posted", "overlapped an inspection crew on the adjacent section")),

    spec("U07", "fashion production manager", "cr", "reject",
         ("sample tracker", "fit notes", "production chat", "factory deadlines"),
         d("I made a simple color approval in a quick video call.", "Was a measurement revision still pending?", "No, the sample and specification already agreed."),
         d("I posted a routine production update in the chat yesterday.", "Did that release final sleeve measurements?", "No, it listed sizes and dates only."),
         d("For the outerwear fit revision, I attached the fit notes to the sample tracker and sent the factory a size-by-size change list before confirming the next pattern; the grader could see each measurement behind the change.", "What made that dependable?", "Every instruction was linked to recorded fit data before release."),
         d("The factory video review is scheduled for 09:00, and fit-model measurements upload to the tracker at 08:30.", "Are those times fixed?", "Yes, both are on the factory-deadline calendar."),
         d("A previous live call agreed to shorten a sleeve from a visual impression, and the resulting sample failed when the recorded measurement arrived.", "What had the call required?", "A pattern decision before the fit data was in the tracker."),
         d("The measurement change list can be sent on the production chat once the tracker is complete, and the roster permits a short call only if the factory requires a live confirmation.", "Are both channels available?", "Yes, the change-list release and focused call slot are on the approved form."),
         d("The brand director said a live review makes the collection feel more energetic.", "Did that add fit measurements?", "No, it was about review energy."),
         d("During a July video review, I read tracker timestamps, tracked which measurement fields were still blank, and recorded factory questions; the grading lead confirmed the revision after the data posted, and no sleeve change was approved during my segment.", "Did you shorten the sleeve from appearance?", "No, I maintained the review record while the lead handled confirmation."),
         "The factory is pressing for a video decision on the revised outerwear sample. How should I respond?",
         "Send the measured change list first and reserve a live call for choosing among data-supported constructions.",
         "share fit-linked changes before a focused call",
         "The outerwear fit revision establishes this user's value in attaching fit notes to tracker data before release, while the visual sleeve call establishes why this user should not approve pattern changes from appearance alone.",
         "The user can approve aligned color samples and send routine chat updates.",
         "Those activities establish neither measurement-linked asynchronous instructions nor the failure mode of acting on visual impression.",
         "A more energetic review does not make an unmeasured alteration safe to release.",
         ("outerwear fit revision", "confirm a measured pattern revision", "attached fit notes to tracker and sent a size-by-size change list", "the grader saw each measurement behind the change"),
         ("visual sleeve call", "shorten a sleeve", "acted on appearance before fit data arrived", "produced a failing sample")),

    spec("U08", "wildlife rehabilitation supervisor", "pg", "conditional",
         ("intake board", "treatment chart", "care channel", "release seasons"),
         d("I gave a normal feeding update during a quick handover.", "Was a handling restriction still unsigned?", "No, the treatment plan was unchanged."),
         d("I left written care notes for every evening shift last week.", "Did that finalize a raptor restriction?", "No, they covered routine timing and observations."),
         d("When a raptor arrived with a wing injury, I linked the radiograph report to the treatment chart and posted a restricted-handling plan for the night carers; the plan stated exactly when to medicate and when not to attempt flight exercise.", "What did the carers receive?", "An imaging-linked written handoff with precise handling limits."),
         d("The evening handover call is at 17:30, and the visiting veterinarian signs imaging reviews after morning rounds at 11:00.", "Are those times negotiable?", "No, both are fixed on the release-season roster."),
         d("In an earlier spoken handoff, a carer interpreted 'keep quiet' as permission to move an injured owl for cleaning, worsening its stress response.", "What had the handoff required?", "A direction before the imaging-linked restriction was written on the chart."),
         d("The signed care plan can be posted on the care channel after the veterinarian signs the chart, and the roster permits a short call only to coordinate release transport.", "Are both channels available?", "Yes, the plan release and coordination slot are on the approved form."),
         d("The board chair said a live care huddle reassures donors that every animal receives attention.", "Did that add the radiograph result?", "No, it was about donor reassurance."),
         d("During a July evening handover, I read intake timestamps, tracked which chart fields awaited veterinary sign-off, and recorded carer questions; the veterinarian finalized restrictions after imaging review, and no handling limit was set during my segment.", "Did you authorize cleaning from a general spoken note?", "No, I maintained the handover record while the veterinarian handled restrictions."),
         "The evening carers want direction on the new raptor before the veterinarian signs the chart. What should I provide?",
         "Give temporary precautions now, then post the signed plan before using a short call for scheduling details.",
         "send signed care restrictions before live coordination",
         "The raptor wing injury establishes this user's value in linking radiograph findings to written handling limits, while the general spoken instruction establishes why this user should post the signed plan before live coordination on restrictions.",
         "The user can give stable feeding handovers and leave routine written notes.",
         "Those cases establish neither imaging-linked written care plans nor the failure mode of issuing general spoken directions.",
         "Donor reassurance does not establish a clinically valid handling instruction.",
         ("raptor wing injury", "give night carers precise handling limits", "linked radiograph report to treatment chart and posted a plan", "carers knew when to medicate and when not to exercise"),
         ("general spoken instruction", "guide owl cleaning", "gave only a verbal keep-quiet note before imaging was linked", "allowed stressful movement during cleaning")),

    spec("U09", "municipal records archivist", "sf", "accept",
         ("retention index", "transfer register", "records channel", "audit requests"),
         d("I answered a standard retrieval request on a short call.", "Was a disposal list still pending counsel review?", "No, the retention category was obvious."),
         d("I prepared a routine transfer list without a meeting yesterday.", "Did that authorize destruction of held boxes?", "No, it covered straightforward transfers."),
         d("For a zoning-record transfer, I cross-referenced the retention index with the litigation-hold notice and sent the department a hold-marked transfer register; the team kept the records that could not be destroyed.", "What did the register provide?", "A hold-linked written handoff before any disposal action."),
         d("The weekly records meeting is at 15:00, and counsel posts hold-notice updates by Thursday noon.", "Are those times fixed?", "Yes, both are on the audit-request calendar."),
         d("At a previous live meeting, a supervisor approved a box purge from an old index, and the records staff later discovered a new hold covering that address range.", "What had the meeting required?", "A disposal decision before the current legal notice was on the register."),
         d("A marked register can be distributed on the records channel when counsel posts the update, and the roster permits a live call only if departments dispute a retention boundary.", "Are both channels available?", "Yes, the register release and dispute-call slot are on the approved form."),
         d("The city clerk said a public live meeting proves that records decisions are transparent.", "Did that update the hold notice?", "No, it was about meeting visibility."),
         d("During a July records meeting, I read transfer timestamps, tracked which hold fields were still blank, and recorded department questions; the records supervisor authorized disposal after the notice posted, and no box purge was approved during my segment.", "Did you approve disposal from the old index?", "No, I maintained the meeting record while the supervisor handled authorization."),
         "The departments want a decision on the pending zoning boxes before counsel's update arrives. How should I handle it?",
         "Wait to send a hold-marked register, then use live discussion only for genuine classification disputes.",
         "circulate current hold markings before resolving disputes",
         "The zoning-record transfer establishes this user's value in connecting retention categories to active holds before circulation, while the old-index purge establishes why this user should wait for counsel's update before any live disposal decision.",
         "The user can handle clear retrieval calls and prepare routine transfer lists.",
         "Those tasks establish neither hold-marked asynchronous registers nor the reason to defer live disposal until the notice updates.",
         "A transparent meeting does not make a stale index legally current.",
         ("zoning-record transfer", "preserve records covered by an active hold", "cross-referenced retention index with litigation-hold notice", "the team kept records that could not be destroyed"),
         ("old-index purge", "approve box disposal", "relied on a category without the current legal notice", "risked destroying covered records")),

    spec("U10", "renewable energy procurement lead", "cr", "non_decision",
         ("bid matrix", "supplier log", "negotiation room", "contract renewals"),
         d("I discussed a routine delivery date on a supplier call.", "Was a warranty tradeoff still incomplete?", "No, the commercial terms were fixed."),
         d("I circulated a clear comparison note after ordinary bids last month.", "Did that rank incomplete compliance offers?", "No, every required field was filled."),
         d("For the inverter tender, I mapped each supplier's warranty exception against the bid matrix and sent a comparison note before asking finance to choose a preferred option; finance saw the price difference alongside the exact coverage tradeoff.", "What did the note provide?", "A complete written comparison before any live selection."),
         d("The procurement meeting is scheduled for 09:30, and grid-compliance certificates are due on the supplier form by noon.", "Can either deadline move?", "No, both are fixed on the renewal calendar."),
         d("In a previous negotiation room, the group selected the lowest quote before noticing that its warranty excluded coastal installations.", "What had the room required?", "A supplier choice before the warranty exception was connected to the quoted price."),
         d("The bid matrix can be updated on the supplier log when certificates arrive, and the roster permits a short live discussion only if finance must witness a signature.", "Are both channels available?", "Yes, the matrix update and discussion slot are on the approved form."),
         d("The chief operating officer said an immediate negotiation room would signal momentum to suppliers.", "Did that complete the compliance cells?", "No, it was about supplier-facing momentum."),
         d("During a July procurement session, I read bid timestamps, tracked which matrix cells were still blank, and recorded finance questions; the procurement director scheduled supplier selection after certificates arrived, and no preferred option was named during my segment.", "Did you select the lowest quote live?", "No, I maintained the session record while the director handled selection timing."),
         "The procurement group is deciding whether to convene suppliers this morning. What should I recommend?",
         "Do not choose a format or supplier yet; first obtain the missing certificates and complete the comparison.",
         "defer the format choice until evidence is complete",
         "The inverter tender establishes this user's value in mapping warranty exceptions to bids before any selection, while the lowest-quote negotiation establishes why this user should defer format and supplier choice until the matrix is complete.",
         "The user can manage routine delivery calls and circulate ordinary comparison notes.",
         "Those situations establish neither complete-matrix asynchronous comparison nor the reason to defer a live negotiation while cells remain blank.",
         "Supplier-facing momentum does not make missing certificates available.",
         ("inverter tender", "compare commercial tradeoffs with complete evidence", "mapped warranty exceptions against the bid matrix before finance chose", "finance saw price alongside exact coverage tradeoff"),
         ("lowest-quote negotiation", "select a supplier", "chose on price before the coastal warranty exclusion was visible", "selected an unsuitable offer")),
]
