"""Hand-authored S17 profiles for scope commitments with incomplete evidence."""

from generate_s1_s5_review_batch import d, spec


S17 = [
    spec("U01", "grant portfolio coordinator", "pr", "reject",
         ("award register", "partner brief", "funding desk", "proposal windows"),
         d("I summarized a closed partner report for the quarterly desk update.", "Was the programme still open?", "No, the figures had already been reconciled."),
         d("I arranged a one-afternoon discovery outline once the deliverable list was fixed.", "Did that need new evidence?", "No, the partner had supplied the scope sheet."),
         d("When an inland skills pilot arrived with only a concept sheet and no employer counts or delivery sites, I refused to put any delivery volume on the partner calendar and instead scheduled interviews to collect those missing inputs first.", "What did you withhold?", "Any promise about how many sites or cohorts we would run."),
         d("The funding round closes in six weeks.", "Does that deadline cover implementation?", "No, it only sets when the application must be submitted."),
         d("On last year's literacy expansion, I told the partner forum we would deliver the full regional programme before usage figures arrived; when the reconciled data showed half the expected uptake, we had to revise the public commitment.", "What had you assumed?", "That early enthusiasm could stand in for verified demand."),
         d("The award form has a required ceiling field, and finance will not release funds until that field is filled.", "Has a ceiling been entered?", "Not yet; the field is still blank."),
         d("The programme director says an ambitious public announcement would strengthen the application.", "Does that add participant evidence?", "No, publicity does not supply counts, sites, or an approved ceiling."),
         d("On last year's literacy expansion, I arranged a partner workshop and waited for attendance figures before naming a delivery scope; when the reconciled data arrived, the workshop confirmed interest but the counts still did not support a regional rollout.", "Would that support the same pledge?", "No, waiting for figures did not make the counts sufficient for a delivery promise."),
         "Should I commit our office to delivering the full coastal learning rollout?",
         "Decline the full rollout commitment and offer the funded discovery phase.",
         "limit the commitment to evidence gathering",
         "The inland skills episode shows this user can withhold delivery volume until missing inputs are collected, while the literacy expansion shows the cost of promising full regional delivery before demand is verified; only both justify declining coastal rollout while offering funded discovery.",
         "The user can summarize closed reports and outline work when the deliverable list is already fixed.",
         "Neither routine task begins from missing participant counts, sites, or a delivery ceiling.",
         "A stronger application narrative cannot replace the records and contacts needed to define scope.",
         ("inland skills pilot with missing counts", "avoid inventing a delivery volume", "withheld calendar commitments and scheduled interviews for the missing inputs", "no delivery volume was promised"),
         ("literacy expansion forum pledge", "commit to a regional programme", "promised full delivery before usage figures arrived", "forced a public revision after reconciliation")),

    spec("U02", "construction procurement adviser", "be", "reject",
         ("tender ledger", "site dossier", "procurement room", "bid cycles"),
         d("I approved a replacement order after the specification and quantities were final.", "Was the scope still uncertain?", "No, the tender package listed every line item."),
         d("I booked a two-day site survey once the access dates and output were written down.", "Did that require intrusive findings?", "No, the boundary and deliverable were already defined."),
         d("When the depot refurbishment dossier showed roof photographs and a provisional materials list but no intrusive inspection, I authorized only the condition survey and held any rebuild order.", "What stayed undefined?", "The extent of damaged structure behind the cladding and the quantity that would need replacement."),
         d("The authority has earmarked funds for an inspection and can authorize a contractor visit this month.", "Can that money cover the rebuild?", "No, it is reserved for finding the condition behind the cladding."),
         d("On a school annex cladding job, I placed the full replacement order from external photographs alone; when the intrusive report arrived, the order quantity missed hidden steel damage and had to be cancelled.", "What did you treat as sufficient?", "Visual evidence before the structure behind the cladding had been opened."),
         d("Access to the depot is limited to the school break because the loading bay operates during term time.", "Is the inspection window fixed?", "Yes, missing it would postpone the condition evidence."),
         d("A supplier says locking in its full rebuild quote today will protect us from price changes.", "Does a quote show hidden condition?", "No, a price line cannot reveal what is behind the cladding."),
         d("The facilities lead has pencilled an inspection window but says the report may not be used before tendering.", "Would that support the same purchase step?", "No, without using the report, the rebuild scope would remain untested."),
         "Can I place the full depot roof rebuild order now?",
         "Proceed with the inspection engagement only, then decide on the rebuild after its report.",
         "authorize inspection before a rebuild decision",
         "The depot dossier review shows why a rebuild amount is undefined, while the annex order episode shows the cost of treating provisional photographs as a full procurement basis.",
         "The user approves final orders and arranges surveys with explicit boundaries.",
         "Those cases did not involve hidden structural condition or an untested materials quantity.",
         "Price protection is valuable, but it does not establish what work the supplier would actually perform.",
         ("provisional depot roof dossier", "identify repair extent", "shows photographs without intrusive findings", "cannot price a full rebuild safely"),
         ("school annex cladding order", "purchase replacement materials", "ordered from photographs before intrusive inspection", "quantity missed hidden steel damage")),

    spec("U03", "community archive lead", "cr", "accept",
         ("collection log", "donor folder", "archive studio", "intake months"),
         d("I accepted a club photograph donation once the numbered inventory and signed permission arrived.", "Was the collection fully described?", "Yes, every item and public-use limit was listed."),
         d("I logged a returned folder after a donor supplied the missing accession note.", "Did that change intake scope?", "No, it completed one record already on the shelf."),
         d("When the riverworks folders arrived with decade labels but no item count, I told the donor committee we could schedule an inspection visit and accept up to two boxes after rights confirmations, not the whole collection.", "What could not be planned from the inventory?", "Storage demand, cataloguing effort, and any public display schedule."),
         d("The archive has an empty flat-file cabinet and two volunteers available on alternate Saturdays.", "Does that support unrestricted intake?", "No, it supports an initial review and a small selected transfer."),
         d("Two years ago I accepted an entire parish map collection on a verbal promise of future inventory; within a month the stacks overflowed and public access hours were cut while we counted unsorted material.", "What was missing at acceptance?", "A counted inventory and confirmed rights before anything crossed the threshold."),
         d("The annual exhibition programme is printed in three months.", "Does that force a display promise?", "No, the programme can describe the work as under review."),
         d("A councillor says announcing the entire collection would attract visitors to the exhibition.", "Does visitor interest establish contents?", "No, interest is different from a counted, rights-cleared inventory."),
         d("The donor committee agreed to an inspection visit but wants every box accepted before rights confirmations are requested.", "Would that permit the same commitment?", "No, it removes the safeguard that makes a limited transfer workable."),
         "May I accept the riverworks collection for a first, limited intake?",
         "Accept a review visit and up to two rights-cleared boxes, with no promise beyond that.",
         "accept a bounded initial transfer",
         "The riverworks inspection episode defines a defensible first boundary, while the parish map intake episode shows why accepting the whole collection without counts and rights would repeat a storage failure.",
         "The user accepts documented donations and completes standard accession records.",
         "Those cases already had item counts and permission for public use.",
         "Potential exhibition interest is not evidence of storage needs, contents, or rights.",
         ("riverworks decade-labelled folders", "plan an archive intake", "lists broad periods without item counts", "supports inspection and a two-box ceiling only"),
         ("parish map verbal acceptance", "take in a map collection", "accepted the full set before inventory or rights", "stack overflow forced access cuts")),

    spec("U04", "software delivery steward", "pg", "non_decision",
         ("release board", "integration notes", "delivery channel", "quarterly planning"),
         d("I scheduled a maintenance patch once its interface checks and rollback path were written.", "Was the launch month still provisional?", "No, the affected services and recovery steps were known."),
         d("I moved a dependency ticket to the next sprint after the owner confirmed the contract test passed.", "Did that settle a partner launch?", "No, it cleared one internal prerequisite."),
         d("When the partner portal request arrived with sketches and a preferred launch month but no interface contract or load estimate, I told the channel lead we could commit the next design slot to an interface contract and load test plan, not a firm release date.", "What was absent from a delivery promise?", "The work needed to connect safely and the capacity the portal would consume."),
         d("The team has a two-week design slot before the next planning meeting.", "Does that reserve engineering for the whole request?", "No, it reserves time to produce technical evidence."),
         d("On a prior analytics module, I published a firm launch date from the preferred month alone; after load testing failed, we rolled back and removed the date from the quarterly plan.", "What did the early date assume?", "That a preferred month could stand in for an interface contract and capacity proof."),
         d("The commercial team needs a forecast range for its quarterly materials.", "Must that be a firm release date?", "No, it can describe the request as pending the design findings."),
         d("A sales lead says a date on the slide would reassure prospective customers.", "Does reassurance make the integration known?", "No, it does not supply an interface contract or load estimate."),
         d("The platform group agreed to discuss the portal during the design slot but will not produce an interface contract or test plan.", "Would that create the same decision basis?", "No, discussion without those outputs would not support a later launch choice."),
         "Should I publish a firm launch commitment for the partner portal?",
         "Do not make a launch decision yet; commit only to the design outputs.",
         "defer the launch commitment pending design",
         "The portal triage episode shows what the current sketches can and cannot support, while the analytics date episode shows why a preferred month cannot substitute for integration evidence.",
         "The user schedules checked releases and clears internal dependency tickets.",
         "Neither involved an unknown interface contract and an unmeasured load profile.",
         "A customer-facing date can be attractive, but it is not a substitute for integration evidence.",
         ("partner portal sketch review", "determine delivery feasibility", "lacks an interface contract and load estimate", "supports design outputs only"),
         ("analytics module launch date", "commit to a release month", "published a firm date before load testing", "rollback removed the date from the plan")),

    spec("U05", "housing programme officer", "sf", "reject",
         ("repair queue", "resident file", "programme office", "allocation rounds"),
         d("I approved a standard accessibility repair once the assessment and landlord consent were on file.", "Was the route still disputed?", "No, need, location, and permission were documented."),
         d("I arranged a temporary ramp last winter after the occupational therapist listed its dimensions.", "Did that require a new survey?", "No, the permitted work and placement were specific."),
         d("When the courtyard access request arrived with residents' concerns and a rough drawing but no drainage survey, ownership boundary, or affected-household list, I offered the residents association a survey-and-engagement package rather than a build pledge.", "What would a construction promise overlook?", "Whether the path is permitted, buildable, and useful to the households expected to use it."),
         d("There is a small resident-engagement budget available before the next allocation round.", "Can that finance construction?", "No, it can fund a survey and structured feedback sessions."),
         d("On an earlier estate pathway case, I promised the allocation panel we would build the sketched route before the survey returned; when drainage and ownership conflicted with the drawing, the panel had to reopen the pledge.", "What did the early promise assume?", "That a rough drawing could stand in for verified site constraints and household need."),
         d("The allocation panel meets in eight weeks.", "Does that require a construction pledge today?", "No, it gives time to bring verified options to the panel."),
         d("A local newsletter has offered to feature a pledge for a new accessible courtyard.", "Does publicity answer drainage or ownership?", "No, it would advertise a promise ahead of the needed evidence."),
         d("At the tenant meeting, the residents association agreed to a survey but declined to collect affected-household responses.", "Would that support the same package?", "No, the survey alone would not show whether the proposal meets residents' actual access needs."),
         "Should I promise to build the courtyard path described in the request?",
         "Reject the build promise and offer the survey-and-engagement package.",
         "fund investigation before any build pledge",
         "The courtyard triage episode shows why a build pledge is premature, while the estate pathway episode shows the cost of treating a sketch as a construction commitment.",
         "The user approves assessed repairs and arranges ramps with defined dimensions.",
         "Those examples had confirmed need, location, and permission.",
         "A favourable feature may create momentum, but it cannot establish ownership, drainage, or demand.",
         ("courtyard access request review", "assess accessible route options", "omits drainage, ownership, and households", "supports investigation only"),
         ("estate pathway panel pledge", "commit to building a sketched route", "promised construction before the survey returned", "panel reopened the pledge after conflicts emerged")),

    spec("U06", "university laboratory coordinator", "rr", "conditional",
         ("equipment register", "methods folder", "laboratory office", "teaching terms"),
         d("I reserved a microscope for a class once the protocol and consumables list were approved.", "Was the method still unreviewed?", "No, the booking had a clear boundary and assigned technician."),
         d("I hosted a visiting group for a one-day trial using our established sample process.", "Did their material differ from the protocol?", "No, their samples matched the existing method."),
         d("When a spectroscopy group asked for standing suite time with only a one-page aim, I required their solvent list and SDS before the first booking and refused to open the calendar until both arrived.", "What stayed closed?", "Any recurring booking while the handling facts were still unknown."),
         d("The suite has one unused afternoon each fortnight.", "Does that create a standing arrangement?", "No, it only marks when a single session could be scheduled."),
         d("Last term I opened recurring suite access for a polymer group that arrived without advance sample details; mid-session the technician stopped work when an incompatible solvent appeared, and teaching bookings were displaced for decontamination.", "What was missing before access began?", "Advance sample information and a reviewed handling procedure."),
         d("The next teaching term begins in seven weeks.", "Why is that relevant?", "Any recurring use must be understood before it competes with teaching bookings."),
         d("The department chair says recurring access would demonstrate cross-group cooperation.", "Does cooperation establish sample compatibility?", "No, goodwill does not replace a safe handling procedure."),
         d("Last term I ran a one-day trial for a polymer group that followed every posted safety step and produced a written procedure; when we opened recurring access the next month, their samples still conflicted with a teaching solvent line and bookings were displaced.", "Would that support the same grant?", "No, a successful trial did not show that recurring use would stay compatible with teaching schedules."),
         "Can I offer the materials group recurring use of the imaging suite?",
         "Offer one supervised trial only, conditional on advance sample details and a resulting procedure.",
         "grant a conditional trial rather than recurring access",
         "The spectroscopy episode shows this user can withhold standing access until handling facts arrive, while the polymer episode shows the cost of opening recurring use without those facts; only both justify a single conditional trial for the materials group.",
         "The user manages approved class bookings and has hosted a trial under an existing process.",
         "Those activities did not introduce unknown sample handling or uncertain technician demand.",
         "Cross-group cooperation is valuable, but it cannot demonstrate compatibility with the suite.",
         ("spectroscopy group standing-time request", "keep the suite calendar closed until handling facts arrive", "required solvent list and SDS before any booking", "calendar stayed closed until both arrived"),
         ("polymer group recurring access", "grant standing suite time", "allowed access without advance sample information", "incompatible solvent stopped work and displaced teaching")),

    spec("U07", "festival logistics planner", "pr", "accept",
         ("venue grid", "supplier pack", "planning shed", "event season"),
         d("I confirmed a food-court extension after the vendor list included equipment loads and the layout was calculated.", "Was the operating plan still open?", "No, footprint and power needs were settled before contracts went out."),
         d("I updated the venue grid when a stallholder supplied its final power draw.", "Did that commit a new zone?", "No, it filled in a slot already reserved on the sheet."),
         d("When the night-market proposal named a waterfront zone and interested vendors but had no crowd-flow drawing or wet-weather arrangement, I told the authority liaison we could confirm a one-evening pilot after the route study and only within the marked zone.", "What could not be committed from the proposal?", "Full vendor capacity and an operating plan if access narrowed in rain."),
         d("The festival reserve includes funds for a temporary route study and one evening of stewarding.", "Does that fund an entire night market?", "No, it funds testing the route and running a limited pilot."),
         d("Two seasons ago I announced a season-long waterfront market from vendor interest alone; on the first rain night the access route failed and stewards closed the zone before the programme notice could be updated.", "What had not been established?", "Crowd flow under narrowing access and a wet-weather operating plan."),
         d("The printed programme closes next month.", "Can the pilot appear there?", "Yes, as a one-evening trial with its conditions stated."),
         d("A merchant group says calling it a season-long market would attract more applications.", "Does that supply a rain plan or crowd-flow design?", "No, it would advertise capacity that has not been established."),
         d("The waterfront authority agreed to a one-evening pilot but says the route study may be skipped if vendor interest is high.", "Would that support the same plan?", "No, vendor interest does not show that the route can operate safely."),
         "Can I confirm a one-evening waterfront night-market pilot?",
         "Confirm the limited pilot, subject to the route study and marked-zone limit.",
         "confirm a condition-bound pilot",
         "The night-market triage episode defines a narrow pilot that the current proposal can support, while the earlier season-long announcement episode shows why vendor interest alone cannot substitute for route and rain planning.",
         "The user confirms documented stall areas and has extended a food court after calculations were complete.",
         "Those examples had settled layout and equipment requirements.",
         "More applications could be useful, but demand cannot verify crowd flow or wet-weather access.",
         ("unfinished night-market proposal", "test waterfront trading", "lacks crowd-flow and rain arrangements", "does not support a season commitment"),
         ("season-long waterfront announcement", "operate a waterfront market", "confirmed from vendor interest without route or rain planning", "access failed on the first rain night")),

    spec("U08", "public health outreach manager", "be", "reject",
         ("outreach calendar", "service map", "health hub", "campaign periods"),
         d("I scheduled a clinic information session once the referral route and interpreter coverage were confirmed.", "Was follow-up care still undefined?", "No, the clinic had reserved appointments before we advertised."),
         d("I added a vaccination pop-up to the calendar after the site manager listed room capacity and entry flow.", "Did that promise ongoing service?", "No, it was a single event with booked follow-up."),
         d("When the neighbourhood wellbeing idea proposed weekend drop-ins but named neither referral partners nor the languages needed by the largest resident groups, I told the campaign team we could commit to listening sessions and service mapping first.", "What is unsafe about promising the programme now?", "We could invite people to disclose needs without a clear route to appropriate support."),
         d("The hub has funds for listening sessions and can print multilingual information once languages are identified.", "Can that run the full service?", "No, it can map needs and prepare a responsible first offer."),
         d("On a prior wellness corridor pilot, I advertised recurring weekend drop-ins before clinics agreed to review findings or reserve referral slots; residents arrived with needs the hub could not route onward.", "What was missing at launch?", "A confirmed referral path and language plan tied to the sessions."),
         d("The campaign team must submit its autumn calendar in five weeks.", "Does that require advertising weekend drop-ins?", "No, it can list the listening sessions and a later service decision."),
         d("A communications agency says a broad launch message would show the hub is responsive.", "Does that create referral capacity?", "No, responsiveness is not the same as a route for care."),
         d("The local clinics have offered general encouragement but will not review findings or reserve referral slots.", "Would that support the same commitment?", "No, without that connection, the sessions would not establish a safe path onward."),
         "Should I announce recurring weekend wellbeing drop-ins for the neighbourhood?",
         "Reject the recurring-service announcement; commit to listening sessions and mapping first.",
         "begin evidence gathering before service launch",
         "The wellbeing triage episode shows why a recurring service promise is premature, while the corridor pilot episode shows the harm of advertising drop-ins before referral and language evidence exists.",
         "The user schedules sessions with confirmed interpreters and has advertised a pop-up with reserved appointments.",
         "Those cases already had a defined follow-up service.",
         "A broad launch message might look responsive, but it does not provide referral capacity or language coverage.",
         ("unmapped wellbeing proposal", "design neighbourhood support", "has no partners or language plan", "requires preliminary listening work"),
         ("wellness corridor drop-in launch", "open recurring weekend sessions", "advertised before clinics agreed to review or reserve slots", "residents arrived with unrouted needs")),

    spec("U09", "heritage restoration officer", "cr", "conditional",
         ("condition file", "works diary", "restoration office", "conservation seasons"),
         d("I authorized routine cleaning once the material and method were documented in the condition file.", "Was a new intervention still disputed?", "No, previous treatment records applied."),
         d("I arranged a small stone repair last spring after the mason measured the affected edge.", "Did that commit a full restoration?", "No, we knew the loss, access method, and permitted scope."),
         d("When the clocktower proposal showed surface staining in photographs but no mortar analysis, access survey, or water-entry confirmation, I told the conservation panel we could start a diagnostic survey and temporary weather protection while any permanent restoration waited on findings.", "Why could restoration not be promised yet?", "Different causes would require different work, and access may control what is possible."),
         d("The preservation fund can pay for a diagnostic survey and temporary weather protection.", "Does it cover a full restoration package?", "No, that would need a defined treatment and separate approval."),
         d("On a prior town-gate project, I promised full stone restoration before the anniversary from photographs alone; when the survey showed water ingress rather than mortar failure, the scaffold had to be reconfigured at extra cost.", "What did the early promise assume?", "That visible staining identified the governing cause and treatment."),
         d("The town anniversary is four months away.", "Does that justify choosing a treatment without analysis?", "No, it makes temporary protection more useful while the cause is learned."),
         d("A tourism group says promising a restored tower by the anniversary would help its campaign.", "Does a campaign determine the cause of staining?", "No, it cannot tell us whether water, mortar, or access is the governing issue."),
         d("The conservation panel agreed to a surveyor visit but declined temporary protection while results are reviewed.", "Would that support the same response?", "No, it would remove the immediate protective step that makes delay more acceptable."),
         "Can I commit to restoring the clocktower before the town anniversary?",
         "Commit to the diagnostic survey and temporary protection, conditional on later findings for restoration.",
         "authorize diagnosis and interim protection",
         "The clocktower triage episode shows what interim work the current photographs support, while the town-gate promise episode shows why a restoration commitment cannot rest on staining alone.",
         "The user authorizes documented cleaning and has arranged a measured stone repair.",
         "Those examples had identified material loss, access, and a permitted method.",
         "Tourism value may favour visible progress, but it does not identify the cause or treatment.",
         ("unanalysed clocktower condition", "select an appropriate intervention", "has staining without cause or access survey", "requires diagnosis before restoration"),
         ("town-gate anniversary promise", "commit to full stone restoration", "promised treatment from photographs before survey", "scaffold reconfigured after water ingress was found")),

    spec("U10", "regional transport engagement officer", "sf", "accept",
         ("route atlas", "consultation file", "mobility office", "service reviews"),
         d("I arranged a school-route consultation once the affected stops and operator contacts were listed.", "Was demand still unmeasured?", "No, families had identified pickup points and the operator shared ridership counts."),
         d("I updated the route atlas after the operator confirmed a temporary diversion boundary.", "Did that announce a permanent shuttle?", "No, it recorded a short operational change."),
         d("When the hill-district shuttle idea arrived with resident requests and a rough corridor but no stop-level demand counts or operator view of turning constraints, I told the committee we could announce a one-month demonstration and diary review, not a permanent route pattern.", "What could not be promised from the file?", "A permanent shuttle pattern or the number of journeys it could sustain."),
         d("The mobility fund includes money for a travel diary exercise and a one-month demonstration service.", "Does that establish a permanent route?", "No, it lets us gather demand and operating evidence."),
         d("On a valley loop consultation, I pledged a permanent route before the operator shared turning assessments; mid-trial the service had to be withdrawn when a narrow corner could not be safely repeated.", "What was decided too early?", "A lasting pattern before stop counts and turning feasibility were known."),
         d("The council transport committee meets after the demonstration period.", "Why is that useful?", "It provides a place to consider the evidence before any lasting commitment."),
         d("A campaign group says a permanent-route pledge would make the consultation more exciting.", "Does excitement establish demand or turning feasibility?", "No, it would decide those questions before the demonstration answers them."),
         d("The operator has agreed to run a one-month demonstration but will not share turning assessments or review the travel diaries.", "Would that support the same plan?", "No, the demonstration would not connect its results to a responsible next decision."),
         "Can I announce a one-month hill-district shuttle demonstration?",
         "Announce the one-month demonstration and evidence review, with no permanent-route promise.",
         "announce a reviewable demonstration",
         "The hill-district triage episode shows a defensible public commitment the current file can support, while the valley loop pledge episode shows why a permanent route cannot be promised before turning and demand evidence exists.",
         "The user has led consultations with listed stops and has improved a school route using counts and feedback.",
         "Those examples had both practical operating information and usable demand evidence.",
         "A permanent-route pledge may energize participation, but it cannot establish turning feasibility or ongoing use.",
         ("rough hill-district shuttle file", "test hill-district mobility", "lacks stop counts and turning assessment", "cannot support a permanent pattern"),
         ("valley loop permanent pledge", "announce a lasting shuttle route", "pledged permanence before turning assessments", "service withdrawn when a corner proved unsafe")),
]
