"""Hand-authored S16 profiles for live troubleshooting leadership."""

from generate_s1_s5_review_batch import d, spec


S16 = [
    spec("U01", "digital forensics shift lead", "pg", "accept",
         ("evidence timeline", "custody queue", "response alcove", "breach rotations"),
         d("I gave the audit team a short update from last month's closed intrusion file.", "Was that a live investigation?", "No, it was a routine summary after the finding was settled."),
         d("I answered a custody question yesterday using the signed evidence register.", "Did you have to choose a containment action?", "No, I only located the recorded transfer."),
         d("During the April payroll-access inquiry, I spent the afternoon aligning endpoint logs, badge entries, and account records so the response team could identify the compromised account; my written timeline was adopted without correction.", "What part did you own?", "I built and checked the cross-record evidence chain before the team met."),
         d("Nominations close today at 17:00, and tomorrow's response call begins at 08:15.", "Is either time movable?", "No, both are fixed on the incident calendar."),
         d("On a June ransomware bridge, I chaired the live triage and named a contractor laptop as the entry point from the first alert stream; later disk records showed it was only a relay, and the premature isolation delayed containment.", "What had you been trying to do?", "I was trying to give the responders one source while raw signals were still arriving."),
         d("The system can export a combined host-and-badge file at 07:45, and the staffing form lists bridge chair, evidence analyst, and liaison scribe as separate fields.", "Are those arrangements confirmed?", "Yes, the export slot and all three roster fields are available."),
         d("Chief counsel called the chair assignment a high-visibility opportunity.", "Did counsel add incident evidence?", "No, that was only a comment about exposure."),
         d("On an August ransomware bridge, I kept the incident clock, read the prescribed checkpoints, and assigned action owners from the runbook; the designated chair made the source judgment, and the investigation remained open at handoff.", "Were you the source decision-maker?", "No, I handled the bridge mechanics while someone else owned that judgment."),
         "Tomorrow's roster lists bridge chair, evidence analyst, and liaison scribe. How should I rank those three assignments for myself?",
         "Rank the evidence-analyst assignment first and the bridge-chair assignment last, with liaison scribe between them.",
         "accept the evidence-analyst assignment",
         "The payroll inquiry shows that this user contributes a viable cross-record synthesis contribution, while the ransomware bridge shows why this user should rank live chairing last among the three posted roles.",
         "The user can summarize closed findings and locate entries in a custody register.",
         "Those routine tasks establish neither the cross-record synthesis contribution nor the reason to rank live chairing last.",
         "Visibility says nothing about how to order all three assignments from the user's episode history.",
         ("April payroll-access inquiry", "identify the compromised account", "aligned endpoint, badge, and account records into a checked timeline", "timeline adopted without correction"),
         ("June ransomware bridge", "direct containment toward the entry point", "chaired triage and named a source from the first alert stream", "premature isolation delayed containment")),

    spec("U02", "broadcast transmission coordinator", "sf", "reject",
         ("signal path sheet", "studio roster", "master-control desk", "airtime faults"),
         d("I briefed a producer on a resolved audio fault after yesterday's replay review.", "Was another routing choice required?", "No, the program had already ended."),
         d("I updated the studio roster before the weekend rehearsal.", "Did that involve tracing a signal?", "No, it was an ordinary scheduling correction."),
         d("Between programs in March, I reconstructed a regional dropout from router histories and replay clips, marked the failing distribution amplifier on the path sheet, and the replacement passed the evening test.", "What was your goal?", "To leave master control a verified repair target before the next transmission."),
         d("Opening music is scheduled for 06:58, and the fault call has a twelve-minute slot.", "Can the slot be extended?", "No, the broadcast clock is fixed."),
         d("During a May breaking-news fault call, I ran recovery and switched the satellite route after one meter flashed; the fault was in the studio return, so my switch also removed the backup feed.", "What were you trying to restore?", "The anchor's return before airtime, but I chose a route while the path was still unresolved."),
         d("Engineering has one rehearsal bay from 05:40 to 06:20, and the coordinator rota may assign a separate pre-show path check.", "Are those resources reserved?", "Yes, the bay and rota field are booked."),
         d("The network vice president said the opening call is where coordinators show command presence.", "Did that change the broadcast schedule?", "No, it was a visibility argument."),
         d("During a July breaking-news fault call, I logged each meter change, relayed the switcher's readbacks, and kept the countdown; the duty director selected the route, and the unresolved fault was passed to engineering after the bulletin.", "Did you choose a recovery route?", "No, I maintained the call record and timing."),
         "Management has offered me the opening-news recovery lead. Does that assignment fit?",
         "Reject the opening-news recovery-lead assignment and take responsibility for the pre-show path check instead.",
         "reject the live recovery lead",
         "The regional-dropout episode supplies a useful pre-show tracing contribution, while the breaking-news episode shows that this user's rapid route control can compound a fault.",
         "The user can explain resolved faults and maintain a studio roster.",
         "Neither routine episode shows the user's value in path tracing or the distinct cost of putting this user in live route command.",
         "Command-presence rhetoric does not establish either component of the role choice.",
         ("March regional dropout", "identify a repair target before the next transmission", "reconstructed the path from router histories and replay clips", "replacement amplifier passed the evening test"),
         ("May breaking-news fault call", "restore the anchor return before airtime", "led recovery and switched from one flashing meter", "backup feed was also removed")),

    spec("U03", "medical device vigilance analyst", "rr", "reject",
         ("complaint chronology", "safety inbox", "vigilance office", "recall alerts"),
         d("I presented a completed complaint chronology to quality last week.", "Was the cause still disputed?", "No, the review had already closed."),
         d("I sent three hospitals the standard follow-up form on Monday.", "Did you assess their devices?", "No, I only requested the listed records."),
         d("For a February pump-alarm cluster, I reconstructed service histories and clinician reports overnight, isolated a shared valve batch, and proposed a focused field check that confirmed worn valves.", "What was the intended result?", "To turn scattered complaints into a testable inspection scope."),
         d("The regulator call starts at 09:00, and hospitals must receive a holding message by 09:30.", "Are those deadlines fixed?", "Yes, they are on the liaison schedule."),
         d("In an April rapid-recall huddle, I acted as the initial hazard voice and attributed alarms to a battery lot from one hospital report; maintenance records later tied them to a software update, and unaffected units were held.", "What were you expected to provide?", "A live causal position before the complaint histories had been reconciled."),
         d("The overnight review room is available until 08:30, and the call agenda has separate evidence-summary and initial-hazard slots.", "Is that division permitted?", "Yes, both slots are on the approved agenda."),
         d("A senior director said the initial-hazard slot would raise my profile.", "Did the director supply complaint records?", "No, it was career advice."),
         d("In a June rapid-recall huddle, I maintained the complaint queue, read each hospital's timestamps, and recorded requested follow-ups; the appointed medical officer issued the provisional hazard position, which remained pending at adjournment.", "Did you attribute the alarms?", "No, I administered the same huddle while the medical officer owned causation."),
         "The liaison asks me to rank the two regulator-call duties. Should initial hazard spokesperson come first?",
         "Do not rank initial hazard spokesperson first; rank overnight evidence synthesis above it.",
         "rank evidence synthesis above hazard spokesperson",
         "The pump investigation shows a strong overnight synthesis contribution, and the recall huddle shows a specific failure when this user is made the live initial-causation voice.",
         "The user can present closed reviews and send standard information requests.",
         "Those activities establish neither a comparative strength in reconstructing an open cluster nor a reason to demote the live hazard duty.",
         "Career exposure does not resolve the ordering between the two duties.",
         ("February pump-alarm cluster", "define a testable inspection scope", "reconstructed service histories and clinician reports", "focused check confirmed worn valves"),
         ("April rapid-recall huddle", "give an initial hazard position", "attributed alarms from one hospital report", "unaffected units were held")),

    spec("U04", "marine weather routing adviser", "pr", "non_decision",
         ("route forecast board", "vessel schedule", "routing cabin", "storm diversions"),
         d("I answered a captain's tide question from the published table yesterday.", "Was a diversion underway?", "No, it was a routine port call."),
         d("I copied the weekly vessel schedule onto the routing board.", "Did that settle any storm route?", "No, it was an administrative update."),
         d("For a January North Sea diversion, I spent four hours combining wave ensembles, fuel margins, and port limits, then issued a route note that kept the vessel outside the gale window and within reserve.", "What did the vessel need?", "A feasible route whose weather and harbor constraints had been considered together."),
         d("A standing-role response is due Friday, and any storm bridge must end before the vessel's next position report.", "Are those timing rules confirmed?", "Yes, they are in the dispatch notice."),
         d("On a March squall bridge, I served as default route adviser and directed a vessel toward one port from a fresh radar sweep; a closure notice already in another queue arrived later, and the detour consumed its fuel reserve.", "What was your goal on the call?", "To choose the immediate diversion, but the standing setup separated the harbor information from my view."),
         d("Dispatch permits a one-incident trial with separate route-note and bridge-adviser slots, and the standing designation may remain open until the trial ends.", "Is that arrangement authorized?", "Yes, both slots and the later decision date are on the roster."),
         d("A fleet manager described the standing title as a good demonstration of decisiveness.", "Did that specify the incident package?", "No, it only described the title."),
         d("On a May squall bridge, I opened the standard incident package, announced each weather update, and entered the captain's acknowledgments; the shore superintendent chose the diversion, and the route remained undecided when my shift ended.", "Did you own the route recommendation?", "No, I performed the bridge's information-handling task without making that choice."),
         "Dispatch can decide the standing title now or use the next incident as a trial. What should I propose?",
         "Defer the standing designation and take the route-note slot for the one-incident trial.",
         "trial route-note work before a standing decision",
         "The North Sea episode supplies a viable route-note contribution for the trial, while the squall episode supplies the user-specific reason not to finalize this user as default live adviser now.",
         "The user handles routine tide questions and schedule-board updates.",
         "Those facts reveal neither the user's integrated route-note contribution nor the reason to postpone this user's standing designation.",
         "The title's prestige supports neither half of the trial proposal.",
         ("January North Sea diversion", "produce a feasible storm route", "combined wave, fuel, and port constraints", "vessel avoided the gale and retained reserve"),
         ("March squall bridge", "choose an immediate diversion", "advised from radar while harbor information sat in another queue", "detour consumed the fuel reserve")),

    spec("U05", "university identity access architect", "be", "accept",
         ("access dependency map", "account ledger", "identity workshop", "enrollment outages"),
         d("I explained a closed login ticket to the service desk yesterday.", "Was a systemwide action pending?", "No, the fix was already recorded."),
         d("I corrected an account owner in the ledger last week.", "Did that change an entitlement?", "No, it was a contact-field correction."),
         d("During a February admissions outage, I traced applicant accounts through the directory, group feed, and enrollment service, drew the dependency map, and proposed the rollback that restored access without removing scholarship entitlements.", "What had you set out to do?", "Find the break and give the team a narrowly targeted recovery plan."),
         d("Registration opens at 10:00, and the continuity call occupies the 09:30-to-09:50 window.", "Can either time move?", "No, both are fixed by the registrar."),
         d("In an April enrollment bridge, I acted as incident commander and ordered single sign-on disabled after the failed-login count rose; the break was a stale group feed, and the broad action removed advisers' access.", "What decision were you making?", "I was choosing the campuswide intervention before the dependency chain was traced."),
         d("The staffing sheet permits a dependency-mapper beside a separate incident commander, and the architecture room is reserved from 08:30.", "Are both arrangements authorized?", "Yes, they are listed in the continuity plan."),
         d("The chief information officer said commanders on registration day are remembered at promotion time.", "Did that add account data?", "No, it was about recognition."),
         d("In a June enrollment bridge, I maintained the action log, displayed the service inventory, and read back owners; the appointed commander chose the intervention, and no cause was established before the call ended.", "Were you deciding which service to disable?", "No, my responsibility was the bridge record and display."),
         "Registration recovery needs a named owner. Which staffing box fits my history?",
         "Accept the dependency-mapper slot and leave incident command to a separate person.",
         "take mapper, not command",
         "The admissions episode establishes this user's concrete value in building a targeted dependency plan, while the enrollment episode establishes the cost of giving this user broad live intervention authority.",
         "The user can explain a closed ticket and correct ledger contact data.",
         "Those tasks do not establish either the mapper contribution or the reason to separate command authority.",
         "Promotion visibility is not evidence for either side of the responsibility split.",
         ("February admissions outage", "restore applicant access without entitlement loss", "traced the directory, feed, and enrollment dependencies", "targeted rollback restored access"),
         ("April enrollment bridge", "choose a campuswide recovery action", "commanded from failed-login counts before tracing dependencies", "advisers lost access")),

    spec("U06", "pharmaceutical cold-chain investigator", "cr", "reject",
         ("temperature excursion ledger", "shipment register", "quality review room", "distribution alerts"),
         d("I summarized a closed temperature review for warehouse staff on Tuesday.", "Was product disposition still open?", "No, quality had already signed it."),
         d("I entered a carrier reference in the shipment register yesterday.", "Did that interpret any sensor data?", "No, it was a clerical update."),
         d("For a January vaccine excursion, I aligned logger downloads, door records, and carrier scans over an evening, isolated the actual warm interval, and recommended testing that retained the usable batch.", "What were you trying to determine?", "Whether the shipment history justified testing rather than blanket disposal."),
         d("The hospital procurement call starts at 11:15, and replacement orders close at noon.", "Are those times fixed?", "Yes, the hospital confirmed both."),
         d("On a March rapid-distribution call, I chaired disposition and ordered destruction from one high sensor reading; the logger had been beside an open loading door, and usable doses were discarded.", "What did the call require from you?", "An immediate batch decision while the rest of the transit record was still absent."),
         d("The full carrier packet is scheduled for delivery at 14:00, and the quality review room is booked from 14:15 to 16:00.", "Are those resources available tomorrow?", "Yes, both reservations are confirmed."),
         d("The commercial lead said chairing the hospital call would make me the person who saved the account.", "Did that add shipment records?", "No, it was sales framing."),
         d("On a May rapid-distribution call, I tracked the lot numbers, read the procurement deadlines, and recorded attendees' requests; the quality director made the disposition decision, and the batch remained quarantined afterward.", "Did you decide whether to destroy it?", "No, I handled call administration while the director owned disposition."),
         "Quality has three open slots: urgent hospital chair, afternoon packet review, and morning roster update. How should I rank them for myself?",
         "Rank the afternoon packet review first and the urgent hospital chair last, with the morning roster update between them.",
         "decline rapid disposition leadership",
         "The vaccine excursion establishes a useful full-record review contribution, while the distribution call establishes why this user should rank urgent disposition leadership last among the three posted duties.",
         "The user can summarize a closed review and update a shipment register.",
         "Neither routine action supplies the comparative value of full-record reconstruction or the user-specific reason to rank urgent chairing last.",
         "Commercial visibility cannot order all three duties from the user's episode history.",
         ("January vaccine excursion", "determine a proportionate batch response", "aligned logger, door, and carrier records", "testing retained the usable batch"),
         ("March rapid-distribution call", "make an immediate batch disposition", "chaired the call and acted on one high reading", "usable doses were discarded")),

    spec("U07", "wildlife disease surveillance officer", "pg", "conditional",
         ("outbreak linkage chart", "sample registry", "field epidemiology unit", "migration alerts"),
         d("I gave a park officer the published result for one tagged bird.", "Did that define an outbreak route?", "No, it was a routine confirmed finding."),
         d("I corrected a collection date in the sample registry last week.", "Did that join any cases?", "No, it fixed one record."),
         d("During a February waterfowl mortality investigation, I combined banding histories, laboratory matches, and wetland visits, proposed a narrow sampling route, and the field team confirmed the source marsh on its first day.", "What was your operational goal?", "Turn the linked records into a limited collection plan."),
         d("The interagency call begins at 05:30, and rangers depart at 06:10.", "Are those times negotiable?", "No, they are fixed on the collection order."),
         d("On an April avian-alert call, I led route selection from two nearby sighting reports and sent crews toward one corridor; later samples showed separate introductions, so the crews searched the wrong wetlands.", "What had you been asked to decide?", "The first collection route before any laboratory comparison was present."),
         d("The laboratory match report has a 05:00 delivery slot, and the field portal accepts an overnight sightings map until 05:15.", "Are both channels operational?", "Yes, those delivery windows are confirmed."),
         d("The agency head said local officials expect the call leader to sound decisive.", "Did that add a sample result?", "No, it was about presentation."),
         d("On a June avian-alert call, I plotted reported coordinates, read the collection order, and logged ranger check-ins; the incident epidemiologist selected the route, and the suspected corridor remained unconfirmed at handoff.", "Did you infer a common source?", "No, I handled the call's field-information flow."),
         "Under what circumstance should I agree to lead the next dawn collection decision?",
         "Agree only when both the laboratory match report and the sightings map are present before route selection.",
         "lead only with both source and location inputs",
         "The mortality investigation shows that this user can convert laboratory-plus-location linkage into a bounded route, while the alert call shows that this user's leadership from proximity alone misdirects collection.",
         "The user can relay one confirmed result and correct one registry date.",
         "Those tasks establish neither integrated route planning nor the failure mode that makes both inputs necessary.",
         "Pressure to sound decisive does not establish the two-part condition.",
         ("February waterfowl mortality investigation", "choose a narrow collection route", "combined banding, laboratory, and wetland records", "source marsh confirmed on the first field day"),
         ("April avian-alert call", "select the first collection route", "led from nearby sightings without laboratory comparison", "crews searched the wrong wetlands")),

    spec("U08", "payment settlement operations strategist", "pg", "accept",
         ("settlement sequence ledger", "clearing schedule", "payments review pod", "liquidity incidents"),
         d("I explained yesterday's settled exception at the morning handoff.", "Was another payment released?", "No, I reviewed a completed entry."),
         d("I updated a bank holiday in the clearing schedule.", "Did that reconcile an obligation?", "No, it was a calendar change."),
         d("During a February cross-border delay, I reconciled collateral postings with confirmation times, marked the true obligation order in a sequence ledger, and proposed a hold release that cleared without an unmatched transfer.", "What was your aim?", "Give the desk a complete sequence before anyone moved funds."),
         d("The market closes at 16:30, and the liquidity bridge is limited to fifteen minutes.", "Can either deadline move?", "No, both are fixed externally."),
         d("On an April liquidity bridge, I held release authority and released the queue as soon as collateral appeared; confirmation was still pending, and the desk created an unmatched exposure.", "What were you trying to accomplish?", "Move the queue before close, but I treated the first prerequisite as the whole sequence."),
         d("The bridge roster includes a sequence-controller seat without release authority, and the clearing feed can be displayed on that seat.", "Is that seat available?", "Yes, it is unassigned and enabled."),
         d("The treasury director called release authority a rare chance to make a visible market decision.", "Did that alter the clearing entries?", "No, it was about status."),
         d("On a June liquidity bridge, I announced the timestamps, maintained the queue order, and recorded bank acknowledgments; the treasury officer held release authority, and two pending items remained queued at close.", "Could you release those items?", "No, my role covered sequence control rather than authorization."),
         "Treasury is staffing sequence controller and release authority separately. Where should I volunteer?",
         "Volunteer for sequence controller and not for release authority.",
         "accept the sequence-controller role",
         "The cross-border episode establishes the user's value in constructing obligation order, while the liquidity episode establishes a user-specific error when that same person combines partial sequencing with live release authority.",
         "The user can explain settled entries and maintain the clearing calendar.",
         "Those routine actions reveal neither the sequence-building contribution nor the reason to separate release authority.",
         "The prestige of market authority does not determine the responsibility boundary.",
         ("February cross-border delay", "release a hold without creating an unmatched transfer", "reconciled collateral and confirmation into obligation order", "settlement cleared without unmatched exposure"),
         ("April liquidity bridge", "release queued payments before close", "used release authority after only collateral appeared", "unmatched exposure was created")),

    spec("U09", "dam safety instrumentation specialist", "rr", "reject",
         ("sensor correlation sheet", "reservoir log", "inspection trailer", "spillway alarms"),
         d("I explained a confirmed gauge trend to maintenance on Monday.", "Was an emergency action pending?", "No, it was a closed weekly review."),
         d("I entered the reservoir level in the daily log.", "Did that validate a sensor?", "No, it was the standard reading entry."),
         d("After a January seepage anomaly, I went to the inspection gallery, compared piezometer history, rainfall records, and drain photographs, and prioritized the blocked drain that crews cleared before pressure rose.", "What did you need to accomplish?", "Connect the instrument pattern to a physical inspection target."),
         d("The downstream message is scheduled for 07:20, and the operations call begins at 07:00.", "Are those times fixed?", "Yes, emergency management set them."),
         d("During a March spillway alarm, I advised the call remotely and treated one rising piezometer as structural movement; operators made an unnecessary gate change before a technician found a clogged sensor line.", "What were you trying to decide?", "Whether the gauge justified immediate spillway action without a physical look."),
         d("A gallery inspection slot is available at 06:15, and the remote-adviser seat is assigned separately from field verification.", "Are both positions authorized?", "Yes, they appear on the response roster."),
         d("The emergency manager said the remote adviser is the public's authoritative technical voice.", "Did that inspect the sensor line?", "No, it was about communications."),
         d("During a May spillway alarm, I received gauge readbacks, entered reservoir changes, and relayed the warning timetable from the remote desk; the operations chief chose the gate action, and the sensor status was still open at sign-off.", "Did you make the structural judgment?", "No, I maintained the remote information record."),
         "They ask me to rank remote spillway adviser against field verification for the next alarm. Which belongs lower?",
         "Rank remote spillway adviser lower and choose field verification.",
         "reject the remote adviser assignment",
         "The seepage episode establishes this user's useful field-correlation role, while the spillway episode shows that remote advisory authority led this user to equate a lone reading with structural movement.",
         "The user can brief a confirmed trend and enter a reservoir reading.",
         "Neither routine task supports the field-versus-remote ranking because neither supplies both the field contribution and the remote failure.",
         "Public-authority language adds no evidence about the appropriate work location.",
         ("January seepage anomaly", "identify the physical inspection target", "compared instruments, rainfall, and gallery photographs on site", "blocked drain cleared before pressure rose"),
         ("March spillway alarm", "advise whether immediate gate action was needed", "remotely equated one gauge rise with structural movement", "unnecessary gate change preceded discovery of a clogged line")),

    spec("U10", "railway rolling-stock reliability planner", "be", "conditional",
         ("failure linkage board", "fleet diary", "maintenance planning cell", "service disruptions"),
         d("I explained a completed door-fault review to the depot team.", "Was a withdrawal decision still open?", "No, the units had returned to service."),
         d("I added a maintenance window to the fleet diary.", "Did that identify a failing component?", "No, it was a schedule entry."),
         d("For recurring door faults in February, I compared a week of telemetry, repair histories, and driver reports, isolated one actuator series, and scheduled targeted replacements that reduced cancellations.", "What decision did the depot need?", "Which component group justified focused maintenance."),
         d("The service-recovery call starts at 15:45, and platform allocations lock at 16:05.", "Can either time move?", "No, dispatch has fixed both."),
         d("On an April disruption bridge, I led the fleet recommendation from two similar door reports and urged withdrawal of the whole class; the controller followed it, but later telemetry showed a platform transmitter fault, so the class withdrawal and spare-train deployment had been unnecessary.", "What were you trying to decide?", "How broadly to withdraw trains before the component comparison arrived."),
         d("The depot comparison has a 15:30 delivery slot, and the call roster has separate reliability-note and withdrawal-authorization fields.", "Are those arrangements confirmed?", "Yes, the delivery slot and both roster fields are booked."),
         d("The operations chief said broad rush-hour decisions are how planners earn trust.", "Did that identify a failing part?", "No, it was a comment about reputation."),
         d("On a June disruption bridge, I tracked affected unit numbers, read back depot owners, and logged service gaps; the duty controller set the withdrawal scope, and the suspected component remained under review.", "Did you recommend a fleet scope?", "No, I handled the bridge's unit tracking."),
         "How should I define my part in the next recovery call?",
         "Offer the reliability recommendation, but leave withdrawal authorization, including any whole-class action, to the duty controller.",
         "recommend reliability action without withdrawal authority",
         "The recurring-fault episode shows that this user can contribute a comparison-based reliability recommendation, while the disruption episode shows why a separate controller should retain withdrawal authority.",
         "The user can discuss a completed review and update a maintenance calendar.",
         "Those tasks establish neither the user's comparison-based recommendation value nor the reason to separate withdrawal authority.",
         "Trust-building rhetoric supports neither side of the authority split.",
         ("February recurring door faults", "select a focused maintenance group", "compared telemetry, repairs, and driver reports across the fleet", "targeted replacements reduced cancellations"),
         ("April disruption bridge", "set the withdrawal scope", "led from two similar reports without cross-fleet comparison", "the whole class was withdrawn and spare trains deployed unnecessarily")),
]
