"""Hand-authored S18 profiles for review quality under interruption vs protected focus."""

from generate_s1_s5_review_batch import d, spec


S18 = [
    spec("U01", "standards editor", "rr", "reject",
         ("manuscript queue", "editorial calendar", "review studio", "revision weeks"),
         d("I cleared routine correspondence between meetings without losing track.", "Did those messages affect a publication decision?", "No, they were routing notes rather than comparative readings."),
         d("I discussed a draft with an author for twenty minutes after the section list was settled.", "Was that a decision-bearing comparison?", "No, it was a clarifying conversation about structure."),
         d("For the flood-resilience handbook, I reserved a two-hour quiet block, compared all cited thresholds side by side, and caught that the executive summary overstated the evidence.", "What made the correction possible?", "I could hold the competing passages together until the claim was checked."),
         d("My review calendar marks protected blocks as unavailable on the shared schedule.", "Why make that boundary visible?", "A posted block keeps ordinary questions from fragmenting the evidence check."),
         d("While reviewing the accessibility guide in the open office, I answered chat requests between sections and approved a recommendation before noticing its exception clause.", "What caused the miss?", "Each restart made the earlier qualification harder to retain."),
         d("The production coordinator holds a 15:00 calendar slot after my review block.", "Is that slot fixed?", "Yes, it is booked on the editorial calendar."),
         d("The publisher says rapid chat replies make an editor look collaborative.", "Does that settle the review schedule?", "No, responsiveness is useful only if the decision remains accurate."),
         d("While reviewing the accessibility guide in the open office, I answered chat requests between sections, recorded page references, and handed the draft to the associate editor for the recommendation wording.", "Did you approve the recommendation?", "No, I only proofread formatting while the associate editor owned the judgment."),
         "How should I handle author questions during tomorrow's policy manuscript review?",
         "Ask colleagues to batch nonurgent questions and preserve a protected evidence-review block.",
         "protect a continuous comparison block",
         "The flood-resilience review shows that uninterrupted comparison catches consequential qualifications, while the accessibility chat episode shows why this user's split attention produces a missed exception.",
         "The user handles routine correspondence and brief author conversations well.",
         "Neither activity requires tracking qualifications across a long, decision-bearing comparison.",
         "Publisher praise for rapid replies concerns availability, not the quality of the resulting publication judgment.",
         ("flood-resilience handbook review", "verify an evidence claim", "compared cited thresholds in a quiet block", "overstatement corrected before publication"),
         ("accessibility guide chat review", "approve a recommendation", "answered chats between sections before approving", "exception clause missed")),

    spec("U02", "supply allocation analyst", "pr", "accept",
         ("allocation sheet", "carrier dashboard", "planning pod", "shortage cycles"),
         d("I answered a warehouse status call while updating a simple count.", "Did that require balancing scarce stock?", "No, the answer was a location lookup rather than a floor calculation."),
         d("I made a quick route adjustment for one truck with a clear spare capacity figure.", "Was any clinic minimum at stake?", "No, it was one destination and a known surplus."),
         d("During the pediatric formula shortage, I muted alerts for ninety minutes, reconciled clinic minimums against carrier limits, and assigned the remaining pallets without leaving any rural clinic below its floor.", "Why did the quiet interval matter?", "The tradeoffs stayed visible long enough to test each allocation."),
         d("I have asked dispatch to page me only for a vehicle breakdown or a safety hold while I am assigning constrained inventory.", "Is that a delay tactic?", "No, it separates urgent transport facts from ordinary requests for updates."),
         d("In last spring's saline shortage, five pop-up messages arrived as I moved quantities between regions, so I followed the latest request rather than the minimum-coverage table and shorted one clinic.", "What was lost?", "I stopped checking the allocation against the shared floor."),
         d("Dispatch can route ordinary delivery questions to the dashboard and call me once after the allocation is locked.", "Would that support better decisions?", "Yes, the live exceptions would remain distinct from routine noise."),
         d("The regional director says answering every ping demonstrates ownership of the shortage.", "Does that define the right operating method?", "No, ownership includes making the distribution defensible."),
         d("In last spring's saline shortage, five pop-up messages arrived as I moved quantities between regions, but the duty supervisor entered the final numbers while I read back carrier confirmations.", "Did you choose the regional split?", "No, I relayed status while the supervisor owned the allocation decision."),
         "What interruption rule should I set while allocating the remaining formula across clinics?",
         "Use a protected allocation interval with escalation only for transport or safety exceptions.",
         "set an exception-only interruption rule",
         "The formula reconciliation episode shows that protected comparison preserves clinic floors, while the saline pop-up episode shows why this user's interrupted reallocations can drop a site below its agreed minimum.",
         "The user can handle simple status calls and isolated route changes.",
         "Those tasks do not require preserving a multi-clinic scarcity calculation across competing requests.",
         "Director pressure to answer every ping does not show that continuous interruption improves allocation quality.",
         ("pediatric formula shortage allocation", "meet clinic minimums", "muted routine alerts while reconciling the sheet", "all clinics retained minimum coverage"),
         ("saline shortage reallocation", "distribute scarce supply", "followed pop-up requests during regional moves", "one clinic fell below its floor")),

    spec("U03", "airworthiness records reviewer", "be", "reject",
         ("maintenance dossier", "inspection roster", "records bay", "return-to-service days"),
         d("I logged a completed inspection while mechanics asked routine questions nearby.", "Was a release decision pending?", "No, I was recording an item already signed off."),
         d("I attended a short daily stand-up after lunch.", "Did that involve reconciling superseding records?", "No, it was a schedule and parts update."),
         d("For a landing-gear return, I closed the door, traced the serial history through three repair records, and found that one life-limited part had been entered under the wrong suffix.", "What did that prevent?", "The aircraft was held until the part record was corrected."),
         d("Our records protocol now gives discrepancy reviews a closed-door hour unless an aircraft safety event requires immediate contact.", "Why such a specific rule?", "The review depends on following one chain without importing unrelated tasks."),
         d("During a noisy shared-desk review, I took calls from the hangar between records and cleared a component whose inspection interval had been superseded by a later bulletin.", "Why was it cleared?", "I resumed from the old page and treated the newer bulletin as already checked."),
         d("The shift lead can hold ordinary paperwork questions and bring them to me after the discrepancy decision is documented.", "Does that preserve operations?", "Yes, mechanics still receive a single, complete answer."),
         d("A manager says an open desk keeps the maintenance team agile.", "Does agility justify the release method?", "No, a release must rest on the complete record chain."),
         d("During a noisy shared-desk review, I took calls from the hangar between records, logged timestamps, and passed the stack to the certifying inspector for the clearance decision.", "Did you authorize the release?", "No, I maintained the record flow while the inspector owned the interval check."),
         "Why do I insist on a closed-door review period before signing an airworthiness discrepancy?",
         "Because reliable discrepancy decisions require uninterrupted tracing of the full maintenance record chain.",
         "require protected record tracing",
         "The landing-gear trace shows that uninterrupted dossier review catches suffix errors before release, while the shared-desk episode shows why call-driven restarts led this user to clear a superseded interval.",
         "The user can log completed inspections and attend short stand-ups.",
         "Neither involves reconciling superseding records before authorizing return to service.",
         "Open-desk agility is not evidence that fragmented review supports a sound release decision.",
         ("landing-gear return review", "verify a life-limited part", "traced serial history behind a closed door", "incorrect suffix caught before release"),
         ("shared-desk component review", "clear an inspection record", "took hangar calls between source documents", "superseded interval overlooked")),

    spec("U04", "community grant panel chair", "cr", "conditional",
         ("scoring matrix", "panel diary", "civic meeting room", "award rounds"),
         d("I welcomed applicants and answered procedural questions during an open panel session.", "Did that require ranking competing benefits?", "No, it was orientation rather than matrix comparison."),
         d("I read a single application at home after dinner.", "Does solo reading establish panel readiness?", "No, the decision depends on comparing every proposal against the same matrix."),
         d("For the youth-housing round, I asked the panel to hold calls for one hour, compared each proposal against the published criteria, and identified that a popular bid had omitted a required safeguarding partner.", "How did the pause help?", "We could test the enthusiasm against the full evidence before voting."),
         d("I now reserve the final scoring hour for panel-only discussion and ask staff to interrupt only for a legal or conflict-of-interest issue.", "Why those exceptions?", "Those facts can change eligibility; status requests cannot."),
         d("At the neighborhood-greening round, staff brought in sponsor messages and arrival questions between votes, so the panel elevated the most discussed proposal without rechecking its maintenance budget.", "What did the interruptions change?", "They displaced the final comparison of affordability."),
         d("The program officer can log sponsor messages and present them once the scoring record is complete.", "Would that ignore partners?", "No, it gives them a considered response after the award basis is settled."),
         d("A council member says a visible, continuously accessible panel feels more democratic.", "Does that answer the scoring concern?", "No, fairness also requires equal attention to every submitted criterion."),
         d("At the neighborhood-greening round, staff brought in sponsor messages and arrival questions between votes, but I kept the matrix open and the duty scorer recorded ranks while I handled arrivals.", "Did you select the award?", "No, I managed room flow while the scorer maintained the affordability comparison."),
         "Can I make the final grant-scoring hour interruption-free while still allowing essential issues through?",
         "Yes—protect the scoring hour and allow interruptions only for eligibility, legal, or conflict-of-interest issues.",
         "protect final scoring with narrow exceptions",
         "The youth-housing comparison shows that uninterrupted matrix review exposes missing safeguarding evidence, while the greening round shows why message-driven restarts displaced an affordability check.",
         "The user manages procedural exchanges and solo application reading.",
         "Neither is the collective act of applying a shared matrix across competing awards.",
         "Being continuously visible to sponsors does not substitute for a fair, complete comparison.",
         ("youth-housing grant round", "rank eligible proposals", "held calls during matrix comparison", "missing safeguarding partner identified"),
         ("neighborhood-greening round", "select an award", "accepted sponsor messages between votes", "maintenance budget not rechecked")),

    spec("U05", "pharmacovigilance case lead", "pg", "non_decision",
         ("case narrative", "safety inbox", "review room", "signal weeks"),
         d("I acknowledged a routine safety inbox item within minutes.", "Was a medical assessment underway?", "No, I was routing the item rather than building a chronology."),
         d("I joined a brief team huddle after a standard case day.", "Did that involve causality review?", "No, it was a workload and deadline check."),
         d("For a liver-injury report, I silenced noncritical inbox alerts, aligned the laboratory timeline with dosing changes, and recommended follow-up rather than a premature signal escalation.", "What supported that judgment?", "The chronology remained intact through the alternative explanations."),
         d("Our case handbook permits immediate interruptions during review only for a new death report or a regulatory deadline due that day.", "Why not answer all incoming cases?", "Most can be triaged without breaking the current medical chronology."),
         d("On an earlier neuropathy case, I answered team messages between source documents and treated a pre-existing symptom as treatment-emergent, sending the case for unnecessary escalation.", "What did the restart obscure?", "The baseline note at the start of the timeline."),
         d("A colleague can screen the inbox and bring only death reports or same-day deadlines to the review room.", "Would that leave other reports unattended?", "No, they remain logged and are addressed at the next triage point."),
         d("The department head says every rapid reply reassures external partners.", "Does reassurance determine the review sequence?", "No, the medical assessment must remain accurate before it is communicated."),
         d("On an earlier neuropathy case, I answered team messages between source documents, logged each attachment time, and handed the chronology draft to the medical reviewer for classification.", "Did you classify symptom timing?", "No, I maintained the file order while the reviewer owned the emergent-versus-baseline call."),
         "Before I commit to covering the live safety inbox during a complex causality review, what should I arrange?",
         "Defer that commitment until a screener and a narrow escalation path are arranged.",
         "defer inbox coverage pending safeguards",
         "The liver-injury review shows that protected chronology work avoids premature escalation, while the neuropathy message episode shows why this user's interrupted review misclassified baseline symptoms.",
         "The user can acknowledge routed inbox items and attend short team huddles.",
         "Neither task requires sustaining a clinical chronology across alternative explanations.",
         "Partner reassurance is a communication goal, not evidence that constant interruptions improve case assessment.",
         ("liver-injury causality review", "assess causality", "silenced noncritical alerts while aligning chronology", "premature escalation avoided"),
         ("neuropathy chronology review", "classify symptom timing", "answered messages between documents", "baseline symptom misclassified")),

    spec("U06", "litigation discovery manager", "sf", "accept",
         ("privilege log", "case calendar", "review suite", "production windows"),
         d("I responded to a lawyer's document-location question immediately.", "Was a privilege decision involved?", "No, the answer was a known folder path."),
         d("I scanned a short email chain in a shared workspace.", "Did that require linking advice across attachments?", "No, it was a single thread with one recipient list."),
         d("Before the merger production, I set a ninety-minute no-message block, linked the executive emails to the outside-counsel thread, and withheld a document whose copied recipient initially made it look nonprivileged.", "What made the distinction visible?", "I could follow the purpose and recipients across the full chain."),
         d("The review team uses a red-status signal during privilege calls, and the review suite is booked from 14:00 to 16:00.", "Why use that signal?", "It marks the scheduled review window on the case calendar."),
         d("During a prior rolling production, I answered progress pings between attachments and released an email before noticing that its attachment requested legal advice.", "What failed?", "The connector between the email and attachment was lost on restart."),
         d("The project coordinator inbox is open from 16:05 to 16:20 for progress questions.", "Is that inbox a standing live channel?", "No, it is a timed inbox window on the case calendar."),
         d("Lead counsel says instant availability helps the team feel supported.", "Does that require interrupting privilege analysis?", "No, support can be scheduled around the decision-sensitive review."),
         d("During a prior rolling production, I answered progress pings between attachments, indexed each file, and passed the batch to senior counsel for the release decision.", "Did you clear the email for production?", "No, I maintained the review log while counsel owned the privilege call."),
         "For tomorrow's production review, what interruption rule should I set while deciding privilege calls?",
         "Use protected review blocks with only court, cutoff, or security escalations.",
         "use protected privilege-review blocks",
         "The merger chain review shows that uninterrupted linking prevents disclosure, while the rolling production ping episode shows why this user's fragmented review missed a privileged attachment.",
         "The user can answer location questions and scan short email chains in shared space.",
         "Neither requires determining privilege across a linked set of documents before production.",
         "Counsel's preference for instant visibility does not reduce the disclosure risk of fragmented analysis.",
         ("merger production privilege review", "determine privilege", "linked executive emails with counsel thread uninterrupted", "sensitive document withheld"),
         ("rolling production email review", "clear an email for release", "answered progress pings between attachments", "privileged attachment connection missed")),

    spec("U07", "distribution exception supervisor", "rr", "reject",
         ("exception board", "dock schedule", "dispatch office", "peak weeks"),
         d("I directed a driver to an open dock while radios were active.", "Did that require a system-wide reroute?", "No, it was one assignment to an available bay."),
         d("I handled a brief late-day package trace for one customer order.", "Was a driver-hours calculation involved?", "No, the scan history was short and bounded."),
         d("When snow closed two depots, I stepped into the planning room for an hour, matched priority medical deliveries to driver hours and road restrictions, and reassigned routes without sending a driver beyond legal limits.", "Why leave the radio desk?", "The route dependencies needed one stable view."),
         d("During weather exceptions, dispatch now sends only road closures, vehicle safety issues, or medical-delivery changes into the planning room.", "Why those categories?", "They can alter the route plan; ordinary location requests do not."),
         d("Last December I took radio calls between each reassignment and moved a driver toward a late pickup without noticing that the detour would exhaust the driver's remaining hours.", "What did that create?", "A second reroute and a delayed medical shipment."),
         d("The radio operator can keep the live board and relay the three route-changing exceptions at a scheduled check.", "Can operations still respond?", "Yes, urgent facts remain immediate without turning every query into a restart."),
         d("The depot manager says a supervisor should be visibly available on the radio all day.", "Does visibility establish a safe routing process?", "No, the driver-hour calculation still has to be completed."),
         d("Last December I took radio calls between each reassignment, read back road closures, and logged driver IDs while the route planner entered the final sequence.", "Did you assign the late pickup?", "No, I maintained radio traffic while the planner owned the hours calculation."),
         "Should I remain on the radio while building tomorrow's weather-exception route plan?",
         "Reject that arrangement; delegate routine radio traffic and receive only route-changing exceptions.",
         "delegate routine radio traffic during planning",
         "The snow-closure planning episode shows that protected reconciliation preserves driver-hour and medical constraints, while the December radio episode shows why this user's interrupted reassignment missed an hours-limit conflict.",
         "The user can assign a dock and trace one package amid normal radio traffic.",
         "Neither involves reconciling a system-wide reroute against driver hours, roads, and delivery priority.",
         "Visible radio availability does not show that continual interruptions are safe for constrained routing.",
         ("snow depot closure planning", "reassign priority routes", "matched roads, driver hours, and medical deliveries in a quiet room", "legal routes preserved"),
         ("December weather reassignment", "reroute a late pickup", "took radio calls between each change", "driver-hours conflict missed")),

    spec("U08", "product research synthesis lead", "pr", "conditional",
         ("evidence wall", "research calendar", "insight lab", "planning sprints"),
         d("I shared a single interview finding in a live design critique.", "Had the finding been checked against the study set?", "Yes, it was one confirmed quote rather than a cross-interview pattern."),
         d("I answered a quick question about a participant quote.", "Was a full synthesis underway?", "No, it was recall of one recorded line."),
         d("For the onboarding study, I booked a focus morning, grouped interviews by first-use behavior, and found that the apparent navigation problem was actually an account-verification delay.", "What allowed that distinction?", "The contradictory quotes stayed alongside the timing data until the pattern resolved."),
         d("My team calendar reserves synthesis mornings, with interruptions allowed for participant welfare, a study cancellation, or a launch decision that cannot wait.", "Why protect that time?", "Those exceptions materially change the study; routine design questions can wait for the evidence readout."),
         d("During the payments study, designers dropped into the lab asking for headline conclusions between interview clusters, so I named checkout as the problem before comparing the failed-verification sessions.", "What happened later?", "The team built around the wrong friction point for a sprint."),
         d("The design lead can gather questions and join a scheduled evidence readout once the synthesis map is complete.", "Would designers be excluded?", "No, they would receive conclusions with the contradictory evidence included."),
         d("The vice president says rapid answers keep product momentum high.", "Does momentum determine whether the interpretation is mature?", "No, momentum is costly when it sends a sprint toward the wrong problem."),
         d("During the payments study, designers dropped into the lab asking for headline conclusions between interview clusters, but I logged their questions and continued grouping sessions while the research director drafted the readout summary.", "Did you name checkout as the problem?", "No, I kept the interview clusters intact while the director owned the headline."),
         "How should I handle designers' live questions while I am synthesizing the next study?",
         "Use protected synthesis time, with only welfare, cancellation, or truly time-critical launch interruptions.",
         "set a protected synthesis window",
         "The onboarding synthesis shows that protected comparison separates verification delay from navigation, while the payments interruption episode shows why this user's premature checkout conclusion misdirected a sprint.",
         "The user can share checked findings and answer narrow quote questions live.",
         "Neither establishes that a cross-interview interpretation is ready before the full pattern is compared.",
         "Product momentum is valuable, but it does not validate an interpretation formed around interruptions.",
         ("onboarding study synthesis", "identify first-use friction", "compared quotes with timing data in a focus morning", "verification delay identified"),
         ("payments study synthesis", "name the primary friction", "answered designers between interview clusters", "wrong checkout problem framed for sprint")),

    spec("U09", "claims quality auditor", "be", "accept",
         ("claim file", "audit rota", "quality office", "appeal cycles"),
         d("I approved a routine address correction while colleagues asked questions.", "Was a coverage interpretation involved?", "No, it was a clerical field fix."),
         d("I attended a short morning calibration huddle.", "Did that reconstruct a disputed chronology?", "No, it aligned scoring examples across auditors."),
         d("In an appeal involving storm damage, I used a quiet review block to align photographs, contractor invoices, and the adjuster's notes, then found that the denial had overlooked the documented date of loss.", "What followed?", "We corrected the decision before the customer entered a longer appeal."),
         d("The audit rota gives contested denials a protected hour, with interruptions limited to a vulnerable-customer escalation, a regulator request, or a data-security issue.", "Why separate those cases?", "They may change urgency or legal obligations; routine queue questions do not."),
         d("On a water-damage audit, I answered queue messages between exhibits and treated a later repair estimate as if it predated the policy lapse, upholding a denial incorrectly.", "What did the switching affect?", "I lost the sequence that gave the estimate its meaning."),
         d("A queue coordinator can hold routine questions and send one summary at the end of the contested-file block.", "Would claimants wait longer?", "No, the queue continues moving while the appeal-risk decision is checked properly."),
         d("The operations head says an auditor who answers instantly keeps service levels high.", "Does that show the denial is sound?", "No, service level and evidentiary accuracy both matter."),
         d("On a water-damage audit, I answered queue messages between exhibits, indexed each document, and passed the file to the senior auditor for the coverage determination.", "Did you uphold the denial?", "No, I maintained the exhibit order while the senior auditor owned the chronology judgment."),
         "Why should contested-denial audits have a protected review hour instead of taking routine queue messages throughout?",
         "Because accurate appeal-risk decisions depend on uninterrupted reconstruction of the file chronology.",
         "protect contested-file chronology review",
         "The storm-damage appeal shows that focused alignment corrects an overlooked loss date, while the water-damage queue episode shows why this user's interrupted review reversed a repair estimate's chronology.",
         "The user can process address corrections and join short calibration huddles.",
         "Neither requires evaluating disputed coverage through a multi-document timeline.",
         "Instant queue responsiveness does not establish that an interrupted denial review is accurate.",
         ("storm-damage appeal audit", "check a denial", "aligned photos, invoices, and notes in a quiet block", "overlooked loss date corrected"),
         ("water-damage denial audit", "review a disputed denial", "answered queue messages between exhibits", "repair-estimate chronology reversed")),

    spec("U10", "emergency procurement reviewer", "cr", "reject",
         ("supplier file", "purchase calendar", "procurement cell", "surge events"),
         d("I confirmed that a vendor form was complete while taking a call from finance.", "Was a source-selection decision underway?", "No, it was a completeness check rather than an award comparison."),
         d("I briefed a buyer on a standard purchase order in ten minutes.", "Did that compare eligibility and capacity?", "No, the order followed an existing contract line."),
         d("During the flood-response purchase, I moved to a quiet room, checked supplier capacity against conflict disclosures and delivery maps, and stopped an award to a firm whose depot could not serve the isolated district.", "What did the focused review prevent?", "We avoided committing emergency funds to a supplier that could not perform."),
         d("The procurement cell routes only a safety shortage, a legal injunction, or a supplier withdrawal into an active emergency-award review.", "Why limit contact that tightly?", "Those facts can alter the award; routine status calls cannot."),
         d("During the generator procurement last year, I accepted buyer calls between supplier files and selected the lowest quoted vendor before noticing its capacity statement excluded the required delivery window.", "What was the consequence?", "The order had to be cancelled and reissued under greater pressure."),
         d("A duty buyer can log status requests and interrupt only when a supplier withdraws or the emergency need changes.", "Does that slow the response?", "No, it keeps the award review decisive while preserving the facts that truly alter it."),
         d("The incident director says buyers need an answer every time they call.", "Does that make the proposed review safe?", "No, speed without a complete award basis can create a second emergency."),
         d("During the generator procurement last year, I accepted buyer calls between supplier files, logged each quote timestamp, and handed the comparison sheet to the duty chief for the award selection.", "Did you select the vendor?", "No, I tracked the files while the duty chief owned the capacity check."),
         "The incident director wants me to review emergency supplier awards while answering buyers' live calls. What should I say?",
         "Reject that setup; assign a duty buyer to handle routine calls and preserve a protected award review with narrow escalations.",
         "delegate routine calls during emergency award review",
         "The flood-response comparison shows that uninterrupted source review excludes a nonperforming supplier, while the generator call episode shows why this user's fragmented award review missed a delivery-window exclusion.",
         "The user can complete vendor forms and give short standard-order briefings.",
         "Neither requires validating supplier eligibility, capacity, conflicts, and delivery feasibility under emergency pressure.",
         "Demand for instant buyer answers does not demonstrate that fragmented award review protects public funds or service.",
         ("flood-response supplier review", "select a capable supplier", "checked capacity, conflicts, and delivery maps without interruption", "nonperforming firm excluded"),
         ("generator emergency award review", "award an emergency order", "accepted buyer calls between supplier files", "delivery-window exclusion missed")),
]
